(function(root){
 'use strict';
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const node=id=>document.getElementById(id);
 let owner='',activeUid='',refs=[],messageRef=null,messageCallback=null,epoch=0,threadEpoch=0,session=0,loaded=new Set(),errors=new Set(),initialScroll=true;
 const drafts=new Map(),sending=new Map();
 const allowed=()=>state.role==='admin'&&!!state.user?.uid&&state.c47AdminPage==='support'&&!!node('c70Thread');
 function remember(){const input=node('c70ChatInput');if(activeUid&&input)drafts.set(activeUid,input.value);}
 function stop(reset=false){remember();epoch++;threadEpoch++;if(messageRef&&messageCallback)messageRef.off('value',messageCallback);messageRef=null;messageCallback=null;refs.forEach(([r,c])=>r.off('value',c));refs=[];activeUid='';loaded.clear();errors.clear();if(reset){session++;owner='';drafts.clear();sending.clear();state.c70SupportUsers={};state.c70SupportNotices=[];state.c70AdminChatUid='';if(node('c70Thread'))node('c70Thread').innerHTML='';}}
 function health(){const h=node('cdSupportHealth');if(!h)return;h.textContent=errors.size?'ข้อมูลแชทบางส่วนโหลดไม่สำเร็จ กรุณาลองใหม่':loaded.size<2?'กำลังโหลดรายชื่อและข้อความ…':'';h.className=errors.size?'error':'muted';}
 function watch(){if(!allowed())return;if(owner!==state.user.uid){stop(true);owner=state.user.uid;}if(refs.length)return;
  if(c70SupportRef&&c70SupportCb){c70SupportRef.off('value',c70SupportCb);c70SupportRef=null;c70SupportCb=null;}
  const uid=owner,generation=epoch,current=()=>allowed()&&owner===uid&&state.user.uid===uid&&generation===epoch;
  for(const [key,ref] of [['notices',db.ref('adminSupportNotifications').orderByChild('createdAt').limitToLast(300)],['users',db.ref('users')]]){const cb=s=>{if(!current())return;loaded.add(key);errors.delete(key);if(key==='users')state.c70SupportUsers=s.val()||{};else state.c70SupportNotices=Object.entries(s.val()||{}).map(([id,v])=>({...v,id})).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));c70RenderInbox();paintHeader();health();if(!activeUid&&loaded.size===2){const first=state.c70AdminChatUid||state.c70SupportNotices[0]?.userId;if(first)c70OpenAdminChat(first);}};refs.push([ref,cb]);ref.on('value',cb,()=>{if(!current())return;loaded.add(key);errors.add(key);health();});}
 }
 c70AdminChatPage=function(){return '<div class="c70Page cd-support-page">'+c70AdminHeader('แชทกับผู้ใช้','เลือกผู้ใช้เพื่ออ่านและตอบกลับข้อความ')+'<p id="cdSupportHealth" role="status"></p><section class="c70Panel c70Chat"><aside class="c70Inbox"><div class="c70InboxHead"><h2>ข้อความ</h2><input id="c70ChatSearch" class="field" placeholder="ค้นหาชื่อปัจจุบัน ชื่อเดิม หรือ Email" aria-label="ค้นหาบทสนทนา" oninput="c70RenderInbox()"><button type="button" data-support="reload">รีเฟรชรายชื่อ</button></div><div id="c70InboxRows"></div></aside><main id="c70Thread" class="c70Thread"><div class="c70Empty" style="margin:auto">เลือกผู้ใช้เพื่อเริ่มสนทนา</div></main></section></div>';};
 c70LoadAdminChat=watch;
 c70RenderInbox=function(){const h=node('c70InboxRows');if(!h||state.role!=='admin')return;const q=(node('c70ChatSearch')?.value||'').trim().toLowerCase();const rows=c70SupportPeople().filter(x=>{const u=state.c70SupportUsers[x.uid]||{},old=Object.values(u.nameHistory||{}).flatMap(n=>[n.oldName,n.newName,n.oldNameEn,n.newNameEn]).join(' ');return !q||[c70PersonName(x.uid,x.last),u.email,u.nameEn,old].join(' ').toLowerCase().includes(q);});h.innerHTML=rows.map(x=>{const name=c70PersonName(x.uid,x.last);return '<button type="button" class="c70InboxItem '+(activeUid===x.uid?'active':'')+'" data-support-user="'+E(x.uid)+'"><span class="c70Avatar">'+E(name.slice(0,1).toUpperCase())+'</span><span><b>'+E(name)+'</b><span>'+E(x.last.message||'เปิดบทสนทนา')+'</span></span>'+(x.unread?'<span class="c70Unread">'+x.unread+'</span>':'')+'</button>';}).join('')||'<div class="c70Empty">'+(loaded.size<2?'กำลังโหลด…':'ไม่พบบทสนทนาตามที่ค้นหา')+'</div>';};
 function paintHeader(){const h=node('cdSupportThreadHead');if(!h||!activeUid)return;const u=state.c70SupportUsers[activeUid]||{},name=c70PersonName(activeUid,state.c70SupportNotices.find(n=>n.userId===activeUid)||{});h.innerHTML='<div class="c70Avatar">'+E(name.slice(0,1).toUpperCase())+'</div><div class="cd-support-person"><b>'+E(name)+'</b><div class="small">'+E(u.role==='athlete'?'นักกีฬา':u.role==='coach'?'โค้ช':'ผู้ใช้')+' · Support Chat</div></div>'+(u.role==='athlete'?'<button type="button" class="cd-name-history-button" data-profile-history="'+E(activeUid)+'">ประวัติชื่อ</button>':'');}
 function markRead(uid){const updates={};state.c70SupportNotices.filter(n=>n.userId===uid&&!n.read).forEach(n=>{updates['adminSupportNotifications/'+n.id+'/read']=true;updates['adminSupportNotifications/'+n.id+'/readAt']=firebase.database.ServerValue.TIMESTAMP;});if(Object.keys(updates).length)db.ref().update(updates).catch(()=>{});}
 c70OpenAdminChat=function(uid){if(!allowed()||!uid)return;watch();if(uid===activeUid&&messageRef&&node('c70ChatInput')){paintHeader();return;}remember();threadEpoch++;if(messageRef&&messageCallback)messageRef.off('value',messageCallback);activeUid=String(uid);state.c70AdminChatUid=activeUid;initialScroll=true;c70RenderInbox();const generation=threadEpoch,actor=owner,recipient=activeUid;
  node('c70Thread').innerHTML='<header id="cdSupportThreadHead" class="c70ThreadHead"></header><div id="c70Messages" class="c70Messages" role="log" aria-label="ข้อความในบทสนทนา"><div class="c70Empty">กำลังโหลดข้อความ…</div></div><form class="c70Composer" onsubmit="event.preventDefault();c70SendAdminChat()"><label class="cd-support-input-label" for="c70ChatInput">ตอบกลับ</label><textarea id="c70ChatInput" rows="2" maxlength="4000" placeholder="พิมพ์ข้อความตอบกลับ…" aria-label="พิมพ์ข้อความตอบกลับ" onkeydown="if(event.key===\'Enter\'&&!event.shiftKey&&!event.isComposing){event.preventDefault();c70SendAdminChat()}">'+E(drafts.get(recipient)||'')+'</textarea><button id="cdSupportSend" type="submit" aria-label="ส่งข้อความ" '+(sending.has(recipient)?'disabled':'')+'>➤</button><div id="cdSupportSendStatus" class="cd-support-feedback" role="status" aria-live="polite"></div></form>';paintHeader();markRead(recipient);
  messageRef=db.ref('supportChats/'+recipient+'/messages').limitToLast(200);const current=()=>allowed()&&owner===actor&&state.user.uid===actor&&generation===threadEpoch&&activeUid===recipient;
  messageCallback=s=>{if(!current())return;const box=node('c70Messages');if(!box)return;const nearBottom=box.scrollHeight-box.scrollTop-box.clientHeight<90,top=box.scrollTop;box.innerHTML=Object.values(s.val()||{}).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0)).map(c70SupportBubble).join('')||'<div class="c70Empty">เริ่มต้นสนทนาได้เลย</div>';box.scrollTop=initialScroll||nearBottom?box.scrollHeight:top;initialScroll=false;};messageRef.on('value',messageCallback,()=>{if(!current())return;node('c70Messages').innerHTML='<div class="error">โหลดข้อความไม่สำเร็จ <button type="button" data-support="retry-thread">ลองใหม่</button></div>';});
 };
 c70SendAdminChat=async function(){if(!allowed()||state.user.uid!==owner)return;const input=node('c70ChatInput'),raw=input?.value||'',text=raw.trim(),recipient=activeUid,actor=owner,authSession=session,operation={};if(!text||!recipient||sending.has(recipient))return;if(text.length>4000){node('cdSupportSendStatus').textContent='ข้อความยาวเกิน 4,000 ตัวอักษร';return;}sending.set(recipient,operation);drafts.set(recipient,raw);const button=node('cdSupportSend');if(button)button.disabled=true;node('cdSupportSendStatus').textContent='กำลังส่ง…';
  try{const mid=db.ref('supportChats/'+recipient+'/messages').push().key,nid=db.ref('notifications/'+recipient).push().key,now=firebase.database.ServerValue.TIMESTAMP;await db.ref().update({['supportChats/'+recipient+'/messages/'+mid]:{senderId:actor,senderRole:'admin',text,createdAt:now},['notifications/'+recipient+'/'+nid]:{type:'support_reply',senderId:actor,message:'มีข้อความใหม่จาก Admin Coach Di',read:false,createdAt:now}});
   if(session===authSession&&owner===actor&&state.user?.uid===actor){if(drafts.get(recipient)===raw)drafts.set(recipient,'');if(allowed()&&activeUid===recipient){const live=node('c70ChatInput');if(live?.value===raw)live.value='';node('cdSupportSendStatus').textContent='ส่งแล้ว';}}
  }catch(e){if(session===authSession&&allowed()&&owner===actor&&activeUid===recipient)node('cdSupportSendStatus').textContent='ส่งไม่สำเร็จ ข้อความยังอยู่ กรุณาลองส่งอีกครั้ง';}finally{if(sending.get(recipient)===operation)sending.delete(recipient);if(session===authSession&&allowed()&&owner===actor&&activeUid===recipient&&node('cdSupportSend'))node('cdSupportSend').disabled=sending.has(recipient);}
 };
 document.addEventListener('input',e=>{if(e.target.id==='c70ChatInput'&&allowed()&&activeUid)drafts.set(activeUid,e.target.value);});
 document.addEventListener('click',e=>{if(!allowed())return;const b=e.target.closest('button');if(!b)return;if(b.dataset.supportUser)return c70OpenAdminChat(b.dataset.supportUser);if(b.dataset.support==='reload'){remember();stop();watch();return;}if(b.dataset.support==='retry-thread'){const uid=activeUid;remember();activeUid='';return c70OpenAdminChat(uid);}});
 const previousRoute=s41ShowAdmin;s41ShowAdmin=async function(page){stop();return previousRoute.apply(this,arguments);};
 const previousLogout=logout;logout=function(){stop(true);return previousLogout.apply(this,arguments);};auth.onAuthStateChanged(u=>{if(!u||u.uid!==owner)stop(true);});
 if(allowed())s41ShowAdmin('support');
})(window);
