(function(root){
 'use strict';
 const DAY=86400000,valid=n=>Number.isFinite(Number(n))&&Number(n)>0?Number(n):0;
 const day=n=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(n));
 function dayStart(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))throw Error('กรุณาระบุวันที่ให้ถูกต้อง');const time=Date.parse(value+'T00:00:00+07:00');if(!Number.isFinite(time)||day(time)!==value)throw Error('วันที่ไม่ถูกต้อง');return time;}
 function trialRange(start,end,now=Date.now()){const trialStartedAt=dayStart(start);if(start>day(now))throw Error('วันเริ่ม Trial ต้องไม่เกินวันนี้');const last=end||day(trialStartedAt+59*DAY),trialEndsAt=dayStart(last)+DAY-1;if(trialEndsAt<trialStartedAt)throw Error('วันครบกำหนดต้องไม่อยู่ก่อนวันเริ่มต้น');return {trialStartedAt,trialEndsAt,days:Math.round((trialEndsAt+1-trialStartedAt)/DAY)};}
 function effectiveEnd(sub={}){return Math.max(valid(sub.trialEndsAt),valid(sub.currentPeriodEndsAt));}
 function renewalState(sub={},now=Date.now()){const end=effectiveEnd(sub);return {end,expired:!!end&&now>=end,locked:!!end&&now>end+3*DAY};}
 function trialPatch(uids,range,actor,stamp){if(!Array.isArray(uids)||!uids.length||!actor)throw Error('ไม่พบผู้ใช้');const patch={};for(const uid of new Set(uids)){if(typeof uid!=='string'||!uid||/[.#$\[\]/]/.test(uid))throw Error('รหัสผู้ใช้ไม่ถูกต้อง');const p='users/'+uid+'/subscription/';patch[p+'trialStartedAt']=range.trialStartedAt;patch[p+'trialEndsAt']=range.trialEndsAt;patch[p+'trialUpdatedBy']=actor;patch[p+'trialUpdatedAt']=stamp;}return patch;}
 const api={dayStart,trialRange,effectiveEnd,trialPatch,renewalState};if(typeof module==='object'&&module.exports){module.exports=api;return;}root.CoachDiTrial=api;
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let editor=null,ownRef=null,ownCallback=null,ownUid='',ownTimer=null,seen='',ownLoaded=false,refreshing=false;
 function cleanup(){if(ownRef&&ownCallback)ownRef.off('value',ownCallback);ownRef=null;ownCallback=null;ownUid='';ownLoaded=false;clearInterval(ownTimer);ownTimer=null;seen='';editor=null;document.getElementById('boTrialDialog')?.remove();document.getElementById('boRenewalDialog')?.remove();document.getElementById('boRenewalNotice')?.remove();}
 async function openTrial(button){if(state.role!=='admin'||!state.user?.uid)return;try{const uids=JSON.parse(button.dataset.trialUids||'[]');if(!uids.length)return;const entries=await Promise.all(uids.map(async uid=>({uid,user:(await db.ref('users/'+uid).once('value')).val()||{}})));if(entries.some(x=>x.user.role!=='coach'))throw Error('บัญชีนี้ไม่ใช่ผู้ให้บริการ');if(state.role!=='admin')return;editor={entries,actor:state.user.uid};const sub=entries[0].user.subscription||{},first=valid(sub.trialStartedAt)?day(sub.trialStartedAt):'',last=valid(sub.trialEndsAt)?day(sub.trialEndsAt):'';document.getElementById('boTrialDialog')?.remove();const d=document.createElement('dialog');d.id='boTrialDialog';d.className='cdtx-dialog';d.innerHTML=`<h2>แก้ไข Free Trial</h2><p><b>${E(button.dataset.trialName||entries[0].user.displayName||'ผู้ให้บริการ')}</b></p><label>วันเริ่ม Trial<input class="field" id="boTrialStart" type="date" max="${day(Date.now())}" value="${first}"></label><label>วันสุดท้ายที่ใช้ฟรี<input class="field" id="boTrialEnd" type="date" value="${last}"></label><button data-trial-action="sixty">กำหนดฟรี 60 วันจากวันเริ่ม</button><p id="boTrialLength" class="muted"></p><p>ใช้ได้ถึง 23:59 น. ของวันสุดท้าย ตามเวลาไทย</p>${entries.length>1?`<p>ปรับช่วง Trial ให้ตรงกันทั้ง ${entries.length} โปรไฟล์เดิมของบัญชีนี้</p>`:''}<p>รอบที่ชำระแล้วคงเดิม: ${valid(sub.currentPeriodEndsAt)?E(day(sub.currentPeriodEndsAt)):'ยังไม่มี'}</p><p id="boTrialError" role="alert"></p><div class="cdtx-actions"><button data-trial-action="save" class="cdtx-primary">บันทึก Trial</button><button data-trial-action="close">ยกเลิก</button></div>`;document.body.append(d);d.addEventListener('input',describeTrial);d.showModal();describeTrial();}catch(e){alert('เปิด Trial ไม่สำเร็จ: '+(e.message||e));}}
 function describeTrial(){try{const r=trialRange(document.getElementById('boTrialStart').value,document.getElementById('boTrialEnd').value);document.getElementById('boTrialLength').textContent='ทดลองใช้ฟรี '+r.days+' วัน';document.getElementById('boTrialError').textContent='';}catch(e){document.getElementById('boTrialLength').textContent='';document.getElementById('boTrialError').textContent=e.message;}}
 async function saveTrial(button){if(state.role!=='admin'||!editor||state.user?.uid!==editor.actor||button.disabled)return;button.disabled=true;try{const end=document.getElementById('boTrialEnd').value;if(!end)throw Error('กรุณาระบุวันสุดท้ายที่ใช้ฟรี');const range=trialRange(document.getElementById('boTrialStart').value,end),current=await Promise.all(editor.entries.map(async old=>({old,user:(await db.ref('users/'+old.uid).once('value')).val()||{}})));for(const {old,user} of current){if(user.role!=='coach')throw Error('บัญชีมีการเปลี่ยนแปลง กรุณาเปิดใหม่');const before=old.user.subscription||{},after=user.subscription||{};if(valid(before.trialStartedAt)!==valid(after.trialStartedAt)||valid(before.trialEndsAt)!==valid(after.trialEndsAt))throw Error('Trial ถูกแก้ไขแล้ว กรุณาปิดและเปิดใหม่');}await db.ref().update(trialPatch(editor.entries.map(e=>e.uid),range,state.user.uid,firebase.database.ServerValue.TIMESTAMP));document.getElementById('boTrialDialog').close();document.getElementById('boTrialDialog').remove();editor=null;if(typeof s42Toast==='function')s42Toast('บันทึกช่วง Trial แล้ว');else alert('บันทึกช่วง Trial แล้ว');}catch(e){document.getElementById('boTrialError').textContent=e.message||String(e);button.disabled=false;}}
 // All clients and access rules use the longest valid trial or paid entitlement.
 c62SubEnd=effectiveEnd;c46PeriodEnd=effectiveEnd;
 cdSubStatus=function(sub){const now=Date.now();if(!effectiveEnd(sub))return {key:'not_started',label:'ยังไม่เริ่ม Trial',cls:'pending'};if(valid(sub.currentPeriodEndsAt)>now)return {key:'active',label:'ใช้งานรอบที่ชำระแล้ว',cls:'confirmed'};if(valid(sub.trialEndsAt)>now)return {key:'trial',label:'ทดลองใช้ฟรี',cls:'coach_approved'};return {key:'expired',label:'ครบกำหนดแล้ว',cls:'cancelled'};};
 const oldSubscriptionCard=cdCoachSubscriptionCard;cdCoachSubscriptionCard=function(){return oldSubscriptionCard()+`<div class="notice">Trial: ${valid(state.subscription?.trialStartedAt)?day(state.subscription.trialStartedAt):'ยังไม่ระบุวันเริ่ม'} ถึง ${valid(state.subscription?.trialEndsAt)?day(state.subscription.trialEndsAt):'ยังไม่ระบุวันสิ้นสุด'} · สิทธิ์ใช้งานถึง ${effectiveEnd(state.subscription)?day(effectiveEnd(state.subscription)):'ยังไม่ระบุ'}</div>`;};
 function checkoutBusy(){return !!document.getElementById('cd106Modal')||!!new URLSearchParams(location.search).get('subscriptionPayment')||!!sessionStorage.getItem('coachDiSubscriptionPayment');}
 function offerRenewal(){if(state.role!=='coach'||!ownLoaded||state.user?.uid!==ownUid)return;const status=renewalState(state.subscription),oldLocked=!!state.subscriptionLocked;state.subscriptionLocked=status.locked;if(oldLocked!==status.locked&&!checkoutBusy()&&!refreshing){refreshing=true;try{showCoach(status.locked?'settings':'overview');}finally{refreshing=false;}}if(!status.expired){document.getElementById('boRenewalDialog')?.remove();document.getElementById('boRenewalNotice')?.remove();return;}let banner=document.getElementById('boRenewalNotice');if(!banner){banner=document.createElement('section');banner.id='boRenewalNotice';banner.className='cdtx-warning';banner.innerHTML='<b>ครบกำหนดใช้งานแล้ว ต้องการต่ออายุไหม?</b> <button data-renew="yes">ต่ออายุ / ไปชำระเงิน</button>';coachContent.prepend(banner);}const key=ownUid+':'+status.end;if(seen===key||checkoutBusy()||document.querySelector('dialog[open]')||document.getElementById('c62Legal'))return;seen=key;const d=document.createElement('dialog');d.id='boRenewalDialog';d.className='cdtx-dialog';d.innerHTML=`<h2>ต้องการต่ออายุใช้งานไหม?</h2><p>สิทธิ์ใช้งานสิ้นสุดวันที่ ${day(status.end)} แล้ว</p><p>ต่ออายุ ฿${Number(root.COACH_DI_PUBLIC_CONFIG?.subscriptionPriceSatang||25900)/100} / ${Number(root.COACH_DI_PUBLIC_CONFIG?.subscriptionPeriodDays||30)} วัน</p><div class="cdtx-actions"><button data-renew="yes" class="cdtx-primary">ต้องการต่ออายุ · ไปชำระเงิน</button><button data-renew="later">ไว้ภายหลัง</button></div>`;document.body.append(d);d.showModal();}
 function bindOwn(){if(state.role!=='coach'||!state.user?.uid)return;if(ownUid===state.user.uid)return;if(ownRef&&ownCallback)ownRef.off('value',ownCallback);clearInterval(ownTimer);ownUid=state.user.uid;ownLoaded=false;seen='';const uid=ownUid;ownRef=db.ref('users/'+uid+'/subscription');ownCallback=s=>{if(uid!==ownUid||state.role!=='coach')return;state.subscription=s.val()||{};ownLoaded=true;offerRenewal();};ownRef.on('value',ownCallback,()=>{ownLoaded=false;document.getElementById('boRenewalDialog')?.remove();document.getElementById('boRenewalNotice')?.remove();});ownTimer=setInterval(offerRenewal,30000);}
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.trialUids)return openTrial(b);if(b.dataset.trialAction==='close')return document.getElementById('boTrialDialog')?.close();if(b.dataset.trialAction==='sixty'){try{const range=trialRange(document.getElementById('boTrialStart').value,'');document.getElementById('boTrialEnd').value=day(range.trialEndsAt);describeTrial();}catch(error){document.getElementById('boTrialError').textContent=error.message;}return;}if(b.dataset.trialAction==='save')return saveTrial(b);if(b.dataset.renew){document.getElementById('boRenewalDialog')?.remove();if(b.dataset.renew==='yes'&&state.role==='coach'){showCoach('settings');setTimeout(()=>{if(state.role==='coach')cdLoadSubscriptionPayInfo();},40);}}});
 const oldShowCoach=showCoach;showCoach=function(){const result=oldShowCoach.apply(this,arguments);if(state.role==='coach'){bindOwn();setTimeout(offerRenewal,0);}return result;};
 const oldLogout=logout;logout=function(){cleanup();return oldLogout.apply(this,arguments);};auth.onAuthStateChanged(u=>{if(!u||u.uid!==ownUid){cleanup();if(u)setTimeout(bindOwn,1800);}});document.addEventListener('visibilitychange',()=>{if(!document.hidden){bindOwn();offerRenewal();}});bindOwn();
})(typeof window==='undefined'?globalThis:window);
