(function(root){
 'use strict';
 const C=root.CoachDiBackofficeCore,M=root.CoachDiCoachSummary;
 const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=n=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(Number(n||0)/100);
 const stamp=n=>Number.isFinite(Number(n))&&Number(n)>0?new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'medium',timeStyle:'short'}).format(new Date(Number(n))):'ไม่ระบุวัน–เวลา';
 const clock=v=>{if(v==null||v==='')return '—';if(/^\d{1,2}:\d{2}$/.test(String(v)))return String(v).padStart(5,'0');const n=Math.round(Number(v)*60);return Number.isFinite(n)&&n>=0&&n<=1440?String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0'):'—';};
 const labels={paid:'รับเงินแล้ว',review:'รอตรวจสลิป',confirm:'รอโค้ชยืนยัน',unpaid:'รอชำระเงิน',refund:'รอคืนเงิน',refunded:'คืนเงินแล้ว',cancelled:'ยกเลิก / ไม่อนุมัติ',reconcile:'ตรวจสอบข้อมูลรับเงิน',test:'รายการทดสอบ',unknown:'ตรวจสอบประเภทรายการ'};
 const bookingLabels={approved:'อนุมัติแล้ว',confirmed:'ยืนยันแล้ว',completed:'เรียนแล้ว',pending:'รออนุมัติ',pending_coach_approval:'รอโค้ชยืนยัน',pending_approval:'รออนุมัติ',payment_submitted:'ส่งสลิปแล้ว',payment_uploaded:'ส่งสลิปแล้ว',pending_verification:'รอตรวจสลิป',rejected:'ไม่อนุมัติ',declined:'ไม่อนุมัติ',cancelled:'ยกเลิก',active:'เปิดรับผู้เล่น',open:'เปิดรับผู้เล่น',closed:'ปิดรับผู้เล่น',full:'เต็มแล้ว',payment_verified:'ตรวจรับเงินแล้ว',refund_required:'รอคืนเงิน',awaiting_payment:'รอชำระเงิน',unpaid:'ยังไม่ชำระ',refunded:'คืนเงินแล้ว'};
 const types={booking:'จองโค้ช',group:'Open Play',refund:'คืนเงิน',unknown:'ตรวจสอบประเภทรายการ'};
 const newView=()=>({period:'month',...C.period('month'),type:'',status:'',q:'',page:1,rosterScope:'upcoming',rosterDate:C.today()});
 let view=newView(),data={},refs=[],owner='',epoch=0,timer=null,queued=null,loaded=new Set(),errors=new Set(),online=true,lastDay=C.today();
 const isOwn=()=>state.role==='coach'&&!!state.user?.uid&&!state.subscriptionLocked;
 const mounted=()=>!!document.getElementById('csRoot');
 function stop(reset=false){epoch++;refs.forEach(([r,cb])=>r.off('value',cb));refs=[];owner='';data={};loaded.clear();errors.clear();online=true;clearInterval(timer);clearTimeout(queued);timer=null;queued=null;for(const id of ['csOverviewMetrics','csOverviewTransactions','csRosters','csBookingOverview','csIncomeBreakdown','csAllTime','csFinanceMetrics','csTransactions'])put(id,'');put('csHealth','');if(reset)view=newView();}
 function queue(){clearTimeout(queued);queued=setTimeout(refresh,60);}
 function start(){if(!isOwn()||!mounted()){stop();return;}if(owner===state.user.uid)return;stop();owner=state.user.uid;const uid=owner,generation=epoch;
  const sources=[['bookings',db.ref('bookings').orderByChild('coachId').equalTo(uid)],['paymentTransactions',db.ref('paymentTransactions').orderByChild('coachId').equalTo(uid)],['refunds',db.ref('refunds').orderByChild('coachId').equalTo(uid)],['coachGroupClasses',db.ref('coachGroupClasses/'+uid)],['coachGroupClassRequests',db.ref('coachGroupClassRequests/'+uid)],['online',db.ref('.info/connected')]];
  for(const [key,ref] of sources){const current=()=>generation===epoch&&owner===uid&&state.user?.uid===uid&&isOwn();const cb=s=>{if(!current())return;const value=s.val();if(key==='online')online=value!==false;else data[key]=key.startsWith('coachGroup')?{[uid]:value||{}}:value||{};loaded.add(key);errors.delete(key);queue();};refs.push([ref,cb]);ref.on('value',cb,()=>{if(!current())return;delete data[key];loaded.add(key);errors.add(key);queue();});}
  timer=setInterval(()=>{if(!isOwn()||state.user.uid!==owner||!mounted()){stop();return;}const day=C.today();if(day!==lastDay){if(view.rosterDate===lastDay)view.rosterDate=day;lastDay=day;Object.assign(view,C.period(view.period,Date.now(),view));syncControls();}refresh();},30000);
 }
 function health(){if(!online)return '<div class="cdtx-warning">ขาดการเชื่อมต่อ · ข้อมูลและยอดเงินอาจยังไม่เป็นปัจจุบัน <button data-cs="reload">ลองใหม่</button></div>';if(errors.size)return '<div class="cdtx-warning">ข้อมูลบางส่วนโหลดไม่สำเร็จ ยอดเงินและรายชื่ออาจยังไม่ครบ <button data-cs="reload">ลองใหม่</button></div>';if(loaded.size<6)return '<div class="cdtx-info">กำลังโหลดรายการจอง ผู้เข้าร่วม และการรับเงิน… ยอดอาจยังไม่ครบ</div>';return '<div class="cs-live">● อัปเดตข้อมูลแล้ว · '+E(stamp(Date.now()))+' · เวลาไทย</div>';}
 const metric=(name,value,note)=>'<article><span>'+name+'</span><strong>'+value+'</strong><small>'+note+'</small></article>';
 function todayTimeline(books,day){const rows=books.filter(b=>b.date===day&&!/cancel|declin|reject/.test(b.status||'')).sort((a,b)=>Number(a.start)-Number(b.start));return '<section class="c43card c45Timeline"><div class="c43ctop"><h3>จองโค้ชวันนี้</h3><span>'+E(day)+'</span></div>'+rows.map(b=>'<button data-cs="booking-detail" data-booking-id="'+E(b.id)+'"><time>'+E(clock(b.start))+'</time><span><b>'+E(clock(b.start)+'–'+clock(b.end))+' '+E(b.athlete||b.athleteName||'ผู้จอง')+'</b><small>'+E(b.venue||b.venueName||'')+'</small></span></button>').join('')+(rows.length?'':'<p class="cdtx-empty">ไม่มีการจองโค้ชวันนี้</p>')+'<button class="c43btn" data-cs="schedule">ดูตารางทั้งหมด</button></section>';}
 function header(title){return '<header class="cdtx-head"><div><span class="cdtx-eyebrow">COACH DI · '+E(state.coachProfile?.providerKind==='knocker'?'KNOCKER':'COACH')+'</span><h1>'+title+'</h1><p>จองโค้ชและ Open Play · ข้อมูล ณ <span data-cs-today>'+C.today()+'</span></p></div><div class="cdtx-actions"><button data-cs="reload">รีเฟรชข้อมูล</button><button data-cs="openplay">จัดการ Open Play</button></div></header>';}
 function rosterShell(){return '<section class="cdtx-panel cs-roster"><header class="cdtx-section"><div><h2>Open Play · รายชื่อผู้จอง</h2><p>ดูวัน–เวลาคลาส วันที่จอง และสถานะของผู้เข้าร่วมแต่ละคน</p></div></header><div class="cs-controls"><label>แสดงคลาส<select data-cs-filter="rosterScope"><option value="upcoming" '+(view.rosterScope==='upcoming'?'selected':'')+'>วันนี้และที่กำลังจะมาถึง</option><option value="date" '+(view.rosterScope==='date'?'selected':'')+'>เลือกวัน</option><option value="all" '+(view.rosterScope==='all'?'selected':'')+'>ทั้งหมด รวมย้อนหลัง</option></select></label><label>วันที่ Open Play<input type="date" data-cs-filter="rosterDate" value="'+E(view.rosterDate)+'"></label><button data-cs="roster-today">วันนี้</button></div><div id="csRosters"></div></section>';}
 function overview(){return '<main id="csRoot" class="cdtx cs-page" data-cs-page="overview">'+header('ภาพรวมของฉัน')+'<div id="csHealth" role="status" aria-live="polite"></div><section id="csOverviewMetrics" class="cdtx-metrics"></section><section class="cdtx-panel"><div id="csOverviewTransactions"></div></section>'+rosterShell()+'<div id="csBookingOverview"></div><section class="cdtx-panel"><div id="csIncomeBreakdown"></div></section></main>';}
 function finance(){Object.assign(view,C.period(view.period,Date.now(),view));return '<main id="csRoot" class="cdtx cs-page" data-cs-page="finance">'+header('รายได้และธุรกรรมทั้งหมด')+'<div id="csHealth" role="status" aria-live="polite"></div><div class="cs-controls"><label>ช่วงรายได้<select data-cs-filter="period">'+[['today','วันนี้'],['week','7 วันล่าสุด'],['month','เดือนนี้ถึงวันนี้'],['lastmonth','เดือนที่แล้ว'],['year','ปีนี้ถึงวันนี้'],['all','ทั้งหมดถึงวันนี้'],['custom','กำหนดช่วงเอง']].map(([v,n])=>'<option value="'+v+'" '+(view.period===v?'selected':'')+'>'+n+'</option>').join('')+'</select></label><label>ตั้งแต่<input type="date" data-cs-filter="from" value="'+E(view.from)+'"></label><label>ถึง<input type="date" data-cs-filter="to" max="'+C.today()+'" value="'+E(view.to)+'"></label><button data-cs="export">Export Excel รายได้</button></div><div id="csAllTime"></div><section id="csFinanceMetrics" class="cdtx-metrics"></section><section class="cdtx-panel"><div id="csIncomeBreakdown"></div></section><section class="cdtx-panel"><h2>รายการธุรกรรม</h2><p>รายการรับเงินใช้วันรับเงิน รายการรอดำเนินการใช้วันที่ทำรายการ · รวมการจองและ Open Play</p><div class="cs-controls"><label>ค้นหาชื่อ / คลาส / อ้างอิง<input data-cs-filter="q" value="'+E(view.q)+'" placeholder="ชื่อผู้จองหรือชื่อ Open Play"></label><label>ประเภท<select data-cs-filter="type"><option value="">ทั้งหมด</option>'+Object.entries(types).map(([k,v])=>'<option value="'+k+'" '+(view.type===k?'selected':'')+'>'+v+'</option>').join('')+'</select></label><label>สถานะ<select data-cs-filter="status"><option value="">ทุกสถานะ</option><option value="attention" '+(view.status==='attention'?'selected':'')+'>ต้องดำเนินการ</option>'+Object.entries(labels).filter(([k])=>k!=='unknown').map(([k,v])=>'<option value="'+k+'" '+(view.status===k?'selected':'')+'>'+v+'</option>').join('')+'</select></label><button data-cs="clear">แสดงทั้งหมด</button></div><div id="csTransactions"></div></section><p class="cdtx-note">นับรายได้จากเงินที่ยืนยันรับแล้วเท่านั้น รวม Open Play ที่ตรวจสลิปและอนุมัติแล้ว ยอดรอชำระและรายการทดสอบยังไม่เป็นรายได้ ยอดคืนเงินแสดงแยก ส่วนของโค้ชเป็นยอดหลังค่าธรรมเนียม ก่อนปรับคืนเงิน</p></main>';}
 const attention=r=>root.CoachDiTransactions.attention(r);
 function filtered(rows){const q=view.q.trim().toLowerCase();return rows.filter(r=>(r.reason==='invalid_or_future_payment_time'||((!view.from||!r.day||r.day>=view.from)&&(!view.to||!r.day||r.day<=view.to)))&&(!view.type||r.type===view.type)&&(!view.status||(view.status==='attention'?attention(r):view.status==='refund'?r.status==='refund'||r.refundRequired:r.status===view.status))&&(!q||[r.athleteName,r.title,r.reference,r.venue].join(' ').toLowerCase().includes(q)));}
 function badge(status){return '<span class="cdtx-badge '+E(status)+'">'+E(labels[status]||status||'ไม่ระบุสถานะ')+'</span>';}
 function incomeBreakdown(rows){const paid=rows.filter(r=>r.status==='paid'&&['booking','group'].includes(r.type)),groups=['booking','group'].map(type=>({name:types[type],rows:paid.filter(r=>r.type===type)})),max=Math.max(1,...groups.map(g=>M.summarize(g.rows).coachNet));return '<h2>รายได้แยกประเภท</h2><p>ส่วนของโค้ชหลังค่าธรรมเนียม ก่อนปรับคืนเงิน · '+E(view.from||'เริ่มต้น')+' ถึง '+E(view.to)+'</p>'+groups.map(g=>{const s=M.summarize(g.rows);return '<div class="cs-income-bar"><span>'+g.name+' <small>'+g.rows.length+' รายการ</small></span><div><i style="width:'+Math.round(s.coachNet/max*100)+'%"></i></div><b>'+money(s.coachNet)+'</b></div>';}).join('');}
 function rosterHTML(sessions){const today=C.today(),matching=sessions.filter(s=>view.rosterScope==='all'||view.rosterScope==='date'?view.rosterScope==='all'||s.date===view.rosterDate:!s.date||s.date>=today);return matching.map(s=>'<article class="cs-session '+(s.date===today?'cs-session-today':'')+'"><header><div><span class="cs-session-day">'+(s.date===today?'วันนี้ · ':'')+E(s.date||'ไม่ระบุวันคลาส')+' · '+E(clock(s.start)+'–'+clock(s.end))+'</span><h3>'+E(s.title)+'</h3><p>'+E(s.venue||'ไม่ระบุสนาม')+' · '+E(bookingLabels[s.status]||s.status||'ไม่ระบุสถานะคลาส')+'</p></div><div class="cs-session-total"><b>'+money(s.received)+'</b><span>รับแล้ว · '+s.participants.length+' รายชื่อ</span><small>อนุมัติแล้ว '+s.participants.filter(p=>['approved','confirmed','completed'].includes(p.requestStatus)).length+' คน</small></div></header><div class="cdtx-scroll"><table><thead><tr><th>ชื่อผู้จอง</th><th>จองเข้ามาเมื่อ</th><th>สถานะการเข้าร่วม</th><th>การชำระเงิน</th><th>รับแล้ว</th></tr></thead><tbody>'+s.participants.map(p=>'<tr><td><b>'+E(p.name)+'</b></td><td>'+E(stamp(p.bookedAt))+'</td><td>'+E(bookingLabels[p.requestStatus]||p.requestStatus||'ไม่ระบุ')+'</td><td>'+badge(p.transactionStatus||p.status||({payment_verified:'paid',payment_submitted:'review',refund_required:'refund',refunded:'refunded'}[p.paymentStatus]||'unpaid'))+(p.refundRequired?'<small class="cdtx-badge refund">รอคืนเงิน</small>':'')+'</td><td class="cdtx-money">'+money(p.received)+'</td></tr>').join('')+(s.participants.length?'':'<tr><td colspan="5" class="cdtx-empty">ยังไม่มีผู้จองคลาสนี้</td></tr>')+'</tbody></table></div></article>').join('')||'<p class="cdtx-empty">ไม่มี Open Play ในช่วงที่เลือก · เลือกวันหรือดูทั้งหมดเพื่อดูย้อนหลัง</p>';}
 function transactionHTML(rows){const max=Math.max(1,Math.ceil(rows.length/25));view.page=Math.min(view.page,max);return (view.from&&view.to&&view.from>view.to?'<p class="cdtx-warning">วันเริ่มต้องไม่อยู่หลังวันสิ้นสุด</p>':'')+'<div class="cdtx-scroll"><table><thead><tr><th>ธุรกรรม / วันทำรายการ</th><th>ผู้จอง</th><th>คลาส / วัน–เวลา</th><th>รับแล้ว</th><th>ส่วนโค้ช</th><th>คืนแล้ว</th><th>สถานะ</th></tr></thead><tbody>'+rows.slice((view.page-1)*25,view.page*25).map(r=>'<tr><td><b>'+E(types[r.type]||r.type)+'</b><small>'+E(stamp(r.timestamp))+'</small><small>'+E(r.reference)+'</small></td><td>'+E(r.athleteName)+'</td><td><b>'+E(r.title||types[r.type])+'</b><small>'+E(r.date||'ไม่ระบุวันคลาส')+' · '+E(clock(r.start)+'–'+clock(r.end))+'</small><small>'+E(r.venue||'')+'</small></td><td class="cdtx-money">'+money(r.received)+'</td><td class="cdtx-money">'+money(r.net)+'</td><td class="cdtx-money">'+money(r.refund)+'</td><td>'+badge(r.status)+(r.refundRequired?'<small class="cdtx-badge refund">รอคืนเงิน</small>':'')+'<small>'+E(bookingLabels[r.bookingStatus]||r.bookingStatus||'')+'</small></td></tr>').join('')+(rows.length?'':'<tr><td colspan="7" class="cdtx-empty">ไม่พบธุรกรรมตามตัวกรอง</td></tr>')+'</tbody></table></div><footer class="cdtx-pagination"><span>'+rows.length+' รายการ · หน้า '+view.page+' / '+max+'</span><div><button data-cs="prev" '+(view.page===1?'disabled':'')+'>ก่อนหน้า</button><button data-cs="next" '+(view.page===max?'disabled':'')+'>ถัดไป</button></div></footer>';}
 function put(id,html){const node=document.getElementById(id);if(node)node.innerHTML=html;}
 function refresh(){if(!isOwn()||!mounted()||owner!==state.user.uid)return;const now=Date.now(),today=C.today(now),rows=M.project(data,owner,now),sessions=M.roster(data,owner,now),all=M.summarize(rows),selected=filtered(rows),s=M.summarize(selected);put('csHealth',health());document.querySelectorAll('[data-cs-today]').forEach(n=>n.textContent=today);
  if(document.getElementById('csOverviewMetrics')){const monthRows=rows.filter(r=>r.day>=today.slice(0,7)+'-01'&&r.day<=today),month=M.summarize(monthRows),daily=M.summarize(rows.filter(r=>r.day===today));put('csOverviewMetrics',metric('รายได้โค้ชวันนี้',money(daily.coachNet),'รวมการจองและ Open Play')+metric('รายได้โค้ชเดือนนี้',money(month.coachNet),'เดือนนี้ถึงวันนี้ · ก่อนปรับคืนเงิน')+metric('Open Play เดือนนี้',money(monthRows.filter(r=>r.type==='group').reduce((n,r)=>n+r.net,0)),'รวมอยู่ในรายได้โค้ชแล้ว')+metric('รายได้โค้ชสะสมทั้งหมด',money(all.coachNet),'หลังค่าธรรมเนียม ก่อนปรับคืนเงิน'));
   put('csOverviewTransactions','<div class="cs-summary-line"><div><h2>ธุรกรรมทั้งหมด '+all.count+' รายการ</h2><p>รับแล้ว '+money(all.serviceReceived)+' · Open Play '+money(all.openPlayReceived)+' · คืนเงินแล้ว '+money(all.refunds)+'</p><p>ต้องดำเนินการ '+all.attention+' รายการ · Open Play รอตรวจสลิป '+all.openPlayReviewCount+' รายการ</p></div><button data-cs="finance">ดูรายได้และธุรกรรมทั้งหมด</button></div>');
   put('csRosters',rosterHTML(sessions));const books=Object.entries(data.bookings||{}).filter(([,b])=>b?.coachId===owner).map(([id,b])=>({...b,id})),pending=books.filter(c43new).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));put('csBookingOverview',(typeof c58DayCalendar==='function'?'<section class="c43card">'+c58DayCalendar(today)+'</section>':'')+'<div class="c45OverviewGrid"><section class="c43card"><div class="c43ctop"><div><h2>คำขอจองโค้ชใหม่</h2><p>'+pending.length+' รายการ</p></div><button class="c43btn" data-cs="bookings">ดูการจองโค้ชทั้งหมด</button></div>'+pending.slice(0,5).map(c45DashboardTicket).join('')+(pending.length?'':'<p class="cdtx-empty">ไม่มีคำขอจองโค้ชใหม่</p>')+'</section>'+todayTimeline(books,today)+'</div>');
   // Overview always describes the current month, independent of finance filters.
   const saved={from:view.from,to:view.to};Object.assign(view,C.period('month',now));put('csIncomeBreakdown',incomeBreakdown(monthRows));Object.assign(view,saved);
  }else{put('csAllTime','<p class="cs-alltime">สะสมทั้งหมด: รับเงิน '+money(all.serviceReceived)+' · ส่วนโค้ช '+money(all.coachNet)+' · '+all.count+' ธุรกรรม</p>');put('csFinanceMetrics',metric('รับเงินในช่วงที่เลือก',money(s.serviceReceived),'รวมจองโค้ชและ Open Play')+metric('ส่วนของโค้ช',money(s.coachNet),'หลังค่าธรรมเนียม ก่อนปรับคืนเงิน')+metric('Open Play รับแล้ว',money(s.openPlayReceived),'รวมอยู่ในยอดรับเงินแล้ว')+metric('รอชำระ / ตรวจสลิป',money(s.waiting),'ยังไม่นับเป็นรายได้')+metric('คืนเงินแล้ว',money(s.refunds),'แสดงแยกจากรายได้')+metric('ธุรกรรมในช่วงที่เลือก',s.count+' รายการ','ต้องดำเนินการ '+s.attention+' รายการ'));put('csTransactions',transactionHTML(selected));put('csIncomeBreakdown',incomeBreakdown(selected));}
 }
 function syncControls(){document.querySelectorAll('[data-cs-filter]').forEach(n=>{if(view[n.dataset.csFilter]!=null)n.value=view[n.dataset.csFilter];if(n.dataset.csFilter==='to')n.max=C.today();});}
 function exportFinance(){if(!isOwn()||owner!==state.user.uid)return;if(errors.size||loaded.size<6||!online)return alert('ข้อมูลยังไม่ครบหรือขาดการเชื่อมต่อ กรุณารีเฟรชก่อน Export');if(view.from&&view.to&&view.from>view.to)return alert('วันเริ่มต้องไม่อยู่หลังวันสิ้นสุด');if(!root.CoachDiExcel)return alert('โหลดตัวส่งออกไม่สำเร็จ กรุณารีเฟรช');const rows=filtered(M.project(data,owner,Date.now())),s=M.summarize(rows);root.CoachDiExcel.download([{name:'สรุปรายได้',rows:[['ข้อมูล ณ',C.today()],['ตั้งแต่',view.from||'เริ่มต้น'],['ถึง',view.to],['รับเงิน (บาท)',s.serviceReceived/100],['ส่วนโค้ชก่อนคืนเงิน (บาท)',s.coachNet/100],['Open Play รับแล้ว (บาท)',s.openPlayReceived/100],['คืนเงินแล้ว (บาท)',s.refunds/100],['รอชำระและตรวจสลิป (บาท)',s.waiting/100],['จำนวนธุรกรรม',s.count],['ประเภท',types[view.type]||'ทั้งหมด'],['สถานะ',labels[view.status]||(view.status==='attention'?'ต้องดำเนินการ':'ทั้งหมด')],['คำค้น',view.q],['หมายเหตุ','นับเฉพาะรับเงินยืนยันแล้ว รายการรอดำเนินการและทดสอบไม่เป็นรายได้ คืนเงินแสดงแยก']]},{name:'ธุรกรรม',rows:[['อ้างอิง','ประเภท','ผู้จอง','คลาส','วัน–เวลาธุรกรรม','วันที่คลาส','เวลาเริ่ม','เวลาสิ้นสุด','รับแล้ว (บาท)','ส่วนโค้ช (บาท)','คืนแล้ว (บาท)','สถานะ'],...rows.map(r=>[r.reference,types[r.type],r.athleteName,r.title||'',stamp(r.timestamp),r.date||'',clock(r.start),clock(r.end),r.received/100,r.net/100,(r.refund||0)/100,labels[r.status]||r.status])]}],'coach-di-my-income-'+C.today()+'.xlsx');}
 document.addEventListener('input',e=>{const key=e.target.dataset?.csFilter;if(!key||!isOwn()||!mounted())return;view[key]=e.target.value;view.page=1;if(key==='period')Object.assign(view,C.period(view.period,Date.now(),view));if(key==='from'||key==='to'){view.period='custom';Object.assign(view,C.period('custom',Date.now(),view));}if(key==='rosterDate')view.rosterScope='date';syncControls();queue();});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-cs]');if(!b||!isOwn()||!mounted())return;const action=b.dataset.cs;if(action==='reload'){stop();start();return refresh();}if(action==='export')return exportFinance();if(action==='finance'||action==='bookings'||action==='schedule')return showCoach(action);if(action==='booking-detail')return s42Detail(b.dataset.bookingId);if(action==='openplay')return showCoach('groupclasses');if(action==='roster-today'){view.rosterScope='date';view.rosterDate=C.today();syncControls();}if(action==='clear'){Object.assign(view,{q:'',type:'',status:'',period:'all',page:1},C.period('all'));syncControls();}if(action==='prev')view.page=Math.max(1,view.page-1);if(action==='next')view.page++;refresh();});
 c43overview=overview;c43finance=finance;c43reports=finance;c49RenderFinance=refresh;c49ExportFinance=exportFinance;
 const previousOpenPlay=typeof c79InjectOpenPlayDashboard==='function'?c79InjectOpenPlayDashboard:null;if(previousOpenPlay)c79InjectOpenPlayDashboard=function(){if(!mounted())return previousOpenPlay();};
 const previousShow=showCoach;showCoach=function(){const result=previousShow.apply(this,arguments);if(isOwn()&&state.c43p)state.s42Page=state.c43p;if(isOwn()&&mounted()){start();refresh();}else stop();return result;};
 const previousLogout=logout;logout=function(){stop(true);return previousLogout.apply(this,arguments);};auth.onAuthStateChanged(u=>{if(!u||u.uid!==owner)stop(true);});
 document.addEventListener('visibilitychange',()=>{if(!document.hidden&&mounted()){start();refresh();}});
 if(isOwn()&&['overview','finance','reports'].includes(state.c43p||'overview'))showCoach(state.c43p||'overview');
})(window);
