state.c59Tab=state.c59Tab||'discover';state.c59Topics=[];state.c59Tickets=[];state.c59Requests={};state.c59Participants={};
function c59Name(){const p=state.userProfile||{};return p.displayName||p.nameEn||p.nameTh||state.user?.displayName||'Athlete'}
function c59VenueOptions(){return (state.venues||[]).filter(v=>v.id!=='other').sort(c58VenueCompare).map(v=>`<option value="${esc(v.name||v.id)}">${esc(v.name||v.id)}</option>`).join('')}
function c59Page(){return `<div id="c59Root" class="c59"><section class="c59Top"><h1>หาเพื่อนตี</h1><p class="muted">สร้างกลุ่ม นัดสนามและเวลา แล้วอนุมัติเฉพาะคนที่ต้องการให้เข้าร่วม</p><div class="c59Tabs">${[['discover','ค้นหากลุ่ม'],['mine','หัวข้อของฉัน'],['tickets','คำขอ / Tickets'],['calendar','Calendar']].map(x=>`<button class="${state.c59Tab===x[0]?'active':''}" onclick="c59SetTab('${x[0]}')">${x[1]}</button>`).join('')}</div><button class="c59Btn primary" onclick="c59OpenCreate()">＋ สร้างหัวข้อหาเพื่อนตี</button></section><div id="c59Body"><div class="c59Empty">กำลังโหลดกลุ่มจาก Firebase...</div></div></div>`}
function c59SetTab(t){state.c59Tab=t;c59Render()}
async function c59Load(){try{const uid=state.user.uid,[ts,tk]=await Promise.all([db.ref('groupPlayTopics').once('value'),db.ref(`groupPlayTickets/${uid}`).once('value')]);state.c59Topics=Object.entries(ts.val()||{}).map(([id,x])=>({id,...x}));state.c59Tickets=Object.entries(tk.val()||{}).map(([id,x])=>({id,...x}));state.c59Requests={};state.c59Participants={};await Promise.all(state.c59Topics.map(async t=>{const own=t.ownerId===uid;const rq=await db.ref(`groupPlayRequests/${t.id}/${uid}`).once('value');if(rq.exists())state.c59Requests[t.id]={[uid]:rq.val()};if(own){const all=await db.ref(`groupPlayRequests/${t.id}`).once('value');state.c59Requests[t.id]=all.val()||{}}if(own||rq.val()?.status==='approved'){const ps=await db.ref(`groupPlayParticipants/${t.id}`).once('value');state.c59Participants[t.id]=ps.val()||{}}}));c59Render()}catch(e){c59Body.innerHTML=`<div class="error">โหลดข้อมูลหาเพื่อนตีไม่สำเร็จ: ${esc(e.message||e)} <button class="c59Btn" onclick="c59Load()">ลองใหม่</button></div>`}}
function c59Card(t){const uid=state.user.uid,own=t.ownerId===uid,r=(state.c59Requests[t.id]||{})[uid],count=Number(t.approvedCount||1),cap=Number(t.capacityTotal||2),closed=!!t.closedEarly,full=t.status==='full'||count>=cap,label=closed?'ปิดรับ':full?'เต็ม':'เปิดรับ';return `<article class="c59Card"><header><div><h3>${esc(t.sport||'Tennis')} • ${esc(t.venueName)}</h3><small class="muted">สร้างโดย ${esc(t.ownerName||'Athlete')}</small></div><span class="c59Badge ${full?'full':''}">${label}</span></header><div class="c59Meta"><div><small>วันและเวลา</small><b>${esc(t.date)} • ${esc(t.start)}–${esc(t.end)}</b></div><div><small>ผู้เข้าร่วมที่อนุมัติแล้ว</small><b>${count} / ${cap} คน</b></div></div><div class="c59Progress"><i style="width:${Math.min(100,count/cap*100)}%"></i></div><div class="c59Actions">${own?`<button class="c59Btn" onclick="c59OpenOwner('${t.id}')">ดูคำขอ (${Object.values(state.c59Requests[t.id]||{}).filter(x=>x.status==='pending').length})</button>${!full?`<button class="c59Btn c59CloseRecruit" onclick="c59MarkFull('${t.id}')">ปิดรับสมาชิก</button>`:''}`:r?`<span class="c59Badge ${r.status==='rejected'?'full':''}">${r.status==='pending'?'รอเจ้าของอนุมัติ':r.status==='approved'?'เข้าร่วมแล้ว':'ไม่ได้รับอนุมัติ'}</span>`:!full?`<button class="c59Btn primary" onclick="c59Join('${t.id}',this)">สนใจเข้าร่วม</button>`:`<button class="c59Btn" disabled>${closed?'ปิดรับแล้ว':'เต็มแล้ว'}</button>`}</div></article>`}
function c59Render(){const host=document.getElementById('c59Body');if(!host)return;const uid=state.user.uid;if(state.c59Tab==='calendar'){const rows=state.c59Topics.filter(t=>t.ownerId===uid||(state.c59Requests[t.id]||{})[uid]?.status==='approved').sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`));host.innerHTML=`<section class="c59Calendar"><h2>Group Player Calendar</h2>${rows.map(t=>`<button class="c59Event" onclick="c59Details('${t.id}')"><b>${esc(t.date)}<small>${esc(t.start)}–${esc(t.end)}</small></b><span><b>Group Player • ${esc(t.venueName)}</b><small>${Number(t.approvedCount||1)} คนเข้าร่วม</small></span><span>ดูรายละเอียด ›</span></button>`).join('')||'<div class="c59Empty">ยังไม่มี Group Player ใน Calendar</div>'}</section>`;return}if(state.c59Tab==='tickets'){const rows=state.c59Tickets.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));host.innerHTML=`<div class="c59Grid">${rows.map(x=>`<article class="c59Card"><span class="c59Badge">${x.type==='group_join_request'?'คำขอเข้าร่วม':x.type==='group_join_approved'?'ยืนยันเข้าร่วม':x.type==='group_join_rejected'?'ปฏิเสธคำขอ':'Group เต็มแล้ว'}</span><h3>${esc(x.actorName||'Athlete')}</h3><p>${esc(x.date||'')} ${esc(x.start||'')} • ${esc(x.venueName||'')}</p>${x.type==='group_join_request'?`<button class="c59Btn" onclick="c59OpenOwner('${x.topicId}')">ตรวจสอบคำขอ</button>`:`<button class="c59Btn" onclick="c59Details('${x.topicId}')">ดู Ticket</button>`}</article>`).join('')||'<div class="c59Empty">ยังไม่มี Ticket</div>'}</div>`;return}let rows=state.c59Topics.filter(t=>t.status!=='cancelled');if(state.c59Tab==='mine')rows=rows.filter(t=>t.ownerId===uid);host.innerHTML=`<div class="c59Grid">${rows.sort((a,b)=>`${a.date}${a.start}`.localeCompare(`${b.date}${b.start}`)).map(c59Card).join('')||'<div class="c59Empty">ยังไม่มีกลุ่มในขณะนี้</div>'}</div>`}
function c59OpenCreate(){document.body.insertAdjacentHTML('beforeend',`<div id="c59Modal" class="c59Modal"><div><div class="c59ModalHead"><h2>สร้างหัวข้อหาเพื่อนตี</h2><button onclick="c59Close()">✕</button></div><form class="c59Form" onsubmit="c59Create(event)"><div class="c59FormGrid"><label>กีฬา<select id="c59Sport"><option>Tennis</option><option>Pickle Ball</option><option>Badminton</option><option>Football</option></select></label><label>สนาม<select id="c59Venue" onchange="c59OtherVenue.classList.toggle('hidden',this.value!=='__other')">${c59VenueOptions()}<option value="__other">สนามอื่น (พิมพ์เอง)</option></select><input id="c59OtherVenue" class="hidden" placeholder="ชื่อสนาม"></label><label>จำนวนคนรวมเจ้าของ<input id="c59Capacity" type="number" min="2" max="50" value="4" required></label><label>วันที่<input id="c59Date" type="date" min="${TODAY}" value="${TODAY}" required></label><label>เริ่ม<input id="c59Start" type="time" required></label><label>สิ้นสุด<input id="c59End" type="time" required></label></div><button class="c59Btn primary" style="width:100%;margin-top:12px">สร้างหัวข้อ</button></form></div></div>`)}
function c59Close(){document.getElementById('c59Modal')?.remove()}
async function c59Create(e){e.preventDefault();const venue=c59Venue.value==='__other'?c59OtherVenue.value.trim():c59Venue.value,cap=Number(c59Capacity.value);if(!venue)return alert('กรุณาระบุชื่อสนาม');if(c59Date.value<TODAY||c59End.value<=c59Start.value)return alert('กรุณาตรวจสอบวันที่และเวลา');const ref=db.ref('groupPlayTopics').push(),id=ref.key,topic={ownerId:state.user.uid,ownerName:c59Name(),sport:c59Sport.value,venueName:venue,date:c59Date.value,start:c59Start.value,end:c59End.value,capacityTotal:cap,approvedCount:1,status:'open',createdAt:firebase.database.ServerValue.TIMESTAMP,updatedAt:firebase.database.ServerValue.TIMESTAMP},up={};up[`groupPlayTopics/${id}`]=topic;up[`groupPlayParticipants/${id}/${state.user.uid}`]={userId:state.user.uid,userName:c59Name(),role:'owner',approvedAt:firebase.database.ServerValue.TIMESTAMP};try{await db.ref().update(up);c59Close();await c59Load()}catch(x){alert('สร้างหัวข้อไม่สำเร็จ: '+(x.message||x))}}
async function c59Join(id,btn){if(btn.disabled)return;const t=state.c59Topics.find(x=>x.id===id);if(!t||t.ownerId===state.user.uid)return;try{btn.disabled=true;const key=db.ref(`groupPlayTickets/${t.ownerId}`).push().key,up={};up[`groupPlayRequests/${id}/${state.user.uid}`]={userId:state.user.uid,userName:c59Name(),status:'pending',createdAt:firebase.database.ServerValue.TIMESTAMP};up[`groupPlayTickets/${t.ownerId}/${key}`]={type:'group_join_request',topicId:id,actorId:state.user.uid,actorName:c59Name(),venueName:t.venueName,date:t.date,start:t.start,createdAt:firebase.database.ServerValue.TIMESTAMP};await db.ref().update(up);await c59Load()}catch(e){alert('ส่งความสนใจไม่สำเร็จ: '+(e.message||e));btn.disabled=false}}
function c59OpenOwner(id){const t=state.c59Topics.find(x=>x.id===id);if(!t)return;const rs=Object.values(state.c59Requests[id]||{});document.body.insertAdjacentHTML('beforeend',`<div id="c59Modal" class="c59Modal"><div><div class="c59ModalHead"><div><h2>คำขอเข้าร่วม</h2><p>${esc(t.venueName)} • ${esc(t.date)} ${esc(t.start)}</p></div><button onclick="c59Close()">✕</button></div>${rs.map(r=>`<div class="c59Request"><div><b>${esc(r.userName)}</b><small>${r.status==='pending'?'รอพิจารณา':r.status==='approved'?'อนุมัติแล้ว':'ปฏิเสธแล้ว'}</small></div>${r.status==='pending'?`<div><button class="c59Btn primary" onclick="c59Decide('${id}','${r.userId}','approved',this)">อนุมัติ</button> <button class="c59Btn" onclick="c59Decide('${id}','${r.userId}','rejected',this)">ปฏิเสธ</button></div>`:''}</div>`).join('')||'<div class="c59Empty">ยังไม่มีคำขอ</div>'}</div></div>`)}
async function c59Decide(id,uid,status,btn){
 const t=state.c59Topics.find(x=>x.id===id),r=(state.c59Requests[id]||{})[uid];if(!t||!r||r.status!=='pending')return;btn.disabled=true;
 try{
  const claim=await db.ref(`groupPlayRequests/${id}/${uid}`).transaction(x=>x&&x.status==='pending'?{...x,status,respondedAt:Date.now()}:undefined);
  if(!claim.committed)throw Error('คำขอนี้ถูกดำเนินการแล้ว');let finalStatus=status,isFull=false;
  if(status==='approved'){
   const counted=await db.ref(`groupPlayTopics/${id}`).transaction(x=>{if(!x||x.ownerId!==state.user.uid||x.status==='full'||Number(x.approvedCount||1)>=Number(x.capacityTotal||2))return;const n=Number(x.approvedCount||1)+1;return {...x,approvedCount:n,status:n>=Number(x.capacityTotal)?'full':x.status,updatedAt:Date.now()}});
   if(!counted.committed){finalStatus='rejected';await db.ref(`groupPlayRequests/${id}/${uid}`).update({status:'rejected',reason:'group_full',respondedAt:firebase.database.ServerValue.TIMESTAMP})}else isFull=counted.snapshot.val().status==='full';
  }
  const key=db.ref(`groupPlayTickets/${uid}`).push().key,up={};up[`groupPlayTickets/${uid}/${key}`]={type:finalStatus==='approved'?'group_join_approved':'group_join_rejected',topicId:id,actorId:state.user.uid,actorName:t.ownerName,venueName:t.venueName,date:t.date,start:t.start,createdAt:firebase.database.ServerValue.TIMESTAMP};if(finalStatus==='approved')up[`groupPlayParticipants/${id}/${uid}`]={userId:uid,userName:r.userName,role:'player',approvedAt:firebase.database.ServerValue.TIMESTAMP};await db.ref().update(up);c59Close();await c59Load();if(isFull)await c59NotifyFull(id)
 }catch(e){alert('บันทึกผลไม่สำเร็จ: '+(e.message||e));btn.disabled=false}
}
async function c59NotifyFull(id){const t=state.c59Topics.find(x=>x.id===id);if(!t)return;const ps=(await db.ref(`groupPlayParticipants/${id}`).once('value')).val()||{},up={};Object.keys(ps).filter(uid=>uid!==t.ownerId).forEach(uid=>{const k=db.ref(`groupPlayTickets/${uid}`).push().key;up[`groupPlayTickets/${uid}/${k}`]={type:'group_full',topicId:id,actorId:t.ownerId,actorName:t.ownerName,venueName:t.venueName,date:t.date,start:t.start,createdAt:firebase.database.ServerValue.TIMESTAMP}});if(Object.keys(up).length)await db.ref().update(up)}
async function c59MarkFull(id){const t=state.c59Topics.find(x=>x.id===id);if(!t||t.ownerId!==state.user.uid)return;const count=Number(t.approvedCount||1),cap=Number(t.capacityTotal||2),closedEarly=count<cap;if(!confirm(closedEarly?'ปิดรับสมาชิกตอนนี้โดยไม่ต้องรอให้ครบจำนวน?':'ยืนยันว่ากลุ่มเต็มและปิดรับสมาชิก?'))return;await db.ref(`groupPlayTopics/${id}`).update({status:'full',closedEarly,closedAt:firebase.database.ServerValue.TIMESTAMP,updatedAt:firebase.database.ServerValue.TIMESTAMP});await c59NotifyFull(id);await c59Load()}
function c59Details(id){const t=state.c59Topics.find(x=>x.id===id);if(!t)return;const ps=Object.values(state.c59Participants[id]||{});document.body.insertAdjacentHTML('beforeend',`<div id="c59Modal" class="c59Modal"><div><div class="c59ModalHead"><h2>Group Player Ticket</h2><button onclick="c59Close()">✕</button></div><p><b>${esc(t.venueName)}</b><br>${esc(t.date)} • ${esc(t.start)}–${esc(t.end)}</p><h3>ผู้เข้าร่วมที่อนุมัติแล้ว (${ps.length})</h3>${ps.map(p=>`<div class="c59Request"><b>${esc(p.userName)}</b><span class="c59Badge">${p.role==='owner'?'เจ้าของหัวข้อ':'เข้าร่วม'}</span></div>`).join('')||'<p class="muted">กำลังรอรายชื่อ</p>'}<p class="muted">Ticket นี้ยืนยันเฉพาะผู้ที่เจ้าของหัวข้ออนุมัติแล้ว กรุณาไปพบกันตามสนามและเวลาที่ระบุ</p></div></div>`)}
const c59Menu=showAthleteMenu;showAthleteMenu=function(page){if(page!=='groupplay')return c59Menu(page);setAthleteNavActive(page);athletePage.classList.remove('hidden');coachPage.classList.add('hidden');Array.from(athletePage.children).forEach(x=>x.style.display='none');let dyn=document.getElementById('c59Host');if(!dyn){dyn=document.createElement('div');dyn.id='c59Host';athletePage.appendChild(dyn)}dyn.style.display='block';dyn.innerHTML=c59Page();setTimeout(c59Load,20)}
const c59Nav=renderNav;renderNav=function(){c59Nav();if(state.role!=='athlete')return;const logout=sidebar.querySelector('.sideLogout');if(!sidebar.querySelector('[data-athlete-page="groupplay"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.athletePage='groupplay';b.onclick=()=>showAthleteMenu('groupplay');b.innerHTML='<span class="navIcon">♟</span>หาเพื่อนตี';sidebar.insertBefore(b,logout)}if(!mobileNav.querySelector('[data-athlete-mobile="groupplay"]')){const b=document.createElement('button');b.dataset.athleteMobile='groupplay';b.onclick=()=>showAthleteMenu('groupplay');b.innerHTML='♟<br>หาเพื่อนตี';mobileNav.insertBefore(b,mobileNav.children[3]||null)}}
