/* Sprint 3.9 — Marketplace profile, pay-before-request, booking chat, subscription payment */
state.pendingBookingPayment=null;
function cdCoachByUid(uid){return (state.coaches||[]).find(c=>c.uid===uid)||{} }
function cdCoachProfileModal(uid){
 const c=cdCoachByUid(uid),name=c.displayName||c.nameTh||c.nameEn||'Coach Di',photo=c.photoURL||'',sport=SPORTS.find(x=>x.id===coachSport(c))?.label||coachSport(c)||'Sport';
 csModal(`<button class="csSheetClose" onclick="csCloseModal()">✕</button><div style="display:flex;gap:16px;align-items:center">${photo?`<img src="${esc(photo)}" style="width:86px;height:86px;border-radius:22px;object-fit:cover">`:`<div class="coachAvatar" style="width:86px;height:86px">${esc(name.slice(0,1))}</div>`}<div><div class="small">${esc(sport)} • ${esc(c.coachDiId||'Coach Di')}</div><h2 style="margin:2px 0">${esc(name)}</h2><div class="muted">${esc(c.bio||'เลือกวันและเวลาว่างด้านล่างเพื่อจองคลาส')}</div></div></div><div class="notice" style="margin-top:16px">ค่าคลาสเริ่มต้น <b>${baht(Number(state.pricing?.p60||0))} / คน / ชั่วโมง</b></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:14px"><button class="pill primary" onclick="csCloseModal();changeAthleteCoach('${uid}');setTimeout(()=>document.querySelector('.scheduleShell')?.scrollIntoView({behavior:'smooth'}),150)">ดูตารางว่าง & จอง</button></div>`)
}
const _renderCoachDiscovery39=renderCoachDiscovery;
renderCoachDiscovery=function(){_renderCoachDiscovery39();document.querySelectorAll('.coachCard').forEach((el,i)=>{let list=filteredCoaches(),c=list[i];if(!c)return;el.onclick=()=>cdCoachProfileModal(c.uid);let extra=document.createElement('div');extra.className='small';extra.style.marginTop='6px';extra.textContent='ดูโปรไฟล์ →';el.appendChild(extra)})}
async function cdGetPublicPay(coachId){try{let x=await db.ref(`coachPaymentPublic/${coachId}`).once('value');return x.val()||{}}catch(e){if(String(e?.code||e?.message||'').toLowerCase().includes('permission')){let x=await db.ref(`coachProfiles/${coachId}/paymentPublic`).once('value');return x.val()||{}}throw e}}
function confirmCourtBooking(venueId,h){if(!courtConfirmed.checked)return;cdPreparePaymentBeforeBooking(venueId,h)}
async function cdPreparePaymentBeforeBooking(venueId,h){
 const box=document.getElementById('athletePaymentStep')||document.createElement('div');box.id='athletePaymentStep';box.className='notice';box.style.marginTop='10px';if(!box.parentNode)verifyResult.appendChild(box);box.innerHTML='กำลังโหลดข้อมูลชำระเงิน...';
 try{let acc=await cdGetPublicPay(state.coachId);if(acc.verificationStatus!=='approved'||!acc.qrDataUrl)throw new Error('บัญชีรับเงินของ Coach ยังไม่ผ่านการ Verify โดย Admin');let c=cdCoachByUid(state.coachId),name=c.displayName||c.nameTh||'Coach Di',price=Number(state.pricing?.p60||0);box.innerHTML=`<div style="display:grid;gap:12px"><b>ชำระค่าคลาสก่อนส่งคำขอจอง</b><div>${esc(name)} • <b>${baht(price)} / คน / ชั่วโมง</b></div><div class="s38QR"><img src="${acc.qrDataUrl}" style="max-width:190px;border-radius:16px"></div><div>${esc(acc.bank||'')} • ${esc(acc.accountNumber||acc.masked||'')}<br>ชื่อบัญชี <b>${esc(acc.accountName||'')}</b></div><div class="notice"><b>หมายเหตุ:</b> ราคานี้เป็นราคาต่อ 1 คน หากเรียนมากกว่า 1 คน ค่าใช้จ่ายส่วนเพิ่มจะเก็บที่สนามตามเงื่อนไขของ Coach/สนาม</div><label><span class="label">จำนวนผู้เรียน</span><input id="cdParticipants" class="field" type="number" min="1" value="1"></label><label><span class="label">แนบสลิปก่อนส่งคำขอ</span><input id="cdPreSlip" class="field" type="file" accept="image/png,image/jpeg,image/webp"></label><button id="submitCoachBookingBtn" class="pill primary" onclick="cdCreatePaidBooking('${venueId}',${h},this)">แนบสลิปและส่งคำขอจอง</button></div>`}catch(e){box.innerHTML=`<div class="error">${esc(e.message||'ไม่สามารถโหลด QR ได้')}</div>`}}
async function cdCreatePaidBooking(venueId,h,btn){
 if(btn)btn.disabled=true;try{let slip=await s38ReadFile(document.getElementById('cdPreSlip')),participants=Math.max(1,Number(document.getElementById('cdParticipants')?.value||1));const coachId=String(state.coachId||''),athleteId=state.user.uid,date=String(state.selectedCell?.date||state.selectedDate),court=venueId==='other'?(chosenOther?.name||'สนามอื่น'):(venueName(venueId)||'สนามที่เลือก'),dd=date.slice(-2),hh=String(Math.floor(h)).padStart(2,'0'),suffix=Math.random().toString(36).slice(2,6).toUpperCase(),id=`${dd}${hh}${suffix}`;let us=(await db.ref(`users/${athleteId}`).once('value')).val()||{},phone=us.phone||'';if(!phone){phone=(prompt('กรุณาระบุเบอร์โทรศัพท์')||'').trim();if(!phone)throw new Error('กรุณาระบุเบอร์โทรศัพท์');await db.ref(`users/${athleteId}`).update({phone})}let booking=cleanFirebaseObject({coachId,athleteId,athlete:us.displayName||state.user.email||'Athlete',athleteEmail:state.user.email||'',phone,date,start:Number(h),end:Number(h)+1,venueId,venue:court,status:'payment_submitted',approvalStatus:'pending',paymentStatus:'payment_submitted',paymentProofDataUrl:slip,paymentSubmittedAt:firebase.database.ServerValue.TIMESTAMP,participants,pricePerPersonSatang:Number(state.pricing?.p60||0),priceSatang:Number(state.pricing?.p60||0),travelFeeSatang:0,platformFeeSatang:0,createdAt:firebase.database.ServerValue.TIMESTAMP});await db.ref(`bookings/${id}`).set(booking);await db.ref(`notifications/${coachId}`).push().set({type:'new_paid_booking',bookingId:id,senderId:athleteId,message:`มีคำขอจองใหม่ ${id} พร้อมสลิป กรุณาตรวจสอบและยืนยัน`,createdAt:firebase.database.ServerValue.TIMESTAMP,read:false});await audit('paid_booking_submitted',id,{coachId,date,start:h,participants});closeSheet();showBookingSuccessTicket(id,{...booking,status:'payment_submitted'});alert('ส่งคำขอพร้อมสลิปแล้ว รอ Coach ตรวจสอบและยืนยัน')}catch(e){alert(e.message||'ส่งคำขอไม่สำเร็จ');if(btn)btn.disabled=false}}
function showBookingSuccessTicket(id,b){let el=document.getElementById('inlineBookingTicket');if(!el)return;el.innerHTML=`<div class="ticketTop"><div><div class="ticketTitle">✓ ส่งคำขอพร้อมสลิปให้ Coach แล้ว</div><div class="ticketMeta"><b>${thaiDate(b.date)}</b> • ${fmt(b.start)}–${fmt(b.end)}<br>${esc(b.venue)}<br>Booking ID: ${esc(id)}</div></div><span class="status pending">รอ Coach ตรวจสลิป</span></div><div class="ticketActions"><button class="pill primary" onclick="showAthleteMenu('mybookings')">ดูการจองของฉัน</button><button class="pill" onclick="cdOpenChat('${esc(id)}')">แชทกับ Coach</button></div>`;el.classList.remove('hidden')}
function cdChatAllowed(b){return b&&(state.role==='admin'||b.coachId===state.user?.uid||b.athleteId===state.user?.uid)}
async function cdOpenChat(id){let b=state.bookings.find(x=>x.id===id);if(!cdChatAllowed(b))return alert('ไม่มีสิทธิ์เปิดแชทนี้');csModal(`<button class="csSheetClose" onclick="csCloseModal()">✕</button><h2>แชท • Booking ${esc(id)}</h2><div id="cdChatMessages" style="height:300px;overflow:auto;border:1px solid #ddd;border-radius:14px;padding:10px"></div><div style="display:flex;gap:8px;margin-top:10px"><input id="cdChatInput" class="field" placeholder="พิมพ์ข้อความ..."><button class="pill primary" onclick="cdSendChat('${esc(id)}')">ส่ง</button></div>`);db.ref(`bookingChats/${id}/messages`).limitToLast(100).on('value',snap=>{let el=document.getElementById('cdChatMessages');if(!el)return;let rows=Object.values(snap.val()||{});el.innerHTML=rows.map(m=>`<div style="margin:7px 0;padding:8px 10px;border-radius:12px;background:${m.senderId===state.user.uid?'#eef6ff':'#f3f4f1'}"><b>${esc(m.senderRole||'user')}</b> ${esc(m.text||'')}</div>`).join('')||'<div class="muted">ยังไม่มีข้อความ</div>';el.scrollTop=el.scrollHeight})}
async function cdSendChat(id){let input=document.getElementById('cdChatInput'),text=(input?.value||'').trim(),b=state.bookings.find(x=>x.id===id);if(!text||!cdChatAllowed(b))return;await db.ref(`bookingChats/${id}/messages`).push().set({senderId:state.user.uid,senderRole:state.role,text,createdAt:firebase.database.ServerValue.TIMESTAMP});input.value=''}
const _renderAthleteBookings39=renderAthleteBookings;
renderAthleteBookings=function(){_renderAthleteBookings39();document.querySelectorAll('#athleteBookings .card').forEach((card,i)=>{let rows=state.bookings.filter(b=>b.athleteId===state.user?.uid).sort((a,b)=>String(a.date).localeCompare(String(b.date))||Number(a.start)-Number(b.start)),b=rows[i];if(b){let bt=document.createElement('button');bt.className='pill';bt.style.marginTop='10px';bt.textContent='💬 แชทกับ Coach';bt.onclick=()=>cdOpenChat(b.id);card.appendChild(bt)}})}
const _s38CoachPaymentAction39=s38CoachPaymentAction;
s38CoachPaymentAction=function(b){let a=_s38CoachPaymentAction39(b);return a+` <button class="pill" onclick="cdOpenChat('${esc(b.id)}')">💬 แชท</button>`}
async function cdSyncPublicPayment(uid){let a=(await db.ref(`coachPaymentAccounts/${uid}`).once('value')).val()||{},number=String(a.accountNumber||'').replace(/\D/g,'').slice(0,20),pub={verificationStatus:'approved',bank:a.bank||'',accountNumber:number.length>=8?number:'',masked:a.masked||'',accountName:a.accountName||'',qrDataUrl:a.qrDataUrl||'',updatedAt:firebase.database.ServerValue.TIMESTAMP},profilePub={verificationStatus:'approved',bank:pub.bank,masked:pub.masked,accountName:pub.accountName,qrDataUrl:pub.qrDataUrl,updatedAt:pub.updatedAt};if(a.verificationStatus==='approved'){await db.ref(`coachPaymentPublic/${uid}`).set(pub);await db.ref(`coachProfiles/${uid}/paymentPublic`).set(profilePub)}else{await db.ref(`coachPaymentPublic/${uid}`).remove();await db.ref(`coachProfiles/${uid}/paymentPublic`).remove()}}
async function cdSyncAllApprovedPublicPayments(){if(state.role!=='admin'||state.c86PaymentSyncRunning)return;state.c86PaymentSyncRunning=true;try{const s=await db.ref('coachPaymentAccounts').once('value'),rows=Object.entries(s.val()||{}).filter(([,a])=>a.verificationStatus==='approved'&&a.accountNumber);await Promise.all(rows.map(([uid])=>cdSyncPublicPayment(uid)))}catch(e){console.warn('Public payment account sync skipped',e)}finally{state.c86PaymentSyncRunning=false}}
const _adminVerifyPayout39=adminVerifyPayout;adminVerifyPayout=async function(uid,approve){await _adminVerifyPayout39(uid,approve);await cdSyncPublicPayment(uid)}
function cdSubscriptionPayCard(){return `<div class="card"><h3>ชำระ Coach Di Subscription</h3><p>หลัง Trial 60 วัน ค่าบริการ <b>฿199 / เดือน</b></p><div id="cdSubPayInfo">กำลังโหลดช่องทางชำระเงิน...</div></div>`}
const _coachDashboard39=coachDashboard;coachDashboard=function(){setTimeout(cdLoadSubscriptionPayInfo,50);return _coachDashboard39()+cdSubscriptionPayCard()}
async function cdLoadSubscriptionPayInfo(){let el=document.getElementById('cdSubPayInfo');if(!el)return;let cfg=(await db.ref('appConfig/subscriptionPayment').once('value')).val()||{};el.innerHTML=`${cfg.qrDataUrl?`<img src="${cfg.qrDataUrl}" style="max-width:180px;border-radius:16px"><div>${esc(cfg.bank||'')} • ${esc(cfg.accountName||'')}</div>`:'<div class="muted">Admin ยังไม่ได้ตั้ง QR รับค่า Subscription</div>'}<label><span class="label">แนบสลิป ฿199</span><input id="cdSubSlip" class="field" type="file" accept="image/*"></label><button class="pill primary" style="margin-top:8px" onclick="cdSubmitSubscriptionSlip(this)">ส่งสลิปให้ Admin</button>`}
async function cdSubmitSubscriptionSlip(btn){if(btn)btn.disabled=true;try{let slip=await s38ReadFile(document.getElementById('cdSubSlip'));await db.ref('subscriptionPaymentRequests').push().set({coachId:state.user.uid,amountSatang:19900,slipDataUrl:slip,status:'pending',createdAt:firebase.database.ServerValue.TIMESTAMP});alert('ส่งสลิป Subscription ให้ Admin แล้ว')}catch(e){alert(e.message||'ส่งสลิปไม่สำเร็จ');if(btn)btn.disabled=false}}
function cdAdminSubPaymentConfig(){return `<div class="card"><h2>ช่องทางรับค่า Subscription ฿199</h2><div class="formgrid"><label><span class="label">ธนาคาร</span><input id="cdSubBank" class="field"></label><label><span class="label">ชื่อบัญชี</span><input id="cdSubAccount" class="field"></label><label><span class="label">QR Code</span><input id="cdSubQR" class="field" type="file" accept="image/*"></label></div><button class="pill primary" onclick="cdSaveSubPaymentConfig()">บันทึกช่องทางชำระเงิน</button><div id="cdSubRequests" style="margin-top:14px"></div></div>`}
const _adminDashboard39=adminDashboard;adminDashboard=function(){setTimeout(cdLoadSubRequests,80);return _adminDashboard39()+cdAdminSubPaymentConfig()}
async function cdSaveSubPaymentConfig(){let old=(await db.ref('appConfig/subscriptionPayment').once('value')).val()||{},f=document.getElementById('cdSubQR')?.files?.[0],qr=old.qrDataUrl||'';if(f){let input=document.getElementById('cdSubQR');qr=await s38ReadFile(input)}await db.ref('appConfig/subscriptionPayment').set({bank:cdSubBank.value.trim(),accountName:cdSubAccount.value.trim(),qrDataUrl:qr,updatedAt:firebase.database.ServerValue.TIMESTAMP});alert('บันทึกแล้ว')}
async function cdLoadSubRequests(){let el=document.getElementById('cdSubRequests');if(!el)return;let s=await db.ref('subscriptionPaymentRequests').once('value'),rows=Object.entries(s.val()||{}).filter(([id,r])=>r.status==='pending');el.innerHTML=rows.length?'<h3>สลิปรออนุมัติ</h3>'+rows.map(([id,r])=>`<div class="card"><b>${esc(r.coachId)}</b> • ฿199<br><img src="${r.slipDataUrl}" style="max-width:160px;border-radius:12px"><div><button class="pill primary" onclick="cdApproveSubRequest('${id}','${r.coachId}',this)">ตรวจแล้ว • Active 1 เดือน</button></div></div>`).join(''):'<div class="muted">ไม่มีสลิปรออนุมัติ</div>'}
async function cdApproveSubRequest(id,uid,btn){await cdActivateSubscription(uid,btn);await db.ref(`subscriptionPaymentRequests/${id}`).update({status:'approved',approvedBy:state.user.uid,approvedAt:firebase.database.ServerValue.TIMESTAMP});await cdLoadSubRequests()}
