/* Sprint 3.9.2 — Athlete: Category > Coach > Profile/Schedule > Court warning > Court confirm > Pay > My Calendar */
state.athleteFlow='category';
function cd392ApplyFlow(mode){
 state.athleteFlow=mode;athletePage.classList.remove('flow-category','flow-coaches','flow-profile');athletePage.classList.add('flow-'+mode);
 const profile=document.getElementById('cd392CoachProfile');if(profile)profile.remove();
}
const _showAthlete392=showAthlete;
showAthlete=function(){state.selectedSport=null;state.coachId=null;_showAthlete392();setTimeout(()=>{cd392ApplyFlow('category');renderCoachDiscovery()},0)};
const _showAthleteMenu392=showAthleteMenu;
showAthleteMenu=function(page){_showAthleteMenu392(page);if(page==='home'||page==='coach'){state.selectedSport=null;state.coachId=null;cd392ApplyFlow('category');renderCoachDiscovery()}}
selectSport=function(id){state.selectedSport=id;state.coachId=null;state.selectedCell=null;cd392ApplyFlow('coaches');renderCoachDiscovery()}
renderCoachDiscovery=function(){
 let cats=document.getElementById('sportCats'),cards=document.getElementById('coachCards');if(!cats||!cards)return;
 cats.innerHTML=SPORTS.map(x=>`<button class="sportCat ${state.selectedSport===x.id?'active':''}" onclick="selectSport('${x.id}')"><span class="sportIcon">${x.icon}</span>${x.label}</button>`).join('');
 if(!state.selectedSport){cards.innerHTML='';selectedCoachIdentity.textContent='';return}
 let list=filteredCoaches();cards.innerHTML=list.length?list.map(c=>{let name=c.displayName||c.nameTh||c.nameEn||'Coach',photo=c.photoURL||c.photo||c.image||'';return `<button class="coachCard" onclick="cd392OpenCoach('${c.uid}')">${photo?`<img class="coachAvatar" src="${esc(photo)}" alt="${esc(name)}">`:`<div class="coachAvatar">${esc(name.slice(0,1))}</div>`}<div class="coachCardName">${esc(name)}</div><div class="coachSport">${esc(SPORTS.find(x=>x.id===state.selectedSport)?.label||'')} • ${esc(c.coachDiId||'Coach Di')}</div><div class="small" style="margin-top:6px">ดูโปรไฟล์และตาราง →</div></button>`}).join(''):'<div class="coachEmpty">ยังไม่มีโค้ชใน Category นี้</div>';
 selectedCoachIdentity.textContent='เลือก Coach เพื่อดูข้อมูลและตารางว่าง';
}
async function cd392OpenCoach(uid){
 state.coachId=uid;state.selectedCell=null;await loadCoachScopedData(uid);cd392ApplyFlow('profile');
 const c=cdCoachByUid(uid),name=c.displayName||c.nameTh||c.nameEn||'Coach',photo=c.photoURL||c.photo||'',sport=SPORTS.find(x=>x.id===coachSport(c))?.label||'';
 const box=document.createElement('div');box.id='cd392CoachProfile';box.innerHTML=`<button class="pill flowBack" onclick="cd392BackToCoaches()">← กลับไปเลือก Coach</button><div class="coachProfileInline">${photo?`<img src="${esc(photo)}" alt="${esc(name)}">`:`<div class="coachAvatar">${esc(name.slice(0,1))}</div>`}<div><div class="small">${esc(sport)} • ${esc(c.coachDiId||'Coach Di')}</div><h2>${esc(name)}</h2><div class="muted">${esc(c.bio||'เลือกเวลาว่างจากตารางด้านล่างเพื่อจองคลาส')}</div><div style="margin-top:8px"><b>${baht(Number(state.pricing?.p60||0))} / คน / ชั่วโมง</b></div></div></div>`;
 const shell=document.querySelector('.scheduleShell');shell.parentNode.insertBefore(box,shell);renderSchedule();setTimeout(()=>box.scrollIntoView({behavior:'smooth',block:'start'}),50)
}
function cd392BackToCoaches(){state.coachId=null;state.selectedCell=null;cd392ApplyFlow('coaches');renderCoachDiscovery()}
function selectDateSlot(date,h){let s=dayCellStatus(date,h);if(s.type!=='available')return;state.selectedDate=date;state.selectedCell={date,h,venueId:null};renderSchedule();cd392CourtWarning(date,h)}
function cd392CourtWarning(date,h){
 const c=cdCoachByUid(state.coachId),name=c.displayName||c.nameTh||c.nameEn||'Coach';
 sheetContent.innerHTML=`<h2 style="margin:0">รายละเอียดการจอง</h2><p><b>${esc(name)}</b><br>${thaiDate(date)} • ${fmt(h)}–${fmt(h+1)}</p><div class="notice bookingWarning"><b>⚠️ กรุณาจองสนามก่อนจอง Coach</b><br>นักกีฬาต้องจองสนามและได้รับการยืนยันสนามเรียบร้อยแล้ว ก่อนส่งคำขอจอง Coach เพื่อป้องกันกรณีมี Coach แต่ไม่มีสนาม</div><div class="sheetActions"><button class="pill" onclick="closeSheet()">ยกเลิก</button><button class="pill primary" onclick="cd392AcknowledgeCourt('${date}',${h})">รับทราบ</button></div>`;sheetWrap.classList.remove('hidden')
}
function cd392AcknowledgeCourt(date,h){
 state.selectedDate=date;state.selectedCell={date,h,venueId:null};let options=state.venues.filter(v=>v.id!=='other'&&h>=v.openStart&&h<v.openEnd).map(v=>`<option value="${v.id}">${esc(v.name)}</option>`).join('');
 sheetContent.innerHTML=`<h2 style="margin:0">เลือกสนามที่ยืนยันแล้ว</h2><p>${thaiDate(date)} • ${fmt(h)}–${fmt(h+1)}</p><label class="label">สนาม</label><select id="bookingVenueSelect" class="field"><option value="">— เลือกสนาม —</option>${options}<option value="other">สนามอื่น</option></select><div id="otherVenueBox"></div><label style="display:flex;gap:9px;align-items:flex-start;margin-top:14px"><input id="cd392CourtConfirmed" type="checkbox" style="margin-top:5px"> <span>ฉันยืนยันว่าได้จองสนามและได้รับการ Confirm จากสนามแล้ว</span></label><div class="sheetActions"><button class="pill" onclick="closeSheet()">ยกเลิก</button><button class="pill primary" onclick="cd392ConfirmVenue(${h})">ยืนยันสนาม</button></div>`;
 const select=document.getElementById('bookingVenueSelect'),otherBox=document.getElementById('otherVenueBox');chosenOther=null;
 select.addEventListener('change',()=>{chosenOther=null;otherBox.innerHTML=select.value==='other'?venueSearchHTML():''})
}
async function cd392ConfirmVenue(h){
 const select=document.getElementById('bookingVenueSelect'),confirmed=document.getElementById('cd392CourtConfirmed');if(!select||!confirmed)return alert('แบบฟอร์มสนามไม่พร้อม กรุณาปิดแล้วเลือกเวลาใหม่');let venueId=select.value;if(!venueId)return alert('กรุณาเลือกสนาม');if(!confirmed.checked)return alert('กรุณายืนยันว่าจองและ Confirm สนามแล้ว');if(venueId==='other'&&!resolveOtherVenue())return alert('กรุณาพิมพ์ชื่อสนามอย่างน้อย 2 ตัวอักษร หรือเลือกจากรายการ');
 let court=venueId==='other'?chosenOther.name:venueName(venueId),travel=travelCheck(state.selectedDate,h,venueId,court);if(!travel.ok){let suggestions=suggestNextSlots(state.selectedDate,h,venueId,court);return alert(`เวลานี้ไม่เหมาะกับการเดินทางของ Coach\n${travel.reason}\nเวลาที่แนะนำ: ${suggestions.map(fmt).join(', ')||'กรุณาเลือกวันอื่น'}`)}
 state.selectedCell.venueId=venueId;sheetContent.innerHTML=`<h2 style="margin:0">ชำระค่าคลาส</h2><p><b>${esc(court)}</b><br>${thaiDate(state.selectedDate)} • ${fmt(h)}–${fmt(h+1)}</p><div id="athletePaymentStep" class="notice">กำลังโหลด QR Code ของ Coach...</div><div class="sheetActions"><button class="pill" onclick="closeSheet()">ยกเลิก</button></div>`;await cdPreparePaymentBeforeBooking(venueId,h)
}
const _cdPreparePaymentBeforeBooking392=cdPreparePaymentBeforeBooking;
cdPreparePaymentBeforeBooking=async function(venueId,h){
 const target=document.getElementById('athletePaymentStep');if(!target)return _cdPreparePaymentBeforeBooking392(venueId,h);target.innerHTML='กำลังโหลดข้อมูลชำระเงิน...';
 try{let acc=await cdGetPublicPay(state.coachId);if(acc.verificationStatus!=='approved'||!acc.qrDataUrl)throw new Error('บัญชีรับเงินของ Coach ยังไม่ผ่านการ Verify โดย Admin');let c=cdCoachByUid(state.coachId),name=c.displayName||c.nameTh||'Coach Di',price=Number(state.pricing?.p60||0);target.innerHTML=`<div style="display:grid;gap:12px"><b>${esc(name)} • ${baht(price)} / คน / ชั่วโมง</b><div class="s38QR"><img src="${acc.qrDataUrl}" style="max-width:190px;border-radius:16px"></div><div>${esc(acc.bank||'')} • ${esc(acc.accountNumber||acc.masked||'')}<br>ชื่อบัญชี <b>${esc(acc.accountName||'')}</b></div><div class="notice"><b>หมายเหตุ:</b> ราคานี้เป็นราคาต่อ 1 คน หากเรียนมากกว่า 1 คน ค่าใช้จ่ายส่วนเพิ่มจะเก็บที่สนามตามเงื่อนไขของ Coach/สนาม</div><label><span class="label">จำนวนผู้เรียน</span><input id="cdParticipants" class="field" type="number" min="1" value="1"></label><label><span class="label">แนบสลิปก่อนส่งคำขอ</span><input id="cdPreSlip" class="field" type="file" accept="image/png,image/jpeg,image/webp"></label><button id="submitCoachBookingBtn" class="pill primary" onclick="cdCreatePaidBooking('${venueId}',${h},this)">แนบสลิปและส่งคำขอไปที่ Coach</button></div>`}catch(e){target.innerHTML=`<div class="error">${esc(e.message||'ไม่สามารถโหลด QR ได้')}</div>`}
}
const _cdCreatePaidBooking392=cdCreatePaidBooking;
cdCreatePaidBooking=async function(venueId,h,btn){
 if(btn)btn.disabled=true;try{let slip=await s38ReadFile(document.getElementById('cdPreSlip')),participants=Math.max(1,Number(document.getElementById('cdParticipants')?.value||1));const coachId=String(state.coachId||''),athleteId=state.user.uid,date=String(state.selectedCell?.date||state.selectedDate),court=venueId==='other'?(chosenOther?.name||'สนามอื่น'):(venueName(venueId)||'สนามที่เลือก'),dd=date.slice(-2),hh=String(Math.floor(h)).padStart(2,'0'),suffix=Math.random().toString(36).slice(2,6).toUpperCase(),id=`${dd}${hh}${suffix}`;let us=(await db.ref(`users/${athleteId}`).once('value')).val()||{},phone=us.phone||'';if(!phone){phone=(prompt('กรุณาระบุเบอร์โทรศัพท์')||'').trim();if(!phone)throw new Error('กรุณาระบุเบอร์โทรศัพท์');await db.ref(`users/${athleteId}`).update({phone})}let booking=cleanFirebaseObject({coachId,athleteId,athlete:us.displayName||state.user.email||'Athlete',athleteEmail:state.user.email||'',phone,date,start:Number(h),end:Number(h)+1,venueId,venue:court,status:'payment_submitted',approvalStatus:'pending',paymentStatus:'payment_submitted',courtConfirmed:true,courtConfirmedByAthleteAt:firebase.database.ServerValue.TIMESTAMP,paymentProofDataUrl:slip,paymentSubmittedAt:firebase.database.ServerValue.TIMESTAMP,participants,pricePerPersonSatang:Number(state.pricing?.p60||0),priceSatang:Number(state.pricing?.p60||0),travelFeeSatang:0,platformFeeSatang:0,createdAt:firebase.database.ServerValue.TIMESTAMP});await db.ref(`bookings/${id}`).set(booking);let notifKey=db.ref(`notifications/${coachId}`).push().key;await db.ref(`notifications/${coachId}/${notifKey}`).set({type:'new_paid_booking',bookingId:id,senderId:athleteId,message:`มีคำขอจองใหม่ ${id} พร้อมสลิป กรุณาตรวจสอบและยืนยัน`,createdAt:firebase.database.ServerValue.TIMESTAMP,read:false});try{await audit('paid_booking_submitted',id,{coachId,date,start:h,participants})}catch(ae){console.warn('audit log skipped',ae)}closeSheet();state.selectedCell=null;setTimeout(()=>showAthleteMenu('mybookings'),50)}catch(e){alert(e.message||'ส่งคำขอไม่สำเร็จ');if(btn)btn.disabled=false}
}
function cd392CoachName(uid){let c=cdCoachByUid(uid);return c.displayName||c.nameTh||c.nameEn||c.coachDiId||'Coach'}
renderAthleteBookings=function(){
 const mine=state.bookings.filter(b=>b.athleteId===state.user?.uid).sort((a,b)=>String(a.date).localeCompare(String(b.date))||Number(a.start)-Number(b.start));if(!mine.length){athleteBookings.innerHTML='<div class="muted">ยังไม่มีการจอง</div>';return}
 let first=mine.find(b=>b.date>=TODAY)?.date||mine[0].date,start=first,days=Array.from({length:5},(_,i)=>isoAdd(start,i)),minH=Math.min(6,...mine.map(b=>Number(b.start))),maxH=Math.max(22,...mine.map(b=>Number(b.end))),hours=Array.from({length:maxH-minH},(_,i)=>minH+i);
 athleteBookings.innerHTML=`<div style="display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:12px"><div><b>ตารางการจองของฉัน</b><div class="small muted">เวลาอยู่ด้านซ้าย • คอลัมน์เป็นวันที่</div></div></div><div class="athleteCalendarWrap"><table class="athleteCalendar"><thead><tr><th class="calTime">เวลา</th>${days.map(d=>`<th>${shortThaiDate(d)}</th>`).join('')}</tr></thead><tbody>${hours.map(h=>`<tr><td class="calTime">${fmt(h)}</td>${days.map(d=>{let b=mine.find(x=>x.date===d&&Number(x.start)<=h&&Number(x.end)>h);return `<td>${b?`<div class="athleteBookingCell"><b>${esc(cd392CoachName(b.coachId))}</b>${esc(b.venue||'')}<br><span>${fmt(b.start)}–${fmt(b.end)}</span><br><span>${esc(b.status||'')}</span><br><button class="pill" style="min-height:32px;margin-top:5px" onclick="cdOpenChat('${esc(b.id)}')">💬 แชท</button></div>`:''}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>`
}
