/* Coach Di Sprint 4.0 — final override layer */
state.allAthleteBookings=state.allAthleteBookings||[];state.userProfile=state.userProfile||{};state.s40NotifCount=0;let s40ChatBookingId=null,s40ChatRef=null,s40ChatCb=null;
function s40CoachName(b){if(!b)return 'Coach';const c=(state.coaches||[]).find(x=>x.uid===b.coachId);return b.coachName||b.coachDisplayName||c?.displayName||c?.nameTh||c?.nameEn||c?.coachDiId||'Coach'}
function s40CoachPhoto(b){const c=(state.coaches||[]).find(x=>x.uid===b.coachId);return c?.photoDataUrl||c?.photoURL||c?.photoUrl||c?.photo||''}
function s40MyBookings(){return state.role==='athlete'?(state.allAthleteBookings||[]):((state.bookings||[]).filter(b=>b.coachId===state.user?.uid))}
function s40StatusLabel(s){return ({payment_submitted:'รอ Coach ตรวจสอบ',pending_coach_approval:'รอ Coach อนุมัติ',confirmed:'ยืนยันแล้ว',completed:'สอนเสร็จแล้ว',cancelled:'ยกเลิก',rejected_by_coach:'Coach ปฏิเสธ'})[s]||s||'-'}
function s40DateTime(b){return `${b.date||'-'} • ${b.start!=null?fmt(b.start):'-'}–${b.end!=null?fmt(b.end):'-'}`}
function s40Avatar(name,src){return src?`<img class="s40Avatar" src="${esc(src)}" alt="${esc(name)}">`:`<div class="s40Avatar">${esc((name||'?').slice(0,1))}</div>`}

/* Keep athlete's own bookings independent from selected coach schedule. */
function s40BindOwnBookings(){if(state.role!=='athlete'||!state.user?.uid)return;db.ref('bookings').orderByChild('athleteId').equalTo(state.user.uid).on('value',snap=>{state.allAthleteBookings=Object.entries(snap.val()||{}).map(([id,b])=>({id,...b}));if(document.getElementById('s40AthleteDynamic'))s40RenderCurrentAthleteDynamic()})}
function s40BindUserProfile(){const uid=state.user?.uid;if(!uid)return;db.ref(`users/${uid}`).on('value',s=>{if(state.user?.uid!==uid)return;state.userProfile=s.val()||{};state.userDisplayName=state.userProfile.displayName||state.userDisplayName||'';window.CoachDiProfileHistory?.mount()})}
auth.onAuthStateChanged(u=>{if(u)setTimeout(()=>{s40BindOwnBookings();s40BindUserProfile();s40BindNotifications();s40ApplySubscriptionLock()},900)})

/* Athlete + Coach navigation: remove duplicate booking/court sidebar entries; add chat/notifications. */
const s40RenderNavBase=renderNav;renderNav=function(){
 if(state.role==='athlete'){
   sidebar.className='sidebar athleteSidebar';const items=[['home','หน้าหลัก','⌂'],['mybookings','การจองของฉัน','☑'],['history','ประวัติการจอง','◷'],['notifications','แจ้งเตือน','◉'],['chat','Chat','💬'],['profile','โปรไฟล์','●']];
   sidebar.innerHTML=`<div class="sideBrand"><span class="sideMark">Di</span><span>Coach Di</span></div>`+items.map(x=>`<button class="navbtn ${x[0]==='notifications'?'s40NotifBell':''}" data-athlete-page="${x[0]}" onclick="showAthleteMenu('${x[0]}')"><span class="navIcon">${x[2]}</span>${x[1]}${x[0]==='notifications'?'<span id="s40SideNotif"></span>':''}</button>`).join('')+`<div class="sideDivider"></div><button class="navbtn sideLogout" onclick="logout()"><span class="navIcon">↪</span>ออกจากระบบ</button>`;
   mobileNav.className='mobileNav athleteMobile';mobileNav.innerHTML=items.slice(0,5).map(x=>`<button data-athlete-mobile="${x[0]}" onclick="showAthleteMenu('${x[0]}')">${x[2]}<br>${x[1]}</button>`).join('');s40PaintNotifBadge();return;
 }
 if(state.role==='coach'){
   s40RenderNavBase();const side=document.getElementById('sidebar'),logout=[...side.querySelectorAll('.navbtn')].find(b=>(b.textContent||'').includes('ออกจากระบบ'));if(side&&!side.querySelector('[data-page="chat"]')){const b=document.createElement('button');b.className='navbtn';b.dataset.page='chat';b.onclick=s40ShowChat;b.innerHTML='<span>💬</span>แชท';side.insertBefore(b,logout||null)}
   if(side&&!side.querySelector('[data-page="notifications"]')){const b=document.createElement('button');b.className='navbtn s40NotifBell';b.dataset.page='notifications';b.onclick=s40ShowNotifications;b.innerHTML='<span>◉</span>แจ้งเตือน<span id="s40SideNotif"></span>';side.insertBefore(b,logout||null)}s40PaintNotifBadge();return;
 }
 s40RenderNavBase();
}

/* Athlete dynamic pages without destroying booking-home flow. */
const s40ShowAthleteMenuBase=showAthleteMenu;showAthleteMenu=function(page){
 if(['home','coach','court'].includes(page)){document.getElementById('s40AthleteDynamic')?.remove();return s40ShowAthleteMenuBase(page)}
 setAthleteNavActive(page);athletePage.classList.remove('hidden');coachPage.classList.add('hidden');Array.from(athletePage.children).forEach(x=>x.style.display='none');let dyn=document.getElementById('s40AthleteDynamic');if(!dyn){dyn=document.createElement('div');dyn.id='s40AthleteDynamic';athletePage.appendChild(dyn)}dyn.style.display='block';dyn.dataset.page=page;s40RenderCurrentAthleteDynamic();
}
function s40RenderCurrentAthleteDynamic(){const el=document.getElementById('s40AthleteDynamic');if(!el)return;const page=el.dataset.page;if(page==='mybookings')el.innerHTML=s40MyBookingsView();else if(page==='history')el.innerHTML=s40HistoryView();else if(page==='notifications'){el.innerHTML=s40NotificationsView();s40MarkNotificationsRead()}else if(page==='chat'){setTimeout(s40RenderChat,0);el.innerHTML='<div id="s40ChatHost"></div>'}else if(page==='profile')el.innerHTML=athleteProfileView();}

function s40Upcoming(){return (state.allAthleteBookings||[]).filter(b=>b.date>=TODAY&&!['cancelled','rejected_by_coach'].includes(b.status)).sort((a,b)=>String(a.date).localeCompare(String(b.date))||Number(a.start)-Number(b.start))}
function s40MyBookingsView(){const mine=s40Upcoming();const sel=mine[0];let first=mine[0]?.date||TODAY,days=Array.from({length:5},(_,i)=>isoAdd(first,i)),minH=mine.length?Math.min(6,...mine.map(b=>Number(b.start||6))):6,maxH=mine.length?Math.max(22,...mine.map(b=>Number(b.end||22))):22,hours=Array.from({length:maxH-minH},(_,i)=>minH+i);
 return `<div class="s40AthletePanel"><h1 class="pageTitle">การจองของฉัน</h1><p class="muted">รายการที่กำลังจะมาถึงและตารางรวมของคุณ</p>${mine.length?`<label class="label">เลือก Booking</label><select class="field s40BookingSelect" onchange="s40SelectTicket(this.value)">${mine.map((b,i)=>`<option value="${esc(b.id)}">${esc(s40CoachName(b))} • ${esc(b.date)} ${fmt(b.start)} • ${esc(b.venue||'')}</option>`).join('')}</select><div id="s40SelectedTicket">${s40BookingTicket(sel)}</div>`:'<div class="card muted">ยังไม่มี Booking ที่กำลังจะมาถึง</div>'}<div class="card"><div class="s40SectionHead"><h3>ตารางการจอง</h3><span class="small muted">เวลาอยู่ด้านซ้าย • วันที่อยู่ด้านบน</span></div><div class="athleteCalendarWrap"><table class="athleteCalendar"><thead><tr><th class="calTime">เวลา</th>${days.map(d=>`<th>${shortThaiDate(d)}</th>`).join('')}</tr></thead><tbody>${hours.map(h=>`<tr><td class="calTime">${fmt(h)}</td>${days.map(d=>{const b=mine.find(x=>x.date===d&&Number(x.start)<=h&&Number(x.end)>h);return `<td>${b?`<div class="athleteBookingCell"><b>${esc(s40CoachName(b))}</b>${esc(b.venue||'')}<br>${fmt(b.start)}–${fmt(b.end)}<br>${esc(s40StatusLabel(b.status))}</div>`:''}</td>`}).join('')}</tr>`).join('')}</tbody></table></div></div></div>`}
function s40BookingTicket(b){if(!b)return '';return `<div class="card s40BookingHero"><div><span class="s40CoachPill">Coach • ${esc(s40CoachName(b))}</span><div class="coach" style="margin-top:8px">${esc(s40CoachName(b))}</div><div>${esc(s40DateTime(b))}</div><div>${esc(b.venue||'ไม่ระบุสนาม')}</div><div class="small muted" style="margin-top:6px">Booking ID ${esc(b.id||'')} • ${esc(s40StatusLabel(b.status))}</div></div><div><button class="pill primary" onclick="c56OpenUserChat('${esc(b.coachId)}','${esc(b.athleteId)}')">💬 Chat กับ Coach</button></div></div>`}
function s40SelectTicket(id){const b=s40Upcoming().find(x=>x.id===id),el=document.getElementById('s40SelectedTicket');if(el)el.innerHTML=s40BookingTicket(b)}
function s40HistoryView(){const rows=(state.allAthleteBookings||[]).filter(b=>b.date<TODAY).sort((a,b)=>String(b.date).localeCompare(String(a.date))),g={};rows.forEach(b=>{const k=(b.date||'').slice(0,7)||'unknown';(g[k]||(g[k]=[])).push(b)});return `<h1 class="pageTitle">ประวัติการจอง</h1><div class="notice">ประวัติที่ผ่านมาแสดงเป็นสีเทาจาง และระบบจะเก็บไว้ 30 วันก่อนลบตามนโยบาย UAT</div>${Object.keys(g).sort().reverse().map((k,i)=>{const label=k==='unknown'?'ไม่ระบุเดือน':new Date(k+'-01T12:00:00').toLocaleDateString('th-TH',{month:'long',year:'numeric'});return `<details class="s40HistoryMonth" ${i===0?'open':''}><summary><span>${label}</span><span class="small">${g[k].length} Booking</span></summary>${g[k].map(b=>`<div class="s40HistoryTicket"><div class="coach">${esc(s40CoachName(b))}</div><div>${esc(s40DateTime(b))}</div><div>${esc(b.venue||'ไม่ระบุสนาม')}</div><div class="small">Booking ID ${esc(b.id||'')} • ${esc(s40StatusLabel(b.status))}</div></div>`).join('')}</details>`}).join('')||'<div class="card muted">ยังไม่มีประวัติการจอง</div>'}`}

/* Notifications with visible unread badge. */
function s40BindNotifications(){if(!state.user?.uid)return;db.ref(`notifications/${state.user.uid}`).on('value',s=>{state.notifications=Object.entries(s.val()||{}).map(([id,n])=>({id,...n})).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));state.s40NotifCount=state.notifications.filter(n=>!n.read).length;s40PaintNotifBadge();const d=document.getElementById('s40AthleteDynamic');if(d?.dataset.page==='notifications')d.innerHTML=s40NotificationsView()})}
function s40PaintNotifBadge(){document.querySelectorAll('#s40SideNotif').forEach(h=>h.innerHTML=state.s40NotifCount?`<span class="s40NotifBadge">${state.s40NotifCount}</span>`:'')}
function s40NotificationsView(){return `<h1 class="pageTitle">แจ้งเตือน</h1><div class="s40NotifList">${(state.notifications||[]).map(n=>`<div class="s40NotifItem ${n.read?'':'unread'}"><b>${n.type==='booking_confirmed'?'Booking Confirmed':n.type==='chat_message'?'ข้อความใหม่':'Coach Di'}</b><div>${esc(n.message||'')}</div><div class="small muted">${n.createdAt?new Date(n.createdAt).toLocaleString('th-TH'):''}</div></div>`).join('')||'<div class="card muted">ยังไม่มีการแจ้งเตือน</div>'}</div>`}
async function s40MarkNotificationsRead(){const up={};(state.notifications||[]).filter(n=>!n.read).forEach(n=>up[`notifications/${state.user.uid}/${n.id}/read`]=true);if(Object.keys(up).length)try{await db.ref().update(up)}catch(e){}}
function s40ShowNotifications(){coachContent.innerHTML=s40NotificationsView();s40MarkNotificationsRead()}

/* Unified realtime chat: all athlete bookings, coach own bookings; photo support + notification. */
function s40ChatBookings(){return s40MyBookings().slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))}
function s40OtherName(b){return state.role==='coach'?(b.athlete||b.athleteName||'นักกีฬา'):s40CoachName(b)}
function s40OtherPhoto(b){return state.role==='coach'?(b.athletePhoto||''):s40CoachPhoto(b)}
function s40ShowChat(){showCoach('dashboard');coachContent.innerHTML='<div id="s40ChatHost"></div>';s40RenderChat()}
function s40RenderChat(){const host=document.getElementById('s40ChatHost')||document.getElementById('s40AthleteDynamic');if(!host)return;const rows=s40ChatBookings();if(!s40ChatBookingId&&rows[0])s40ChatBookingId=rows[0].id;host.innerHTML=`<h1 class="pageTitle">แชท</h1><p class="muted">ข้อความระหว่างนักกีฬาและ Coach รวมไว้ที่เดียวและอัปเดตแบบ realtime</p><div class="s40ChatShell"><div class="s40ChatList"><div class="s40ChatHead"><h2>Messages</h2><input id="s40ChatSearch" class="s40ChatSearch" placeholder="ค้นหาชื่อ" oninput="s40RenderChatList()"></div><div id="s40ChatListBody"></div></div><div id="s40ChatPane" class="s40ChatPane"></div></div>`;s40RenderChatList();s40BindThread()}
function s40RenderChatList(){const el=document.getElementById('s40ChatListBody');if(!el)return;const q=(document.getElementById('s40ChatSearch')?.value||'').toLowerCase();el.innerHTML=s40ChatBookings().filter(b=>s40OtherName(b).toLowerCase().includes(q)).map(b=>`<div class="s40Conversation ${b.id===s40ChatBookingId?'active':''}" onclick="s40OpenThread('${esc(b.id)}')">${s40Avatar(s40OtherName(b),s40OtherPhoto(b))}<div><div class="name">${esc(s40OtherName(b))}</div><div class="preview">${esc(b.venue||'')} • ${esc(b.date||'')}</div></div><div class="small muted">${b.start!=null?fmt(b.start):''}</div></div>`).join('')||'<div class="muted" style="padding:18px">ยังไม่มีบทสนทนา</div>'}
function s40OpenThread(id){s40ChatBookingId=id;s40RenderChatList();s40BindThread()}
function s40BindThread(){if(s40ChatRef&&s40ChatCb){try{s40ChatRef.off('value',s40ChatCb)}catch(e){}}const pane=document.getElementById('s40ChatPane'),b=s40ChatBookings().find(x=>x.id===s40ChatBookingId);if(!pane)return;if(!b){pane.innerHTML='<div class="cdChatEmpty">เลือกบทสนทนา</div>';return}const name=s40OtherName(b);pane.innerHTML=`<div class="s40ThreadHead">${s40Avatar(name,s40OtherPhoto(b))}<div><b>${esc(name)}</b><div class="small muted">${esc(b.venue||'')} • ${esc(s40DateTime(b))}</div></div></div><div id="s40ThreadMsgs" class="s40ThreadMsgs"></div><div class="s40Composer"><input id="s40ChatInput" placeholder="พิมพ์ข้อความ..." onkeydown="if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();s40SendMessage()}"><button class="s40Send" onclick="s40SendMessage()">➤</button></div>`;s40ChatRef=db.ref(`bookingChats/${b.id}/messages`).limitToLast(200);s40ChatCb=s=>{const el=document.getElementById('s40ThreadMsgs');if(!el)return;const ms=Object.values(s.val()||{}).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));el.innerHTML=ms.map(m=>`<div class="s40Msg ${m.senderId===state.user.uid?'me':'them'}"><div class="s40Bubble">${esc(m.text||'')}<div class="s40MsgTime">${m.createdAt?new Date(m.createdAt).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}):''}</div></div></div>`).join('')||'<div class="cdChatEmpty">เริ่มต้นบทสนทนาได้เลย</div>';el.scrollTop=el.scrollHeight};s40ChatRef.on('value',s40ChatCb)}
async function s40SendMessage(){const i=document.getElementById('s40ChatInput'),text=(i?.value||'').trim(),b=s40ChatBookings().find(x=>x.id===s40ChatBookingId);if(!text||!b)return;const receiver=state.user.uid===b.coachId?b.athleteId:b.coachId,mid=db.ref(`bookingChats/${b.id}/messages`).push().key,nid=db.ref(`notifications/${receiver}`).push().key,up={};up[`bookingChats/${b.id}/messages/${mid}`]={senderId:state.user.uid,senderRole:state.role,text,createdAt:firebase.database.ServerValue.TIMESTAMP};up[`notifications/${receiver}/${nid}`]={type:'chat_message',bookingId:b.id,senderId:state.user.uid,message:`มีข้อความใหม่จาก ${state.userDisplayName||state.coachProfile?.displayName||'Coach Di'}`,read:false,createdAt:firebase.database.ServerValue.TIMESTAMP};try{await db.ref().update(up);i.value=''}catch(e){alert('ส่งข้อความไม่สำเร็จ: '+(e?.message||e))}}
try{cd396OpenChat=function(id){s40ChatBookingId=id;state.role==='athlete'?showAthleteMenu('chat'):s40ShowChat()}}catch(e){}
try{cd398ChatPage=s40RenderChat}catch(e){}

/* New Booking tickets on coach dashboard + canonical confirmation with coach name and slip deletion. */
function s40NewBookings(){return (state.bookings||[]).filter(b=>b.coachId===state.user?.uid&&['payment_submitted','pending_coach_approval','pending'].includes(b.status)).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))}
function s40NewBookingPanel(){const rows=s40NewBookings();return `<div class="card"><div class="s40SectionHead"><h3>New Booking</h3>${rows.length?`<span class="s40Count">${rows.length}</span>`:'<span class="small muted">ไม่มีคำขอใหม่</span>'}</div>${rows.length?`<div class="s40NewGrid">${rows.map(b=>`<div class="s40NewTicket"><span class="s40BadgeNew">NEW BOOKING</span><div class="s40TicketName">${esc(b.athlete||b.athleteName||'นักกีฬา')}</div><div class="small muted">Booking ID ${esc(b.id||'')}</div><div class="s40TicketMeta"><span>วันและเวลา<b>${esc(s40DateTime(b))}</b></span><span>สนาม<b>${esc(b.venue||'-')}</b></span><span>ผู้เรียน<b>${Number(b.participants||1)} คน</b></span><span>ยอดที่แจ้ง<b>${baht(Number(b.priceSatang||0)+Number(b.travelFeeSatang||0))}</b></span></div><div class="s40Actions"><button class="pill primary" onclick="s40ConfirmBooking('${esc(b.id)}')">ยืนยันรับเงิน</button><button class="pill" onclick="csDetail('${esc(b.id)}')">รายละเอียด</button><button class="pill" onclick="s40ChatBookingId='${esc(b.id)}';s40ShowChat()">💬 แชท</button></div></div>`).join('')}</div>`:''}</div>`}
const s40CoachDashboardBase=coachDashboard;coachDashboard=function(){const base=s40CoachDashboardBase();return `<h1 class="pageTitle">Dashboard</h1>${s40NewBookingPanel()}`+base.replace('<h1 class="pageTitle">Dashboard</h1>','')}
async function s40ConfirmBooking(id){const b=(state.bookings||[]).find(x=>x.id===id);if(!b||b.coachId!==state.user.uid)return alert('ไม่พบ Booking');if(!b.paymentProofDataUrl)return alert('ไม่พบสลิปสำหรับ Booking นี้');if(!confirm(`ยืนยันว่าได้รับเงิน Booking ${id} แล้ว?`))return;const coachName=(state.coachProfile?.displayName||state.coachProfile?.nameTh||state.userDisplayName||'Coach').trim(),gross=Number(b.priceSatang||0)+Number(b.travelFeeSatang||0),fee=Number(b.platformFeeSatang||0);try{const up={};up[`bookings/${id}/paymentStatus`]='payment_verified';up[`bookings/${id}/status`]='confirmed';up[`bookings/${id}/verifiedAt`]=firebase.database.ServerValue.TIMESTAMP;up[`bookings/${id}/verifiedBy`]=state.user.uid;up[`bookings/${id}/coachName`]=coachName;up[`bookings/${id}/coachDisplayName`]=coachName;up[`bookings/${id}/paymentProofDataUrl`]=null;up[`bookings/${id}/paymentProofDeletedAt`]=firebase.database.ServerValue.TIMESTAMP;up[`paymentTransactions/TX-${id}`]={bookingId:id,coachId:b.coachId,athleteId:b.athleteId,grossSatang:gross,platformFeeSatang:fee,netSatang:gross-fee,status:'received',receivedAt:firebase.database.ServerValue.TIMESTAMP};const nid=db.ref(`notifications/${b.athleteId}`).push().key;up[`notifications/${b.athleteId}/${nid}`]={type:'booking_confirmed',bookingId:id,senderId:state.user.uid,message:`${coachName} ยืนยัน Booking ${id} แล้ว`,read:false,createdAt:firebase.database.ServerValue.TIMESTAMP};await db.ref().update(up);b.status='confirmed';b.paymentStatus='payment_verified';b.coachName=coachName;b.coachDisplayName=coachName;b.paymentProofDataUrl=null;alert('ยืนยันรับเงินและ Booking เรียบร้อย • สลิปถูกลบแล้ว');showCoach('dashboard')}catch(e){alert('ยืนยันไม่สำเร็จ: '+(e?.message||e))}}
verifyPayment=s40ConfirmBooking;

/* Profile photo consistency: athlete discovery uses the latest photoDataUrl too. */
const s40DiscoveryBase=renderCoachDiscovery;renderCoachDiscovery=function(){s40DiscoveryBase();document.querySelectorAll('#coachCards .coachCard').forEach(card=>{const m=(card.getAttribute('onclick')||'').match(/'([^']+)'/),c=m&&(state.coaches||[]).find(x=>x.uid===m[1]);if(c?.photoDataUrl){let img=card.querySelector('img.coachAvatar');if(img)img.src=c.photoDataUrl;else{let av=card.querySelector('.coachAvatar');if(av){const ni=document.createElement('img');ni.className='coachAvatar';ni.src=c.photoDataUrl;ni.alt=c.displayName||'Coach';av.replaceWith(ni)}}}})}

/* Subscription QA fix: canonical source is users/{coachUid}/subscription (timestamps), not coachSubscriptions. */
function s40SubDue(sub){const end=Number(sub?.currentPeriodEndsAt||sub?.trialEndsAt||0);if(!end)return {days:null,locked:false};const days=Math.ceil((end-Date.now())/86400000);return {days,locked:days<-7,end}}
async function s40ApplySubscriptionLock(){if(state.role!=='coach'||!state.user?.uid)return;try{const sub=(await db.ref(`users/${state.user.uid}/subscription`).once('value')).val()||{},ss=s40SubDue(sub);state.subscriptionLocked=ss.locked;if(!ss.locked)return;document.querySelectorAll('.sidebar .navbtn').forEach(b=>{const t=(b.textContent||'').toLowerCase();const allowed=t.includes('ชำระ')||t.includes('subscription')||t.includes('ออกจากระบบ');if(!allowed){b.style.opacity='.35';b.style.pointerEvents='none'}});const main=document.getElementById('coachContent');if(main&&!document.getElementById('s40Lock'))main.insertAdjacentHTML('afterbegin','<div id="s40Lock" class="s40Lock"><b>บัญชีถูกจำกัดสิทธิ์ชั่วคราว</b><br>Subscription เกินกำหนดมากกว่า 7 วัน กรุณาชำระและรอ Admin Activate</div>')}catch(e){console.warn('subscription lock',e)}}
function s40MtdStart(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`}
async function s40AdminSubLoad(){const host=document.getElementById('s40AdminSubBody');if(!host)return;try{const [us,ts]=await Promise.all([db.ref('users').once('value'),db.ref('subscriptionTransactions').once('value')]),users=us.val()||{},tx=Object.entries(ts.val()||{}).map(([id,v])=>({id,...v})),start=document.getElementById('s40AdminSubStart')?.value||s40MtdStart(),end=document.getElementById('s40AdminSubEnd')?.value||TODAY;const coachUsers=Object.entries(users).filter(([uid,u])=>u.role==='coach'),warnings=coachUsers.map(([uid,u])=>({uid,u,ss:s40SubDue(u.subscription)})).filter(x=>x.ss.days!==null&&x.ss.days<=3).sort((a,b)=>a.ss.days-b.ss.days);const f=tx.filter(t=>{const ms=Number(t.createdAt||t.activatedAt||0);const d=ms?new Date(ms).toISOString().slice(0,10):(t.date||'');return d>=start&&d<=end&&['paid','active','verified'].includes(t.status||t.paymentStatus||'paid')});const revenue=f.reduce((a,t)=>a+Number(t.amountSatang||t.amount||0),0);host.innerHTML=`<div class="grid g3"><div class="metric">Subscription Revenue<b>${baht(revenue)}</b></div><div class="metric">Payments<b>${f.length}</b></div><div class="metric">ใกล้/เกินกำหนด<b>${warnings.length}</b></div></div><div style="margin-top:12px">${warnings.map(x=>`<div class="s40Warning ${x.ss.locked?'s40Critical':''}"><b>${esc(x.u.displayName||x.u.email||x.uid)}</b> • ${x.ss.days>=0?`ครบกำหนดใน ${x.ss.days} วัน`:`เกินกำหนด ${Math.abs(x.ss.days)} วัน`}${x.ss.locked?' • จำกัดสิทธิ์แล้ว':''}</div>`).join('')||'<div class="muted">ไม่มี Coach ใกล้ครบกำหนด</div>'}</div>`}catch(e){host.textContent='โหลด Subscription ไม่สำเร็จ: '+e.message}}
function s40AdminSubCard(){setTimeout(s40AdminSubLoad,50);return `<div class="card s40AdminSub"><div class="s40SectionHead"><h3>Subscription Revenue</h3><span class="small muted">Default MTD</span></div><div class="cdDashboardFilter"><label>จากวันที่<input id="s40AdminSubStart" type="date" value="${s40MtdStart()}"></label><label>ถึงวันที่<input id="s40AdminSubEnd" type="date" value="${TODAY}"></label><button class="pill primary" onclick="s40AdminSubLoad()">ดูช่วงวันที่</button></div><div id="s40AdminSubBody"></div></div>`}
const s40AdminDashboardBase=adminDashboard;adminDashboard=function(){return s40AdminDashboardBase()+s40AdminSubCard()+`<div class="card"><div class="s40SectionHead"><h3>Export ประวัติผู้ใช้งาน</h3></div><div class="s40ExportRow"><button class="pill" onclick="s40ExportUsers('coach')">Export Coach CSV</button><button class="pill" onclick="s40ExportUsers('athlete')">Export Athlete CSV</button></div></div>`}
async function s40ExportUsers(role){try{const s=await db.ref('users').once('value'),rows=Object.entries(s.val()||{}).filter(([uid,u])=>u.role===role).map(([uid,u])=>({uid,displayName:u.displayName||'',email:u.email||'',phone:u.phone||'',status:u.status||'',role:u.role||'',createdAt:u.createdAt||''}));if(!rows.length)return alert('ไม่มีข้อมูล');const heads=Object.keys(rows[0]),q=v=>'"'+String(v??'').replaceAll('"','""')+'"',csv='\\ufeff'+[heads.map(q).join(','),...rows.map(r=>heads.map(h=>q(r[h])).join(','))].join('\\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${role}-history-${TODAY}.csv`;a.click();URL.revokeObjectURL(url)}catch(e){alert('Export ไม่สำเร็จ: '+e.message)}}

/* After each main render, ensure subscription lock is re-applied. */
const s40ShowCoachBase=showCoach;showCoach=function(page){if(state.subscriptionLocked && !['payments','settings'].includes(page)){page='payments'}s40ShowCoachBase(page);setTimeout(s40ApplySubscriptionLock,30)}
