/* Coach Di Sprint 4.1 — VISDA-inspired coach tickets, Manage Customer, LINE-like athlete chat */

/* ---------- Coach New Booking ticket ---------- */
function s41NewBookingPanel(){
 const rows=s40NewBookings();
 return `<section class="s41BookingBoard"><div class="s41BoardHead"><div><h3>คำขอจองใหม่</h3><div class="small muted">ตรวจสลิปและยืนยัน Booking ได้จาก Ticket นี้</div></div>${rows.length?`<span class="s41Count">${rows.length} NEW</span>`:'<span class="small muted">ไม่มีคำขอใหม่</span>'}</div>${rows.map(b=>{
   const total=Number(b.priceSatang||0)+Number(b.travelFeeSatang||0);
   return `<article class="s41BookingTicket">
    <div class="s41TicketTop"><div><div class="s41TicketId">Booking #${esc(b.id||'-')} <span class="s41StatusNew">NEW</span></div><div class="s41Athlete">ผู้จอง: ${esc(b.athlete||b.athleteName||'นักกีฬา')} ${b.phone?`• ${esc(b.phone)}`:''}</div></div><div class="s41Amount"><small>ยอดชำระ</small><b>${baht(total)}</b></div></div>
    <div class="s41TicketBody"><div class="s41InfoBox"><span>วันและเวลา</span><b>${esc(s40DateTime(b))}</b></div><div class="s41InfoBox"><span>สนาม</span><b>${esc(b.venue||'ไม่ระบุสนาม')}</b></div></div>
    <div class="s41SlipRow"><div><b>สลิปชำระเงิน</b><div class="s41SlipState">${b.paymentProofDataUrl?'● แนบแล้ว • รอตรวจสอบ':'ยังไม่มีสลิป'}</div></div><button class="pill" ${b.paymentProofDataUrl?`onclick="s41ViewSlip('${esc(b.id)}')"`:'disabled'}>ดูสลิป</button></div>
    <div class="s41TicketActions"><button class="pill s41Approve" onclick="s40ConfirmBooking('${esc(b.id)}')">✓ ยืนยันรับเงิน</button><button class="pill s41Reject" onclick="s41RejectBooking('${esc(b.id)}')">✕ ปฏิเสธ</button><button class="pill" onclick="csDetail('${esc(b.id)}')">รายละเอียด</button></div>
   </article>`}).join('')}</section>`
}
function s41ViewSlip(id){const b=(state.bookings||[]).find(x=>x.id===id);if(!b?.paymentProofDataUrl)return alert('ไม่พบสลิป');csModal(`<button class="csSheetClose" onclick="csCloseModal()">✕</button><h2>สลิป • ${esc(id)}</h2><img src="${b.paymentProofDataUrl}" style="display:block;max-width:100%;max-height:70vh;margin:auto;border-radius:16px">`)}
async function s41RejectBooking(id){const b=(state.bookings||[]).find(x=>x.id===id);if(!b)return;const reason=prompt('เหตุผลที่ปฏิเสธ Booking')||'Coach ไม่สามารถรับ Booking นี้ได้';if(!confirm('ยืนยันปฏิเสธ Booking นี้?'))return;try{const nid=db.ref(`notifications/${b.athleteId}`).push().key,up={};up[`bookings/${id}/status`]='rejected_by_coach';up[`bookings/${id}/rejectReason`]=reason;up[`bookings/${id}/rejectedAt`]=firebase.database.ServerValue.TIMESTAMP;up[`notifications/${b.athleteId}/${nid}`]={type:'booking_rejected',bookingId:id,senderId:state.user.uid,message:`Coach ปฏิเสธ Booking ${id}: ${reason}`,read:false,createdAt:firebase.database.ServerValue.TIMESTAMP};await db.ref().update(up);showCoach('dashboard')}catch(e){alert('ปฏิเสธไม่สำเร็จ: '+e.message)}}
const s41CoachDashboardBase=coachDashboard;coachDashboard=function(){const base=s41CoachDashboardBase();return base.replace(/<section class="s41BookingBoard"[\s\S]*?<\/section>/,'').replace(/<div class="card"><div class="s40SectionHead"><h3>New Booking<\/h3>[\s\S]*?<\/div><\/div>/,'').replace('<h1 class="pageTitle">Dashboard</h1>',`<h1 class="pageTitle">Dashboard</h1>${s41NewBookingPanel()}`)}

/* ---------- Admin navigation + Manage Customer ---------- */
const s41RenderNavBase=renderNav;renderNav=function(){
 if(state.role!=='admin')return s41RenderNavBase();
 sidebar.className='sidebar';const items=[['overview','Dashboard','⌂'],['verify','Verify Coach','✓'],['customers','Manage Customer','♙'],['support','Messages','💬']];
 sidebar.innerHTML=items.map((x,i)=>`<button class="navbtn ${i===0?'active':''}" data-admin-page="${x[0]}" onclick="s41ShowAdmin('${x[0]}')"><span>${x[2]}</span>${x[1]}</button>`).join('')+`<button class="navbtn" onclick="logout()">↪ ออกจากระบบ</button>`;
 mobileNav.className='mobileNav';mobileNav.innerHTML=items.slice(0,4).map(x=>`<button onclick="s41ShowAdmin('${x[0]}')">${x[2]}<br>${x[1]}</button>`).join('')
}
function s41SetAdminActive(page){document.querySelectorAll('[data-admin-page]').forEach(b=>b.classList.toggle('active',b.dataset.adminPage===page))}
async function s41ShowAdmin(page='overview'){
 athletePage.classList.add('hidden');coachPage.classList.remove('hidden');s41SetAdminActive(page);
 if(page==='overview'){coachContent.innerHTML=adminDashboard();setTimeout(loadAdminVerification,0);return}
 if(page==='verify'){coachContent.innerHTML=adminDashboard();setTimeout(loadAdminVerification,0);return}
 if(page==='customers'){coachContent.innerHTML=s41CustomerPage();await s41LoadCustomers();return}
 if(page==='support'){coachContent.innerHTML='<h1 class="pageTitle">Messages</h1><div id="cdAdminSupport395" class="card">กำลังโหลด...</div>';if(typeof cd395LoadAdminSupport==='function')cd395LoadAdminSupport();return}
}
function s41CustomerPage(){return `<div class="s41AdminShell"><div class="s41BoardHead"><div><h1 class="pageTitle">Manage Customer</h1><div class="muted">ดูประวัตินักกีฬาและ Coach รวมการจอง การใช้จ่าย และสถานะบัญชี</div></div><button class="pill" onclick="s41ExportCurrentCustomers()">⇩ Export</button></div><div class="s41AdminTabs"><button id="s41TabAthlete" class="s41AdminTab active" onclick="s41SetCustomerRole('athlete')">นักกีฬา</button><button id="s41TabCoach" class="s41AdminTab" onclick="s41SetCustomerRole('coach')">Coach</button></div><div class="s41CustomerTools"><input id="s41CustomerSearch" class="field" placeholder="ค้นหาชื่อ, เบอร์โทร, อีเมล..." oninput="s41RenderCustomerTable()"><select id="s41CustomerStatus" class="field" onchange="s41RenderCustomerTable()"><option value="">ทุกสถานะ</option><option value="active">Active</option><option value="suspended">Suspended</option></select><button class="pill" onclick="s41ExportCurrentCustomers()">ส่งออก CSV</button></div><div id="s41CustomerTableHost" class="s41CustomerTableWrap"></div><div id="s41CustomerDetailHost"></div></div>`}
let s41CustomerRole='athlete',s41Users={},s41AllBookings=[],s41CoachProfiles={};
async function s41LoadCustomers(){try{const [u,b,c]=await Promise.all([db.ref('users').once('value'),db.ref('bookings').once('value'),db.ref('coachProfiles').once('value')]);s41Users=u.val()||{};s41AllBookings=Object.entries(b.val()||{}).map(([id,v])=>({id,...v}));s41CoachProfiles=c.val()||{};s41RenderCustomerTable()}catch(e){document.getElementById('s41CustomerTableHost').innerHTML=`<div class="error" style="padding:16px">${esc(e.message)}</div>`}}
function s41SetCustomerRole(role){s41CustomerRole=role;document.getElementById('s41TabAthlete')?.classList.toggle('active',role==='athlete');document.getElementById('s41TabCoach')?.classList.toggle('active',role==='coach');document.getElementById('s41CustomerDetailHost').innerHTML='';s41RenderCustomerTable()}
function s41CustomerRows(){const q=(document.getElementById('s41CustomerSearch')?.value||'').trim().toLowerCase(),status=document.getElementById('s41CustomerStatus')?.value||'';return Object.entries(s41Users).filter(([uid,u])=>u.role===s41CustomerRole&&(!status||(u.status||'active')===status)).map(([uid,u])=>{const prof=s41CoachProfiles[uid]||{},name=u.displayName||prof.displayName||prof.nameTh||u.email?.split('@')[0]||'ไม่ระบุชื่อ',books=s41AllBookings.filter(b=>s41CustomerRole==='athlete'?b.athleteId===uid:b.coachId===uid),paid=books.filter(b=>['confirmed','completed'].includes(b.status)&&b.paymentStatus==='payment_verified'),spend=paid.reduce((a,b)=>a+Number(b.priceSatang||0)+Number(b.travelFeeSatang||0),0);return {uid,u,prof,name,books,paid,spend,last:books.slice().sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))[0]}}).filter(x=>!q||`${x.name} ${x.u.phone||''} ${x.u.email||''}`.toLowerCase().includes(q))}
function s41RenderCustomerTable(){const host=document.getElementById('s41CustomerTableHost');if(!host)return;const rows=s41CustomerRows();host.innerHTML=`<table class="s41CustomerTable"><thead><tr><th>ลูกค้า</th><th>บทบาท</th><th>สถานะ</th><th>Booking</th><th>${s41CustomerRole==='athlete'?'ใช้จ่ายรวม':'รายได้รวม'}</th><th>ล่าสุด</th><th></th></tr></thead><tbody>${rows.map(x=>`<tr onclick="s41OpenCustomer('${esc(x.uid)}')"><td><div class="s41Person">${s41CustomerAvatar(x)}<div><b>${esc(x.name)}</b><div class="small muted">${esc(x.u.phone||x.u.email||'')}</div></div></div></td><td>${s41CustomerRole==='athlete'?'นักกีฬา':'Coach'}</td><td><span class="${(x.u.status||'active')==='active'?'s41Active':'s41Inactive'}">${esc(x.u.status||'active')}</span></td><td>${x.books.length}</td><td>${baht(x.spend)}</td><td>${x.last?esc(x.last.date||''):'-'}</td><td>•••</td></tr>`).join('')}</tbody></table>`}
function s41CustomerAvatar(x){const photo=x.prof.photoDataUrl||x.prof.photoURL||x.u.photoDataUrl||'';return photo?`<img class="s41Avatar" src="${photo}">`:`<div class="s41Avatar">${esc((x.name||'?').slice(0,1))}</div>`}
function s41OpenCustomer(uid){const x=s41CustomerRows().find(r=>r.uid===uid);if(!x)return;const completed=x.books.filter(b=>b.status==='completed').length,cancel=x.books.filter(b=>String(b.status).includes('cancel')).length;document.getElementById('s41CustomerDetailHost').innerHTML=`<div class="s41CustomerDetail"><div class="s41CustomerCard"><div class="s41CustomerHero">${s41CustomerAvatar(x)}<div><h3 style="margin:0">${esc(x.name)}</h3><div class="muted small">${esc(x.u.phone||'')} ${x.u.email?`• ${esc(x.u.email)}`:''}</div></div><span class="${(x.u.status||'active')==='active'?'s41Active':'s41Inactive'}" style="margin-left:auto">${esc(x.u.status||'active')}</span></div><div class="s41Stats"><div class="s41Stat"><span>Booking ทั้งหมด</span><b>${x.books.length}</b></div><div class="s41Stat"><span>สำเร็จ</span><b>${completed}</b></div><div class="s41Stat"><span>ยกเลิก</span><b>${cancel}</b></div></div><h4>ประวัติการจองล่าสุด</h4>${x.books.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,20).map(b=>`<div class="s41HistoryRow"><b>${esc(b.date||'-')}</b><span>${b.start!=null?fmt(b.start):'-'}</span><span>${esc(b.venue||'-')}<br><span class="small muted">${s41CustomerRole==='athlete'?esc(s40CoachName(b)):esc(b.athlete||b.athleteName||'นักกีฬา')}</span></span><span>${esc(s40StatusLabel(b.status))}</span></div>`).join('')||'<div class="muted">ยังไม่มีประวัติ</div>'}</div><div class="s41CustomerCard"><h4 style="margin-top:0">สรุปข้อมูล</h4><p>ยอดรวม <b>${baht(x.spend)}</b></p><p>Booking ล่าสุด <b>${x.last?esc(x.last.date||'-'):'-'}</b></p><p>UID</p><div class="small muted" style="word-break:break-all">${esc(x.uid)}</div></div></div>`}
function s41ExportCurrentCustomers(){const rows=s41CustomerRows().map(x=>({uid:x.uid,name:x.name,role:s41CustomerRole,status:x.u.status||'active',phone:x.u.phone||'',email:x.u.email||'',bookings:x.books.length,totalBaht:Math.round(x.spend/100)}));if(!rows.length)return alert('ไม่มีข้อมูลสำหรับ Export');const heads=Object.keys(rows[0]),q=v=>'"'+String(v??'').replaceAll('"','""')+'"',csv='\ufeff'+[heads.map(q).join(','),...rows.map(r=>heads.map(h=>q(r[h])).join(','))].join('\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`coach-di-${s41CustomerRole}-${TODAY}.csv`;a.click();URL.revokeObjectURL(url)}

/* ---------- LINE-like athlete chat ---------- */
let s41ChatBookingId=null,s41ChatRef=null,s41ChatCb=null;
function s41ChatBookings(){return (state.allAthleteBookings||state.bookings||[]).filter(b=>b.athleteId===state.user?.uid||b.coachId===state.user?.uid).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))}
function s41OtherName(b){if(state.role==='coach')return b.athlete||b.athleteName||'นักกีฬา';return s40CoachName(b)}
function s41OtherPhoto(b){if(state.role==='coach')return b.athletePhoto||'';const c=(state.coaches||[]).find(x=>x.uid===b.coachId);return c?.photoDataUrl||c?.photoURL||''}
function s41AvatarHtml(b){const n=s41OtherName(b),p=s41OtherPhoto(b);return p?`<img class="s41Avatar" src="${p}">`:`<div class="s41Avatar">${esc((n||'?').slice(0,1))}</div>`}
function s41RenderLineChat(){const host=document.getElementById('s40ChatHost')||document.getElementById('s40AthleteDynamic');if(!host)return;const rows=s41ChatBookings();if(!s41ChatBookingId&&rows[0])s41ChatBookingId=rows[0].id;host.innerHTML=`<h1 class="pageTitle">แชท</h1><p class="muted">คุยกับ Coach แบบ realtime และรวมทุกบทสนทนาไว้ที่เดียว</p><div class="s41LineShell"><aside class="s41LineInbox"><div class="s41LineInboxHead"><h2>Chats</h2><input id="s41ChatSearch" class="s41LineSearch" placeholder="ค้นหา Coach" oninput="s41RenderChatList()"></div><div id="s41ChatList"></div></aside><section id="s41LineThread" class="s41LineThread"></section></div>`;s41RenderChatList();s41BindLineThread()}
function s41RenderChatList(){const host=document.getElementById('s41ChatList');if(!host)return;const q=(document.getElementById('s41ChatSearch')?.value||'').toLowerCase();host.innerHTML=s41ChatBookings().filter(b=>s41OtherName(b).toLowerCase().includes(q)).map(b=>`<div class="s41LineConv ${b.id===s41ChatBookingId?'active':''}" onclick="s41OpenLineThread('${esc(b.id)}')">${s41AvatarHtml(b)}<div><div class="name">${esc(s41OtherName(b))}</div><div class="preview">${esc(b.venue||'')} • ${esc(b.date||'')}</div></div><div><div class="time">${b.start!=null?fmt(b.start):''}</div></div></div>`).join('')||'<div class="muted" style="padding:18px">ยังไม่มีบทสนทนา</div>'}
function s41OpenLineThread(id){s41ChatBookingId=id;s41RenderChatList();s41BindLineThread()}
function s41BindLineThread(){if(s41ChatRef&&s41ChatCb){try{s41ChatRef.off('value',s41ChatCb)}catch(e){}}const pane=document.getElementById('s41LineThread'),b=s41ChatBookings().find(x=>x.id===s41ChatBookingId);if(!pane)return;if(!b){pane.innerHTML='<div class="cdChatEmpty">เลือกบทสนทนา</div>';return}pane.innerHTML=`<header class="s41LineHead">${s41AvatarHtml(b)}<div><div class="s41LineHeadName">${esc(s41OtherName(b))} <span style="color:#34D399">●</span></div><div class="s41LineHeadSub">${esc(b.venue||'')} • Booking ${esc(b.id||'')}</div></div><div style="margin-left:auto;font-size:20px">⋮</div></header><div id="s41LineMessages" class="s41LineMessages"><div class="s41DayChip"><span>วันนี้</span></div></div><div class="s41Composer"><button class="s41Plus" type="button">＋</button><input id="s41LineInput" placeholder="พิมพ์ข้อความ..." onkeydown="if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();s41SendLineMessage()}"><button class="s41Send" onclick="s41SendLineMessage()">➤</button></div>`;s41ChatRef=db.ref(`bookingChats/${b.id}/messages`).limitToLast(200);s41ChatCb=s=>{const el=document.getElementById('s41LineMessages');if(!el)return;const ms=Object.values(s.val()||{}).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));el.innerHTML='<div class="s41DayChip"><span>วันนี้</span></div>'+ms.map(m=>{const me=m.senderId===state.user.uid,tm=m.createdAt?new Date(m.createdAt).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'}):'';return `<div class="s41MsgRow ${me?'me':'them'}">${!me?s41AvatarHtml(b):''}<div class="s41LineBubble">${esc(m.text||'')}<div class="s41MsgMeta">${tm}${me?' • อ่านแล้ว':''}</div></div></div>`}).join('');el.scrollTop=el.scrollHeight};s41ChatRef.on('value',s41ChatCb)}
async function s41SendLineMessage(){const input=document.getElementById('s41LineInput'),text=(input?.value||'').trim(),b=s41ChatBookings().find(x=>x.id===s41ChatBookingId);if(!text||!b)return;const receiver=state.user.uid===b.coachId?b.athleteId:b.coachId,mid=db.ref(`bookingChats/${b.id}/messages`).push().key,nid=db.ref(`notifications/${receiver}`).push().key,up={};up[`bookingChats/${b.id}/messages/${mid}`]={senderId:state.user.uid,senderRole:state.role,text,createdAt:firebase.database.ServerValue.TIMESTAMP};up[`notifications/${receiver}/${nid}`]={type:'chat_message',bookingId:b.id,senderId:state.user.uid,message:`มีข้อความใหม่จาก ${state.userDisplayName||state.coachProfile?.displayName||'Coach Di'}`,read:false,createdAt:firebase.database.ServerValue.TIMESTAMP};try{await db.ref().update(up);input.value=''}catch(e){alert('ส่งข้อความไม่สำเร็จ: '+e.message)}}
const s41RenderChatBase=s40RenderChat;s40RenderChat=function(){if(state.role==='athlete')return s41RenderLineChat();return s41RenderChatBase()}
try{cd396OpenChat=function(id){s41ChatBookingId=id;s40ChatBookingId=id;state.role==='athlete'?showAthleteMenu('chat'):s40ShowChat()}}catch(e){}

/* Make admin default land on dashboard with new navigation. */
const s41ShowAdminBase=showAdmin;showAdmin=function(){s41ShowAdmin('overview')}
