function c79OpenPlayText(html){return String(html||'').replaceAll('คลาสกลุ่ม','Open Play')}
function c79TranslateOpenPlay(root){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode())if(node.nodeValue.includes('คลาสกลุ่ม'))node.nodeValue=node.nodeValue.replaceAll('คลาสกลุ่ม','Open Play')}
function c79EnsureCoachOpenPlayEntry(){if(state.role!=='coach')return;let fab=document.getElementById('c79MobileOpenPlay');if(!fab){fab=document.createElement('button');fab.id='c79MobileOpenPlay';fab.className='c79MobileOpenPlay';fab.type='button';fab.onclick=()=>showCoach('groupclasses');fab.innerHTML='<span>♟</span><b>Open Play</b><i><em class="c79MobileBadge"></em></i>';coachPage.appendChild(fab)}const count=c76PendingCount(),badge=fab.querySelector('.c79MobileBadge');badge.textContent=count;badge.classList.toggle('show',count>0);fab.setAttribute('aria-label',count?`Open Play มี ${count} คำขอรออนุมัติ`:'Open Play')}
function c79InjectOpenPlayDashboard(){if(state.role!=='coach'||(state.c43p||state.s42Page||'overview')!=='overview')return;const head=document.querySelector('#coachContent .c43w .c43head');if(!head||document.getElementById('c79OpenPlayEntry'))return;const count=c76PendingCount(),section=document.createElement('section');section.id='c79OpenPlayEntry';section.className='c79OpenPlayEntry';section.innerHTML=`<div><span class="c79OpenPlayIcon">♟</span><div><h3>Open Play</h3><p>เปิดคลาสกลุ่ม ระบุสนาม เวลา ราคา และจำนวนผู้เล่น <span class="c79Pending">${count?`${count} คำขอรออนุมัติ`:''}</span></p></div></div><button type="button" onclick="showCoach('groupclasses')">จัดการ Open Play</button>`;head.insertAdjacentElement('afterend',section)}
const c79CoachNavBase=c76CoachNav;c76CoachNav=function(){const result=c79CoachNavBase(),item=sidebar?.querySelector?.('[data-c76-groupclasses] span:last-child');if(item)item.textContent='Open Play';c79EnsureCoachOpenPlayEntry();return result};
const c79PaintCoachBadgeBase=c76PaintCoachBadge;c76PaintCoachBadge=function(){const result=c79PaintCoachBadgeBase();c79EnsureCoachOpenPlayEntry();const count=c76PendingCount(),entry=document.querySelector('#c79OpenPlayEntry .c79Pending');if(entry)entry.textContent=count?`${count} คำขอรออนุมัติ`:'';return result};
const c79AthleteMenuBase=c76EnsureAthleteMenu;c76EnsureAthleteMenu=function(){const result=c79AthleteMenuBase(),item=document.querySelector('#athletePage>.athleteTabs [data-c76-groupclasses]');if(item)item.textContent='Open Play';return result};
const c79CoachPageBase=c76CoachPage;c76CoachPage=function(){return c79OpenPlayText(c79CoachPageBase()).replace('＋ เปิด Open Play','＋ สร้าง Open Play')};
const c79AthletePageBase=c76AthletePage;c76AthletePage=function(){return c79OpenPlayText(c79AthletePageBase())};
const c79CoachCardBase=c76CoachCard;c76CoachCard=function(item){return c79OpenPlayText(c79CoachCardBase(item))};
const c79AthleteCardBase=c76AthleteCard;c76AthleteCard=function(item){return c79OpenPlayText(c79AthleteCardBase(item))};
const c79RenderCoachBase=c76RenderCoachPage;c76RenderCoachPage=function(){const result=c79RenderCoachBase();c79TranslateOpenPlay(document.getElementById('c76CoachGrid'));return result};
const c79RenderAthleteBase=c76RenderAthletePage;c76RenderAthletePage=function(){const result=c79RenderAthleteBase();c79TranslateOpenPlay(document.getElementById('c76AthleteGrid'));return result};
const c79OpenCreateBase=c76OpenCreate;c76OpenCreate=function(){const result=c79OpenCreateBase();c79TranslateOpenPlay(document.getElementById('c76Modal'));const heading=document.querySelector('#c76Modal h2'),button=document.getElementById('c76CreateButton');if(heading)heading.textContent='สร้าง Open Play';if(button)button.textContent='เปิดรับ Open Play';return result};
function c79Minutes(value){if(typeof value==='string'&&value.includes(':')){const parts=value.split(':').map(Number);return parts[0]*60+parts[1]}return Number(value)*60}
function c79OpenPlayConflict(date,start,end){const a=c79Minutes(start),b=c79Minutes(end),overlap=(x,y)=>a<y&&b>x,blocked=status=>!/cancel|reject|declin/i.test(String(status||''));const booking=(state.bookings||[]).find(x=>x.date===date&&blocked(x.status)&&overlap(c79Minutes(x.start),c79Minutes(x.end))),appointment=(state.c71CoachAppointments||[]).find(x=>x.date===date&&overlap(c79Minutes(x.start),c79Minutes(x.end))),group=(state.c76GroupClasses||[]).find(x=>x.date===date&&!['cancelled','closed'].includes(x.status)&&overlap(c79Minutes(x.start),c79Minutes(x.end)));return booking?`Booking ${booking.id||''}`:appointment?'นัดหมายในตาราง':group?'Open Play อื่น':null}
const c79CreateClassBase=c76CreateClass;c76CreateClass=async function(event){event.preventDefault();const date=document.getElementById('c76Date')?.value,start=document.getElementById('c76Start')?.value,end=document.getElementById('c76End')?.value,conflict=date&&start&&end?c79OpenPlayConflict(date,start,end):null;if(conflict)return alert(`เวลานี้ชนกับ ${conflict} กรุณาเลือกเวลาอื่น`);await c79CreateClassBase(event);const button=document.getElementById('c76CreateButton');if(button&&!button.disabled)button.textContent='เปิดรับ Open Play'};
async function c79NotifyOpenPlay(uid,payload){try{const key=db.ref(`notifications/${uid}`).push().key;await db.ref(`notifications/${uid}/${key}`).set({...payload,recipientId:uid,read:false,createdAt:firebase.database.ServerValue.TIMESTAMP})}catch(error){console.warn('Open Play notification unavailable',error)}}
c76JoinClass=async function(coachId,classId,button){const item=state.c76GroupClasses.find(x=>x.id===classId&&x.coachId===coachId);if(!item||item.status!=='open'||Number(item.approvedCount||0)>=Number(item.capacity||0))return alert('Open Play นี้เต็มหรือปิดรับแล้ว');try{button.disabled=true;const path=`coachGroupClassRequests/${coachId}/${classId}/${state.user.uid}`,nid=db.ref(`notifications/${coachId}`).push().key,now=firebase.database.ServerValue.TIMESTAMP,athleteName=c76AthleteName(),updates={};updates[path]={classId,coachId,athleteId:state.user.uid,athleteName,status:'pending',createdAt:now,updatedAt:now};updates[`notifications/${coachId}/${nid}`]={type:'open_play_join_request',openPlayId:classId,senderId:state.user.uid,recipientId:coachId,coachId,athleteId:state.user.uid,message:`${athleteName} ขอเข้าร่วม Open Play: ${item.title||'Open Play'}`,read:false,createdAt:now};await db.ref().update(updates);button.textContent='ส่งคำขอแล้ว'}catch(error){alert('ส่งคำขอไม่ได้: '+(error.message||error));button.disabled=false}};
c76Decide=async function(classId,athleteId,status,button){if(button?.disabled)return;const item=state.c76GroupClasses.find(x=>x.id===classId),request=state.c76GroupRequests?.[classId]?.[athleteId];if(!item||!request||request.status!=='pending')return;try{button.disabled=true;const requestRef=db.ref(`coachGroupClassRequests/${state.user.uid}/${classId}/${athleteId}`),claim=await requestRef.transaction(value=>value&&value.status==='pending'?{...value,status,updatedAt:Date.now()}:undefined);if(!claim.committed)throw Error('คำขอนี้ถูกดำเนินการแล้ว');let finalStatus=status;if(status==='approved'){const result=await db.ref(`coachGroupClasses/${state.user.uid}/${classId}`).transaction(value=>{if(!value||value.status!=='open'||Number(value.approvedCount||0)>=Number(value.capacity||0))return;const approvedCount=Number(value.approvedCount||0)+1;return {...value,approvedCount,status:approvedCount>=Number(value.capacity)?'full':'open',updatedAt:Date.now()}});if(!result.committed){finalStatus='rejected';await requestRef.update({status:'rejected',reason:'class_full',updatedAt:firebase.database.ServerValue.TIMESTAMP})}}await c79NotifyOpenPlay(athleteId,{type:finalStatus==='approved'?'open_play_approved':'open_play_rejected',openPlayId:classId,senderId:state.user.uid,coachId:state.user.uid,athleteId,message:finalStatus==='approved'?`Coach อนุมัติให้เข้าร่วม Open Play: ${item.title||'Open Play'}`:`คำขอเข้าร่วม Open Play ไม่ได้รับอนุมัติ: ${item.title||'Open Play'}`});try{await audit('coach_open_play_request_decided',classId,{athleteId,status:finalStatus})}catch(_){}}catch(error){alert('ดำเนินการคำขอไม่ได้: '+(error.message||error));button.disabled=false}};
const c79ShowCoachBase=showCoach;showCoach=function(page){const result=c79ShowCoachBase(page);if(state.role==='coach')setTimeout(()=>{c79EnsureCoachOpenPlayEntry();c79InjectOpenPlayDashboard();c79TranslateOpenPlay(document.querySelector('#coachContent .c76Page'))},30);return result};
auth.onAuthStateChanged(user=>{if(user)setTimeout(()=>{if(state.role==='coach'){c79EnsureCoachOpenPlayEntry();c79InjectOpenPlayDashboard()}},1400)});
