(function(root){
 'use strict';
 const excluded=new Set();let ownProfile={},profileUid='',profileRef=null,profileCallback=null;
 const standalone=()=>state.role==='coach'&&ownProfile.providerKind==='knocker';
 function keepCoachDirectory(){const removed=(state.coaches||[]).filter(p=>p.providerKind==='knocker').flatMap(p=>p.aliasUids||[p.uid]);state.coaches=(state.coaches||[]).filter(p=>p.providerKind!=='knocker');removed.forEach(uid=>excluded.add(uid));if(state.role==='athlete'&&excluded.has(state.coachId)){state.coachId='';state.c72DirectCoach=null;}}
 const merge=c104MergePublicCoachProfiles;c104MergePublicCoachProfiles=function(){const all=merge.apply(this,arguments);excluded.clear();all.filter(p=>p.providerKind==='knocker').flatMap(p=>p.aliasUids||[p.uid]).forEach(uid=>excluded.add(uid));return all.filter(p=>p.providerKind!=='knocker');};
 const picker=renderCoachPicker;renderCoachPicker=function(){keepCoachDirectory();return picker.apply(this,arguments);};
 const refresh=refreshCoachList;refreshCoachList=async function(render=true){await refresh(false);keepCoachDirectory();if(render)renderCoachPicker();return state.coaches;};
 function paintProvider(){document.body.classList.toggle('bo-knocker-provider',standalone());if(state.role!=='coach')return;if(typeof roleBadge!=='undefined')roleBadge.textContent=standalone()?'Knocker Portal':'Coach Portal';document.querySelectorAll('#sidebar small,#sidebar .c49CoachMeta').forEach(n=>{if(n.textContent.trim()==='ออนไลน์ • Coach'&&standalone())n.textContent='ออนไลน์ • Knocker';});if(standalone()&&!document.getElementById('boProviderType')){const box=document.createElement('section');box.id='boProviderType';box.className='notice';box.innerHTML='<b>บัญชี Knocker</b><p>ใช้ตาราง การจอง และการเงินจากบัญชีนี้ได้ ข้อมูลสมัคร Knocker ส่งเข้าคิวให้ Admin ตรวจสอบแล้ว</p>';coachContent.prepend(box);}if(!standalone())document.getElementById('boProviderType')?.remove();}
 function bindProfile(){if(state.role!=='coach'||!state.user?.uid)return;if(profileUid===state.user.uid)return;stopProfile();profileUid=state.user.uid;const uid=profileUid;profileRef=db.ref('coachProfiles/'+uid);profileCallback=s=>{if(uid!==profileUid)return;ownProfile=s.val()||{};paintProvider();};profileRef.on('value',profileCallback,()=>{});}
 function stopProfile(){if(profileRef&&profileCallback)profileRef.off('value',profileCallback);profileRef=null;profileCallback=null;profileUid='';ownProfile={};document.body.classList.remove('bo-knocker-provider');}
 function registrationLabel(){const select=document.getElementById('boRegisterKind'),kind=select?.value||'coach',label=kind==='knocker'?'Knocker':kind==='both'?'Coach และ Knocker':'Coach';if(!select)return;const title=document.querySelector('#c68Modal h2'),submit=document.getElementById('c68Submit');if(title)title.textContent='สมัคร '+label;if(submit)submit.textContent='สร้าง / เชื่อมบัญชี '+label;}
 const openRegister=c68OpenCoachRegistration;c68OpenCoachRegistration=function(){const result=openRegister.apply(this,arguments);const select=document.getElementById('boRegisterKind');if(select)select.addEventListener('change',registrationLabel);registrationLabel();return result;};
 function loginLabels(){if(typeof selectedLoginPortal!=='undefined'&&selectedLoginPortal==='coach'){const title=document.getElementById('loginTitle'),button=document.getElementById('loginBtn');if(title)title.textContent='เข้าสู่ระบบ Coach / Knocker';if(button)button.textContent='เข้าสู่ระบบ Coach / Knocker';}document.querySelectorAll('[onclick*="c68OpenCoachRegistration"]').forEach(b=>{if(b.textContent.trim()!=='สมัคร Coach / Knocker')b.textContent='สมัคร Coach / Knocker';});}
 const selectPortal=selectLoginPortal;selectLoginPortal=function(){const result=selectPortal.apply(this,arguments);loginLabels();return result;};
 const show=showCoach;showCoach=function(){const result=show.apply(this,arguments);bindProfile();paintProvider();return result;};
 const leave=logout;logout=function(){stopProfile();return leave.apply(this,arguments);};auth.onAuthStateChanged(u=>{if(!u||u.uid!==profileUid){stopProfile();if(u)setTimeout(()=>{bindProfile();loginLabels();},1800);}});
 const style=document.createElement('style');style.textContent='.bo-knocker-provider .c72ShareCard,.bo-knocker-provider .c72HeaderShare{display:none!important} #boTrialDialog label{display:grid;gap:6px;margin:14px 0} #boTrialError{color:#b42318} #boRenewalNotice{margin-bottom:16px}';document.head.append(style);loginLabels();bindProfile();
})(window);
