const C46_TRIAL_DAYS=60,C46_PRICE=19900,C46_BANK='ธนาคารกรุงศรี',C46_ACCOUNT='1471652673',C46_NAME='ทัศวรรณ ขะณะดี',C46_PHONE='0909599335';
function c46PeriodEnd(s){return Number(s?.status==='active'?s.currentPeriodEndsAt:s?.trialEndsAt||0)}
function c46Days(s,now=Date.now()){const e=c46PeriodEnd(s);return e?Math.ceil((e-now)/86400000):null}
function c46NextPeriodEnd(s,now=Date.now(),months=1){return Math.max(now,Number(s?.currentPeriodEndsAt||0))+30*months*86400000}
async function c46EnsureTrial(){if(state.role!=='coach'||!state.user?.uid)return;try{const ref=db.ref(`users/${state.user.uid}/subscription`),canonical=(await ref.once('value')).val();if(canonical){state.subscription=canonical;return}const now=Date.now(),trial={status:'trial',priceSatang:C46_PRICE,trialStartedAt:now,trialEndsAt:now+C46_TRIAL_DAYS*86400000,currentPeriodStartsAt:null,currentPeriodEndsAt:null};await ref.set(trial);state.subscription=trial}catch(e){console.warn('trial bootstrap',e)}}
cdCoachSubscriptionCard=function(){const s=state.subscription||{},d=c46Days(s),active=s.status==='active'&&Number(s.currentPeriodEndsAt||0)>Date.now(),trial=!active&&Number(s.trialEndsAt||0)>Date.now();return `<section class="c46sub"><div class="c46subHead"><div><h3 style="margin:0">Coach Di Subscription</h3><div class="muted">ทดลองใช้ฟรี 60 วันจากการเริ่มใช้งานครั้งแรก จากนั้น ฿199 / 30 วัน</div></div><span class="status ${active?'confirmed':trial?'coach_approved':'pending'}">${active?'Active':trial?'ทดลองใช้ฟรี':'รอชำระ/ตรวจสอบ'}</span></div><div class="c46subGrid"><div><span>วันคงเหลือ</span><b>${d===null?'-':d>0?d+' วัน':'ครบกำหนดแล้ว'}</b></div><div><span>Trial สิ้นสุด</span><b>${cdDateTime(s.trialEndsAt)}</b></div><div><span>รอบปัจจุบันสิ้นสุด</span><b>${cdDateTime(s.currentPeriodEndsAt)}</b></div></div>${d!==null&&d<=7?`<div class="notice"><b>${d>0?'ใกล้ครบกำหนด':'ครบกำหนดแล้ว'}</b><br>${d>0?`เหลือ ${d} วัน`:'กรุณาชำระและรอ Admin Activate Account'}</div>`:''}</section>`}
cdSubscriptionPayCard=function(){return `<section class="c46sub"><h3 style="margin-top:0">ชำระ Coach Di Subscription</h3><div id="cdSubPayInfo">กำลังโหลด...</div></section>`}
cdLoadSubscriptionPayInfo=async function(){const el=document.getElementById('cdSubPayInfo');if(!el)return;el.innerHTML=`<div class="c46bank">${C46_BANK}<strong>${C46_ACCOUNT}</strong>ชื่อบัญชี ${C46_NAME}</div><label><span class="label">แนบสลิป ฿199</span><input id="cdSubSlip" type="file" accept="image/jpeg,image/png,image/webp"></label><button class="pill primary" style="width:100%;margin-top:10px" onclick="cdSubmitSubscriptionSlip(this)">ส่งสลิปให้ Admin ตรวจสอบ</button><div class="c46sms">ระบบสร้าง Admin Alert และคิวแจ้งเตือนไป ${C46_PHONE}; การส่ง SMS จริงต้องเชื่อม Backend provider</div>`}
cdSubmitSubscriptionSlip=async function(btn){if(btn.disabled)return;try{btn.disabled=true;const input=document.getElementById('cdSubSlip'),f=input?.files?.[0];if(!f)throw new Error('กรุณาเลือกไฟล์สลิป');if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw new Error('รองรับเฉพาะ JPG, PNG หรือ WEBP');if(f.size>3*1024*1024)throw new Error('ไฟล์ต้องไม่เกิน 3 MB');const slip=await s38ReadFile(input),id=db.ref('subscriptionPaymentRequests').push().key;await db.ref(`subscriptionPaymentRequests/${id}`).set({type:'subscription_payment',coachId:state.user.uid,coachEmail:state.user.email||'',amountSatang:C46_PRICE,bank:C46_BANK,accountNumberLast4:'2673',accountName:C46_NAME,slipDataUrl:slip,status:'pending',notificationTarget:C46_PHONE,notificationStatus:'pending_backend_provider',createdAt:firebase.database.ServerValue.TIMESTAMP});alert('ส่งสลิปแล้ว กรุณารอ Admin ตรวจสอบและ Activate Account');btn.textContent='ส่งแล้ว • รอตรวจสอบ'}catch(e){alert(e.message||'ส่งไม่สำเร็จ');btn.disabled=false}}
cdLoadSubRequests=async function(){const el=document.getElementById('cdSubRequests');if(!el)return;try{const s=await db.ref('subscriptionPaymentRequests').once('value'),rows=Object.entries(s.val()||{}).filter(([,r])=>r.type==='subscription_payment'&&r.status==='pending');el.innerHTML=rows.length?`<h3>สลิปรอตรวจสอบ (${rows.length})</h3>`+rows.map(([id,r])=>`<div class="c46req"><div><b>${esc(r.coachEmail||r.coachId)}</b><p>${baht(r.amountSatang)} • ${esc(r.bank)} •••• ${esc(r.accountNumberLast4)}</p><div class="c46sms">Alert target ${esc(r.notificationTarget||C46_PHONE)} • ${esc(r.notificationStatus||'pending')}</div><button class="pill primary" onclick="cdApproveSubRequest('${esc(id)}','${esc(r.coachId)}',this)">ตรวจแล้ว • Activate 30 วัน</button> <button class="pill" onclick="c46RejectSub('${esc(id)}',this)">ปฏิเสธ</button></div><img src="${r.slipDataUrl}" alt="สลิป"></div>`).join(''):'<div class="muted">ไม่มีสลิปรอตรวจสอบ</div>'}catch(e){el.innerHTML=`<div class="error">${esc(e.message||e)}</div>`}}
cdApproveSubRequest=async function(id,uid,btn){if(!confirm('ตรวจสลิปถูกต้องและ Activate 30 วัน?'))return;try{btn.disabled=true;const snap=await db.ref(`users/${uid}/subscription`).once('value'),old=snap.val()||{},now=Date.now(),end=c46NextPeriodEnd(old,now,1),tx=db.ref('subscriptionTransactions').push().key,up={};up[`users/${uid}/subscription`]={...old,status:'active',priceSatang:C46_PRICE,currentPeriodStartsAt:now,currentPeriodEndsAt:end,lastPaymentSatang:C46_PRICE,lastPaidAt:firebase.database.ServerValue.TIMESTAMP,lastActivatedBy:state.user.uid,lastActivatedAt:firebase.database.ServerValue.TIMESTAMP};up[`subscriptionTransactions/${tx}`]={coachId:uid,paymentRequestId:id,amountSatang:C46_PRICE,months:1,status:'paid',activatedBy:state.user.uid,createdAt:firebase.database.ServerValue.TIMESTAMP};up[`subscriptionPaymentRequests/${id}/status`]='approved';up[`subscriptionPaymentRequests/${id}/approvedBy`]=state.user.uid;up[`subscriptionPaymentRequests/${id}/approvedAt`]=firebase.database.ServerValue.TIMESTAMP;up[`subscriptionPaymentRequests/${id}/notificationStatus`]='admin_processed';await db.ref().update(up);await audit('subscription_payment_approved',uid,{requestId:id,currentPeriodEndsAt:end});alert('Activate Account 30 วันเรียบร้อย');await cdLoadSubRequests()}catch(e){alert(e.message||'Activate ไม่สำเร็จ');btn.disabled=false}}
async function c46RejectSub(id,btn){const reason=(prompt('เหตุผลที่ปฏิเสธ')||'').trim();if(!reason)return;try{btn.disabled=true;await db.ref(`subscriptionPaymentRequests/${id}`).update({status:'rejected',rejectionReason:reason,rejectedBy:state.user.uid,rejectedAt:firebase.database.ServerValue.TIMESTAMP,notificationStatus:'admin_processed'});await audit('subscription_payment_rejected',id,{reason});await cdLoadSubRequests()}catch(e){alert(e.message||'ปฏิเสธไม่สำเร็จ');btn.disabled=false}}
const c46LoadData=loadFirebaseData;loadFirebaseData=async function(){await c46LoadData();await c46EnsureTrial()};auth.onAuthStateChanged(u=>{if(u)setTimeout(async()=>{if(state.role==='coach'){await c46EnsureTrial();if(state.s42Page)showCoach(state.s42Page)}},1800)})
