'use strict';const{test}=require('node:test');const assert=require('node:assert/strict');const domain=require('../functions-mobile/booking-refund.cjs');
const now=Date.parse('2026-10-01T12:00:00+07:00'),actorUid='coach_12345678',user={role:'coach',status:'active',subscription:{trialEndsAt:now+86400000}},account={bank:'ธนาคารทดสอบ',accountName:'Athlete Test',accountNumber:'0012345678'};
const booking=(changed={})=>({id:'BOOKING_123',coachId:actorUid,athleteId:'athlete_12345678',date:'2026-10-10',start:10,end:11,status:'confirmed',paymentStatus:'payment_verified',priceSatang:100000,travelFeeSatang:10000,platformFeeSatang:5000,...changed});
const request=(action,changed={})=>({actorUid,user,input:{requestId:'request_12345678',bookingId:'BOOKING_123',action,...changed.input},booking:booking(changed.booking),refundAccount:changed.refundAccount===undefined?account:changed.refundAccount,refund:changed.refund||null,now});
const proof={path:`private/refund-slip/${actorUid}/row/refund.jpg`,contentType:'image/jpeg',size:1024,name:'refund.jpg'};

test('coach cancellation derives refund from payment and saved athlete account',()=>{const decision=domain.evaluate(request('coach_cancel'));assert.equal(decision.ok,true);assert.equal(decision.nextStatus,'cancelled_by_coach');assert.equal(decision.refundStatus,'requested');assert.equal(decision.grossSatang,110000);const patch=domain.bookingPatch(decision,actorUid,{reason:'ไม่สะดวก'},now);assert.equal(patch.refundAccountNumber,'0012345678')});
test('coach cancellation without saved account still cancels and asks athlete for an account',()=>{const decision=domain.evaluate(request('coach_cancel',{refundAccount:null}));assert.equal(decision.ok,true);assert.equal(decision.refundRequired,true);assert.equal(decision.destination,null);assert.equal(decision.refundStatus,null)});
test('cash refund requires an exact pending refund and private coach-owned proof',()=>{const pending={bookingId:'BOOKING_123',coachId:actorUid,athleteId:'athlete_12345678',amountSatang:110000,status:'requested'},changed={booking:{status:'refund_pending_coach_decision',refundStatus:'requested',refundRequestedAt:now},refund:pending,input:{refundProof:proof}};assert.equal(domain.evaluate(request('coach_complete_cash_refund',changed)).ok,true);assert.equal(domain.evaluate(request('coach_complete_cash_refund',{...changed,input:{refundProof:{...proof,path:'private/refund-slip/other/file.jpg'}}})).code,'REFUND_EVIDENCE_REQUIRED');assert.equal(domain.evaluate(request('coach_complete_cash_refund',{...changed,refund:{...pending,amountSatang:1}})).code,'REFUND_RECORD_CONFLICT')});
test('coin refund stays pending for admin and is not reported as completed',()=>{const pending={bookingId:'BOOKING_123',coachId:actorUid,athleteId:'athlete_12345678',amountSatang:110000,status:'requested'},decision=domain.evaluate(request('coach_select_coin_refund',{booking:{status:'refund_pending_coach_decision',refundStatus:'requested',refundRequestedAt:now},refund:pending}));assert.equal(decision.nextStatus,'refund_pending_admin_coin_credit');assert.equal(decision.refundStatus,'pending_admin_coin_credit')});
test('other coaches and past bookings cannot cancel',()=>{assert.equal(domain.evaluate({...request('coach_cancel'),actorUid:'coach_87654321'}).code,'NOT_ASSIGNED_COACH');assert.equal(domain.evaluate(request('coach_cancel',{booking:{date:'2026-09-01'}})).code,'BOOKING_IN_PAST')});
