'use strict';
const{test}=require('node:test');const assert=require('node:assert/strict');const service=require('../functions-mobile/chat-service.cjs');
const clone=value=>value==null?value:structuredClone(value);const parts=path=>String(path||'').split('/').filter(Boolean);
function read(root,path){let node=root;for(const part of parts(path)){if(node==null)return null;node=node[part]}return node==null?null:node}
function write(root,path,value){const keys=parts(path);if(!keys.length){for(const key of Object.keys(root))delete root[key];Object.assign(root,clone(value)||{});return}let node=root;for(const key of keys.slice(0,-1))node=node[key]||(node[key]={});const last=keys.at(-1);if(value===null)delete node[last];else node[last]=clone(value)}
class Snapshot{constructor(value){this.value=clone(value)}val(){return clone(this.value)}}
class Ref{constructor(db,path){this.db=db;this.path=path}async get(){return new Snapshot(read(this.db.data,this.path))}async transaction(callback){const current=clone(read(this.db.data,this.path)),next=callback(current);if(next===undefined)return{committed:false,snapshot:new Snapshot(current)};write(this.db.data,this.path,next);return{committed:true,snapshot:new Snapshot(next)}}async update(updates){if(this.db.failRootUpdateOnce&&!this.path){this.db.failRootUpdateOnce=false;throw Error('simulated network loss')}for(const[path,value]of Object.entries(updates))write(this.db.data,this.path?`${this.path}/${path}`:path,value)}}
class FakeDb{constructor(data){this.data=clone(data);this.failRootUpdateOnce=false}ref(path=''){return new Ref(this,path)}}
const now=Date.parse('2026-10-01T12:00:00+07:00'),bookingId='BOOKING_123';
function seed(){return{users:{coach_12345678:{role:'coach',status:'active',displayName:'Coach Test'},athlete_12345678:{role:'athlete',displayName:'Athlete Test'},outsider_12345678:{role:'athlete',displayName:'Outsider'}},bookings:{[bookingId]:{coachId:'coach_12345678',athleteId:'athlete_12345678',coachName:'Coach Test',athlete:'Athlete Test'}}}}
const request=(actorUid='coach_12345678',requestId='request_12345678',text=' สวัสดีครับ\r\nพร้อมเรียนไหมครับ ' )=>({actorUid,input:{bookingId,requestId,text},now});

test('participant message and push notification are written once with server-owned identity',async()=>{const db=new FakeDb(seed()),result=await service.execute(db,request());assert.equal(result.ok,true);assert.equal(result.replay,false);assert.equal(result.recipientId,'athlete_12345678');const messages=read(db.data,`bookingChats/${bookingId}/messages`),notices=read(db.data,'notifications/athlete_12345678');assert.equal(Object.keys(messages).length,1);assert.equal(Object.values(messages)[0].text,'สวัสดีครับ\nพร้อมเรียนไหมครับ');assert.deepEqual(Object.values(messages)[0],{senderId:'coach_12345678',senderRole:'coach',text:'สวัสดีครับ\nพร้อมเรียนไหมครับ',createdAt:now});assert.equal(Object.keys(notices).length,1);assert.match(Object.values(notices)[0].message,/Coach Test/);assert.equal(Object.values(notices)[0].recipientId,'athlete_12345678')});
test('same request replays without duplicating message or notification and preserves read status',async()=>{const db=new FakeDb(seed()),first=await service.execute(db,request());write(db.data,`notifications/athlete_12345678/${first.notificationId}/read`,true);const again=await service.execute(db,request());assert.equal(again.replay,true);assert.equal(Object.keys(read(db.data,`bookingChats/${bookingId}/messages`)).length,1);assert.equal(Object.keys(read(db.data,'notifications/athlete_12345678')).length,1);assert.equal(read(db.data,`notifications/athlete_12345678/${first.notificationId}/read`),true)});
test('retry repairs command result after a lost response without duplicate side effects',async()=>{const db=new FakeDb(seed());db.failRootUpdateOnce=true;await assert.rejects(()=>service.execute(db,request()),/network loss/);assert.equal(Object.keys(read(db.data,`bookingChats/${bookingId}/messages`)).length,1);const result=await service.execute(db,request());assert.equal(result.replay,true);assert.equal(Object.keys(read(db.data,'notifications/athlete_12345678')).length,1);assert.equal(read(db.data,'chatCommandResults/coach_12345678/request_12345678/status'),'completed')});
test('request id cannot be reused for changed message content',async()=>{const db=new FakeDb(seed());await service.execute(db,request());await assert.rejects(()=>service.execute(db,request('coach_12345678','request_12345678','ข้อความอื่น')),error=>error.code==='REQUEST_CONFLICT')});
test('athlete can message the assigned coach but outsider and inactive coach are rejected',async()=>{const db=new FakeDb(seed()),athlete=await service.execute(db,request('athlete_12345678','request_athlete1','ถึงโค้ช'));assert.equal(athlete.recipientId,'coach_12345678');await assert.rejects(()=>service.execute(db,request('outsider_12345678','request_outside1','ปลอม')),error=>error.code==='NOT_BOOKING_PARTICIPANT');write(db.data,'users/coach_12345678/status','suspended');await assert.rejects(()=>service.execute(db,request('coach_12345678','request_suspend1','ปลอม')),error=>error.code==='COACH_INACTIVE')});
test('empty, oversized and malformed requests are rejected before chat writes',async()=>{for(const req of [request('coach_12345678','short','hello'),request('coach_12345678','request_empty123','   '),request('coach_12345678','request_long123','x'.repeat(service.MAX_TEXT+1))]){const db=new FakeDb(seed());await assert.rejects(()=>service.execute(db,req),error=>error.code==='INVALID_CHAT_MESSAGE');assert.equal(read(db.data,'bookingChats'),null)}});
