'use strict';
const{test}=require('node:test');const assert=require('node:assert/strict');const{readFileSync}=require('node:fs');const path=require('node:path');const vm=require('node:vm');const Core=require('../booking-server-client-core.js');
function fixture(){
  const calls=[],alerts=[],items=new Map(),button={disabled:false};
  const make=value=>({value,parentElement:{querySelector:()=>button}});for(const id of ['cdChatInput','c43input','cd396ChatInput','cd398ChatInput','s40ChatInput'])items.set(id,make(''));
  const root={CoachDiBookingServerCore:Core,CoachDiBookingServer:{call:async(name,data)=>{calls.push({name,data});return{ok:true}}},coachDiFirebaseApp:{auth:()=>({currentUser:{uid:'athlete_12345678'}})},sessionStorage:{getItem:key=>items.get(`storage:${key}`)||null,setItem:(key,value)=>items.set(`storage:${key}`,value),removeItem:key=>items.delete(`storage:${key}`)},state:{c43chat:'BOOKING_43'},cd396ChatBookingId:'BOOKING_396',cd398ChatBookingId:'BOOKING_398',s40ChatBookingId:'BOOKING_40',document:{getElementById:id=>items.get(id)||null,body:{contains:()=>true}},alert:value=>alerts.push(String(value))};root.window=root;
  vm.runInNewContext(readFileSync(path.join(__dirname,'../chat-server-client.js'),'utf8'),root);
  return{root,calls,alerts,items,button};
}
test('all legacy Booking Chat send entry points route through the same callable',async()=>{const f=fixture(),routes=[['cdChatInput',()=>f.root.cdSendChat('BOOKING_DIRECT')],['c43input',()=>f.root.c43send()],['cd396ChatInput',()=>f.root.cd396SendChat()],['cd398ChatInput',()=>f.root.cd398SendMessage()],['s40ChatInput',()=>f.root.s40SendMessage()]];for(const[id,send]of routes){f.items.get(id).value=`ข้อความ ${id}`;await send();assert.equal(f.items.get(id).value,'')}assert.deepEqual(f.calls.map(row=>row.name),Array(5).fill('sendBookingChatMessage'));assert.deepEqual(f.calls.map(row=>row.data.bookingId),['BOOKING_DIRECT','BOOKING_43','BOOKING_396','BOOKING_398','BOOKING_40']);assert.deepEqual(f.alerts,[])});
test('rapid repeat is coalesced and a failed call preserves the draft for retry',async()=>{const f=fixture(),input=f.items.get('s40ChatInput');let release;f.root.CoachDiBookingServer.call=async(name,data)=>{f.calls.push({name,data});await new Promise(resolve=>{release=resolve});return{ok:true}};input.value='ส่งครั้งเดียว';const first=f.root.s40SendMessage(),second=f.root.s40SendMessage();assert.equal(await second,null);assert.equal(f.calls.length,1);release();await first;assert.equal(input.value,'');f.root.CoachDiBookingServer.call=async()=>{throw Object.assign(Error('failure'),{details:{code:'INVALID_CHAT_MESSAGE'}})};input.value='ข้อความที่ต้องแก้';await f.root.s40SendMessage();assert.equal(input.value,'ข้อความที่ต้องแก้');assert.match(f.alerts.at(-1),/2,000/);assert.equal(f.button.disabled,false)});
