'use strict';
const{test}=require('node:test');const assert=require('node:assert/strict');const service=require('../functions-mobile/coach-schedule-service.cjs');
const clone=value=>value==null?value:structuredClone(value);const parts=path=>String(path||'').split('/').filter(Boolean);
function read(root,path){let node=root;for(const part of parts(path)){if(node==null)return null;node=node[part]}return node==null?null:node}
function write(root,path,value){const keys=parts(path);if(!keys.length){for(const key of Object.keys(root))delete root[key];Object.assign(root,clone(value)||{});return}let node=root;for(const key of keys.slice(0,-1))node=node[key]||(node[key]={});const last=keys.at(-1);if(value===null)delete node[last];else node[last]=clone(value)}
class Snapshot{constructor(value){this.value=clone(value)}val(){return clone(this.value)}}
class Ref{constructor(db,path){this.db=db;this.path=path}async transaction(callback){const current=clone(read(this.db.data,this.path)),next=callback(current);if(next===undefined)return{committed:false,snapshot:new Snapshot(current)};write(this.db.data,this.path,next);return{committed:true,snapshot:new Snapshot(next)}}}
class FakeDb{constructor(data){this.data=clone(data)}ref(path=''){return new Ref(this,path)}}
const coach='coach_12345678',now=Date.parse('2026-10-01T12:00:00+07:00');
function seed(){return{users:{[coach]:{role:'coach',status:'active'}},bookings:{},coachPublicSchedule:{[coach]:{}},coachGroupClasses:{[coach]:{}},coachTimeOff:{[coach]:{}}}}
const appointment=(input={})=>({actorUid:coach,input:{action:'appointment_upsert',requestId:'request_appointment1',date:'2026-10-10',start:9,end:10.5,venueId:'visda',venueName:'VISDA Premium Tennis Club',...input},now});
const holiday=(input={})=>({actorUid:coach,input:{action:'time_off_upsert',requestId:'request_holiday123',startDate:'2026-10-12',endDate:'2026-10-15',...input},now});

test('server creates a recurring appointment series once and replays without duplicates',async()=>{const db=new FakeDb(seed()),input=appointment({recurringUntil:'2026-10-24'}),first=await service.execute(db,input),again=await service.execute(db,input);assert.equal(first.count,3);assert.equal(again.replay,true);const rows=read(db.data,`coachPublicSchedule/${coach}`);assert.equal(Object.keys(rows).length,3);assert.deepEqual(Object.values(rows).map(row=>row.date),['2026-10-10','2026-10-17','2026-10-24']);assert.ok(Object.values(rows).every(row=>row.coachId===coach&&row.source==='coach_existing_appointment'&&row.recurrenceGroup==='2026-10-10'));assert.equal(Object.keys(read(db.data,`auditLogs/${coach}`)).length,1)});
test('appointment rejects past time, existing commitments, time off and changed retries',async()=>{for(const mutate of [db=>write(db.data,`bookings/b`,{coachId:coach,date:'2026-10-10',start:9,end:10,status:'confirmed'}),db=>write(db.data,`coachPublicSchedule/${coach}/a`,{date:'2026-10-10',start:10,end:11}),db=>write(db.data,`coachGroupClasses/${coach}/g`,{date:'2026-10-10',start:8,end:9.5,status:'open'}),db=>write(db.data,`coachTimeOff/${coach}/o`,{startDate:'2026-10-10',endDate:'2026-10-10',fullDay:true})]){const db=new FakeDb(seed());mutate(db);await assert.rejects(()=>service.execute(db,appointment()),error=>['TIME_CONFLICT','COACH_TIME_OFF'].includes(error.code));assert.equal(read(db.data,`coachScheduleCommandResults/${coach}`),null)}const past=new FakeDb(seed());await assert.rejects(()=>service.execute(past,appointment({date:'2026-10-01',start:8,end:9})),error=>error.code==='INVALID_APPOINTMENT');const changed=new FakeDb(seed());await service.execute(changed,appointment());await assert.rejects(()=>service.execute(changed,appointment({venueName:'สนามใหม่'})),error=>error.code==='REQUEST_CONFLICT')});
test('Coach can create, edit and delete a multi-day holiday with optimistic version checks',async()=>{const db=new FakeDb(seed()),created=await service.execute(db,holiday()),path=`coachTimeOff/${coach}/${created.timeOffId}`,saved=read(db.data,path);assert.deepEqual({startDate:saved.startDate,endDate:saved.endDate,fullDay:saved.fullDay},{startDate:'2026-10-12',endDate:'2026-10-15',fullDay:true});const edited=await service.execute(db,holiday({requestId:'request_holiday_edit',timeOffId:created.timeOffId,startDate:'2026-10-13',endDate:'2026-10-16',expectedVersion:saved.revision}));assert.equal(edited.timeOffId,created.timeOffId);await assert.rejects(()=>service.execute(db,holiday({action:'time_off_delete',requestId:'request_holiday_stale',timeOffId:created.timeOffId,startDate:'',endDate:'',expectedVersion:saved.revision})),error=>error.code==='SCHEDULE_CHANGED');const current=read(db.data,path);const removed=await service.execute(db,holiday({action:'time_off_delete',requestId:'request_holiday_del',timeOffId:created.timeOffId,startDate:'',endDate:'',expectedVersion:current.revision}));assert.equal(removed.action,'time_off_delete');assert.equal(read(db.data,path),null)});
test('holiday rejects overlap with bookings, appointments, classes and another holiday',async()=>{const fixtures=[['bookings/b',{coachId:coach,date:'2026-10-13',start:9,end:10,status:'pending_coach_approval'}],[`coachPublicSchedule/${coach}/a`,{date:'2026-10-14',start:9,end:10}],[`coachGroupClasses/${coach}/g`,{date:'2026-10-15',start:9,end:10,status:'closed'}],[`coachTimeOff/${coach}/o`,{startDate:'2026-10-11',endDate:'2026-10-12',fullDay:true}]];for(const[path,row]of fixtures){const db=new FakeDb(seed());write(db.data,path,row);await assert.rejects(()=>service.execute(db,holiday()),error=>['TIME_CONFLICT','TIME_OFF_OVERLAP'].includes(error.code));assert.equal(Object.keys(read(db.data,`coachTimeOff/${coach}`)).length,path.includes('coachTimeOff')?1:0)}});
test('inactive Coach, malformed commands, stale appointment updates and long recurrence fail closed',async()=>{const inactive=new FakeDb(seed());write(inactive.data,`users/${coach}/status`,'suspended');await assert.rejects(()=>service.execute(inactive,appointment()),error=>error.code==='COACH_INACTIVE');const malformed=new FakeDb(seed());await assert.rejects(()=>service.execute(malformed,appointment({requestId:'short'})),error=>error.code==='INVALID_SCHEDULE_COMMAND');const stale=new FakeDb(seed());write(stale.data,`coachPublicSchedule/${coach}/existing`,{coachId:coach,date:'2026-10-10',start:9,end:10,venueName:'เดิม',createdAt:1,updatedAt:2});await assert.rejects(()=>service.execute(stale,appointment({requestId:'request_stale123',appointmentId:'existing',expectedVersion:1,start:11,end:12})),error=>error.code==='SCHEDULE_CHANGED');const recurrence=new FakeDb(seed());await assert.rejects(()=>service.execute(recurrence,appointment({requestId:'request_recurring',recurringUntil:'2027-12-31'})),error=>error.code==='RECURRENCE_LIMIT')});
