'use strict';
const{test}=require('node:test');const assert=require('node:assert/strict');const service=require('../functions-mobile/direct-chat-service.cjs');
const clone=value=>value==null?value:structuredClone(value);const parts=path=>String(path||'').split('/').filter(Boolean);
function read(root,path){let node=root;for(const part of parts(path)){if(node==null)return null;node=node[part]}return node==null?null:node}
function write(root,path,value){const keys=parts(path);if(!keys.length){for(const key of Object.keys(root))delete root[key];Object.assign(root,clone(value)||{});return}let node=root;for(const key of keys.slice(0,-1))node=node[key]||(node[key]={});const last=keys.at(-1);if(value===null)delete node[last];else node[last]=clone(value)}
class Snapshot{constructor(value){this.value=clone(value)}val(){return clone(this.value)}}
class Ref{constructor(db,path){this.db=db;this.path=path}async get(){return new Snapshot(read(this.db.data,this.path))}async transaction(callback){const current=clone(read(this.db.data,this.path)),next=callback(current);if(next===undefined)return{committed:false,snapshot:new Snapshot(current)};write(this.db.data,this.path,next);return{committed:true,snapshot:new Snapshot(next)}}async update(updates){if(this.db.failRootUpdateOnce&&!this.path){this.db.failRootUpdateOnce=false;throw Error('simulated network loss')}for(const[path,value]of Object.entries(updates))write(this.db.data,this.path?`${this.path}/${path}`:path,value)}}
class FakeDb{constructor(data){this.data=clone(data);this.failRootUpdateOnce=false}ref(path=''){return new Ref(this,path)}}
const now=Date.parse('2026-10-01T12:00:00+07:00');
function seed(){return{users:{coach_12345678:{role:'coach',status:'active'},athlete_12345678:{role:'athlete'},outsider_12345678:{role:'athlete'},admin_12345678:{role:'admin'}},bookings:{booking_12345678:{coachId:'coach_12345678',athleteId:'athlete_12345678'}}}}
const request=(actorUid='athlete_12345678',input={})=>({actorUid,input:{action:'send',requestId:'request_12345678',coachId:'coach_12345678',athleteId:'athlete_12345678',bookingId:'booking_12345678',text:' สวัสดีครับ\r\nพร้อมไหม ',...input},now});

test('participant sends one server-owned direct message with verified relationship',async()=>{const db=new FakeDb(seed()),result=await service.execute(db,request());assert.equal(result.ok,true);assert.equal(result.replay,false);assert.deepEqual(read(db.data,`userChats/coach_12345678/athlete_12345678/messages/${result.messageId}`),{senderId:'athlete_12345678',senderRole:'athlete',bookingId:'booking_12345678',text:'สวัสดีครับ\nพร้อมไหม',createdAt:now})});
test('same request replays without duplicating a direct message',async()=>{const db=new FakeDb(seed()),first=await service.execute(db,request()),again=await service.execute(db,request());assert.equal(again.replay,true);assert.equal(again.messageId,first.messageId);assert.equal(Object.keys(read(db.data,'userChats/coach_12345678/athlete_12345678/messages')).length,1)});
test('retry after a lost send response repairs command state without duplicate messages',async()=>{const db=new FakeDb(seed());db.failRootUpdateOnce=true;await assert.rejects(()=>service.execute(db,request()),/network loss/);const result=await service.execute(db,request());assert.equal(result.replay,true);assert.equal(Object.keys(read(db.data,'userChats/coach_12345678/athlete_12345678/messages')).length,1);assert.equal(read(db.data,'directChatCommandResults/athlete_12345678/request_12345678/status'),'completed')});
test('sender can delete own message once and replay safely',async()=>{const db=new FakeDb(seed()),sent=await service.execute(db,request()),deletion=request('athlete_12345678',{action:'delete',requestId:'delete_12345678',bookingId:'',messageId:sent.messageId,text:''}),removed=await service.execute(db,deletion),again=await service.execute(db,deletion);assert.equal(removed.action,'delete');assert.equal(again.replay,true);assert.equal(read(db.data,`userChats/coach_12345678/athlete_12345678/messages/${sent.messageId}`),null)});
test('outsider, unrelated pair, inactive coach and deleting another sender message are rejected',async()=>{const db=new FakeDb(seed());await assert.rejects(()=>service.execute(db,request('outsider_12345678',{requestId:'outside_12345678'})),error=>error.code==='NOT_DIRECT_CHAT_PARTICIPANT');await assert.rejects(()=>service.execute(db,request('athlete_12345678',{requestId:'unlinked_12345678',coachId:'other_coach_123'})),error=>error.code==='DIRECT_CHAT_RELATIONSHIP_NOT_FOUND');write(db.data,'users/coach_12345678/status','suspended');await assert.rejects(()=>service.execute(db,request('coach_12345678',{requestId:'inactive_12345678'})),error=>error.code==='COACH_INACTIVE');write(db.data,'users/coach_12345678/status','active');const sent=await service.execute(db,request());await assert.rejects(()=>service.execute(db,request('coach_12345678',{action:'delete',requestId:'delete_other123',bookingId:'',messageId:sent.messageId,text:''})),error=>error.code==='NOT_DIRECT_CHAT_MESSAGE_OWNER')});
test('invalid action, request id, message id and oversized text are rejected before writes',async()=>{for(const req of [request('athlete_12345678',{action:'edit'}),request('athlete_12345678',{requestId:'short'}),request('athlete_12345678',{action:'delete',messageId:'bad/id',text:''}),request('athlete_12345678',{text:'x'.repeat(service.MAX_TEXT+1)})]){const db=new FakeDb(seed());await assert.rejects(()=>service.execute(db,req),error=>['INVALID_DIRECT_CHAT_COMMAND','INVALID_DIRECT_CHAT_MESSAGE'].includes(error.code));assert.equal(read(db.data,'userChats'),null)}});
