'use strict';const{test}=require('node:test');const assert=require('node:assert/strict');const service=require('../functions-mobile/group-class-service.cjs');
const clone=value=>value==null?value:structuredClone(value);class Snapshot{constructor(value){this.value=clone(value)}val(){return clone(this.value)}}
class Ref{constructor(db){this.db=db}async transaction(update){const current=clone(this.db.data),next=update(current);if(next===undefined)return{committed:false,snapshot:new Snapshot(current)};this.db.data=clone(next);return{committed:true,snapshot:new Snapshot(next)}}}class FakeDb{constructor(data){this.data=clone(data)}ref(){return new Ref(this)}}
const now=Date.parse('2026-10-01T00:00:00+07:00'),coach='coach_12345678',athlete='athlete_12345678',athlete2='athlete_87654321';
const proof=id=>({path:`private/group-class-slip/${id}/request/proof.jpg`,name:'proof.jpg',size:1024,contentType:'image/jpeg',uploadedAt:now});
function seed(){return{users:{[coach]:{role:'coach',status:'active',displayName:'Coach Test',subscription:{trialEndsAt:now+86400000}},[athlete]:{role:'athlete',displayName:'Athlete One'},[athlete2]:{role:'athlete',displayName:'Athlete Two'}},coachPaymentPublic:{[coach]:{verificationStatus:'approved'}},coachAvailability:{[coach]:{travelBufferMin:0,maxClassesPerDay:8}},bookings:{},coachPublicSchedule:{[coach]:{}},coachTimeOff:{[coach]:{}},coachGroupClasses:{[coach]:{}},coachGroupClassRequests:{}}}
const createInput=(requestId='create_request_123')=>({actorUid:coach,input:{requestId,action:'create',title:'Tennis Group',sport:'tennis',capacity:2,date:'2026-10-10',start:'10:00',end:'11:00',venueName:'VISDA',priceSatang:100000,note:''},now});
async function create(db){return service.execute(db,createInput())}async function submit(db,classId,id=athlete,requestId=`submit_${id}`){return service.execute(db,{actorUid:id,input:{requestId,action:'submit_paid',coachId:coach,classId,paymentProof:proof(id)},now})}
test('server creates one future class and replays the same command without duplicates',async()=>{const db=new FakeDb(seed()),first=await create(db),second=await create(db);assert.equal(first.classId,second.classId);assert.equal(second.replay,true);assert.equal(Object.keys(db.data.coachGroupClasses[coach]).length,1);assert.equal(db.data.coachGroupClasses[coach][first.classId].approvedCount,0)});
test('athlete submission uses server price, stores private metadata and rejects duplicates',async()=>{const db=new FakeDb(seed()),{classId}=await create(db),result=await submit(db,classId),request=db.data.coachGroupClassRequests[coach][classId][athlete];assert.equal(result.status,'pending');assert.equal(request.priceSatang,100000);assert.equal(request.paymentProofStorage.path,proof(athlete).path);assert.equal(Object.hasOwn(request,'paymentProofDataUrl'),false);assert.equal((await submit(db,classId)).replay,true);await assert.rejects(()=>submit(db,classId,athlete,'different_request_123'),error=>error.code==='GROUP_REQUEST_EXISTS')});
test('approval atomically reserves the final seat and creates an immutable income row',async()=>{const db=new FakeDb(seed()),{classId}=await create(db);db.data.coachGroupClasses[coach][classId].approvedCount=1;await submit(db,classId,athlete);await submit(db,classId,athlete2);const decide=id=>service.execute(db,{actorUid:coach,input:{requestId:`decide_${id}`,action:'decide',classId,athleteId:id,decision:'approved'},now});const results=await Promise.all([decide(athlete),decide(athlete2)]);assert.equal(results.filter(row=>row.status==='approved').length,1);assert.equal(results.filter(row=>row.status==='rejected'&&row.reason==='class_full').length,1);assert.equal(db.data.coachGroupClasses[coach][classId].approvedCount,2);assert.equal(Object.keys(db.data.paymentTransactions).length,1);const rejected=Object.values(db.data.coachGroupClassRequests[coach][classId]).find(row=>row.status==='rejected');assert.equal(rejected.paymentStatus,'refund_required')});
test('schedule change validates conflicts and notifies every active participant',async()=>{const db=new FakeDb(seed()),{classId}=await create(db);await submit(db,classId);const result=await service.execute(db,{actorUid:coach,input:{requestId:'schedule_request_123',action:'update_schedule',classId,date:'2026-10-11',start:'12:00',end:'13:00',venueName:'TROPP'},now});assert.equal(result.notified,1);assert.equal(db.data.coachGroupClasses[coach][classId].venueName,'TROPP');assert.equal(Object.keys(db.data.notifications[athlete]).length,1)});
test('cancelling a paid class marks requests for refund and cannot be replayed with changed intent',async()=>{const db=new FakeDb(seed()),{classId}=await create(db);await submit(db,classId);const request={actorUid:coach,input:{requestId:'status_request_123',action:'set_status',classId,status:'cancelled'},now},result=await service.execute(db,request);assert.equal(result.notified,1);assert.equal(db.data.coachGroupClassRequests[coach][classId][athlete].paymentStatus,'refund_required');assert.equal((await service.execute(db,request)).replay,true);await assert.rejects(()=>service.execute(db,{...request,input:{...request.input,status:'closed'}}),error=>error.code==='REQUEST_CONFLICT')});

