'use strict';const{test}=require('node:test');const assert=require('node:assert/strict');const group=require('../functions-mobile/group-class.cjs');
const now=Date.parse('2026-10-01T00:00:00+07:00'),actor='coach_12345678',requestId='request_12345678';
const input={action:'create',requestId,title:'Tennis Beginner',sport:'tennis',capacity:4,date:'2026-10-10',start:'10:00',end:'11:00',venueName:'VISDA',priceSatang:100000,note:''};
test('Group Class create validation accepts a future paid class and deterministic id',()=>{assert.ok(group.createInput(input,now));assert.equal(group.classId(actor,requestId),group.classId(actor,requestId));assert.match(group.classId(actor,requestId),/^GC_[A-F0-9]{20}$/)});
test('past, free, invalid capacity and reversed time fail closed',()=>{for(const change of [{date:'2026-09-30'},{priceSatang:0},{capacity:1},{end:'09:00'}])assert.equal(group.createInput({...input,...change},now),null)});
test('proof must be a bounded owned private image',()=>{const proof={path:'private/group-class-slip/athlete_12345678/request/proof.jpg',name:'proof.jpg',size:1024,contentType:'image/jpeg',uploadedAt:now};assert.deepEqual(group.proof(proof,'athlete_12345678'),proof);assert.equal(group.proof({...proof,path:'private/group-class-slip/other/proof.jpg'},'athlete_12345678'),null);assert.equal(group.proof({...proof,contentType:'image/svg+xml'},'athlete_12345678'),null)});
test('legacy evidence compatibility accepts only bounded image data or Firebase Storage URLs',()=>{assert.equal(group.legacyProof('data:image/jpeg;base64,'+'A'.repeat(120)),true);assert.equal(group.legacyProof('data:text/html;base64,'+'A'.repeat(120)),false);assert.equal(group.legacyProof('https://example.invalid/'+'a'.repeat(120)),false)});
test('coach access requires active role and a current subscription or grace period',()=>{assert.equal(group.subscribed({role:'coach',status:'active',subscription:{trialEndsAt:now+1}},now),true);assert.equal(group.subscribed({role:'coach',status:'active',subscription:{trialEndsAt:now-259200001}},now),false);assert.equal(group.subscribed({role:'athlete',status:'active',subscription:{trialEndsAt:now+1}},now),false)});
test('request ids cannot contain Firebase path separators or forbidden key characters',()=>{for(const value of ['short','request.with.dot','request/with/slash','request#hash'])assert.equal(group.validRequestId(value),null);assert.equal(group.validRequestId('request_safe-123'),'request_safe-123')});

