'use strict';
const{test}=require('node:test');const assert=require('node:assert/strict');const{readFileSync}=require('node:fs');const path=require('node:path');const vm=require('node:vm');const Core=require('../booking-server-client-core.js');
function fixture(){
  const calls=[],alerts=[],items=new Map(),buttons=new Map();
  for(const id of ['cdSupportInput395','cdAdminSupportInput395','c70ChatInput']){const button={disabled:false};buttons.set(id,button);items.set(id,{value:'',parentElement:{querySelector:()=>button}})}items.set('cdSupportSendStatus',{textContent:''});
  const root={CoachDiBookingServerCore:Core,CoachDiBookingServer:{call:async(name,data)=>{calls.push({name,data});return{ok:true}}},coachDiFirebaseApp:{auth:()=>({currentUser:{uid:'user_12345678'}})},sessionStorage:{getItem:key=>items.get(`storage:${key}`)||null,setItem:(key,value)=>items.set(`storage:${key}`,value),removeItem:key=>items.delete(`storage:${key}`)},state:{c70AdminChatUid:'athlete_87654321'},document:{getElementById:id=>items.get(id)||null,body:{contains:()=>true}},alert:value=>alerts.push(String(value))};root.window=root;
  vm.runInNewContext(readFileSync(path.join(__dirname,'../chat-server-client.js'),'utf8'),root);return{root,calls,alerts,items,buttons};
}
test('user and both legacy Admin support send routes use the same callable',async()=>{const f=fixture(),routes=[['cdSupportInput395',()=>f.root.cd395SendSupport()],['cdAdminSupportInput395',()=>f.root.cd395AdminReply('coach_12345678')],['c70ChatInput',()=>f.root.c70SendAdminChat()]];for(const[id,send]of routes){f.items.get(id).value=`ข้อความ ${id}`;await send();assert.equal(f.items.get(id).value,'')}assert.deepEqual(f.calls.map(row=>row.name),Array(3).fill('sendSupportChatMessage'));assert.deepEqual(f.calls.map(row=>row.data.threadUid),['user_12345678','coach_12345678','athlete_87654321']);assert.equal(f.items.get('cdSupportSendStatus').textContent,'ส่งแล้ว');assert.deepEqual(f.alerts,[])});
test('rapid repeat is coalesced and a failed support call preserves the draft',async()=>{const f=fixture(),input=f.items.get('c70ChatInput');let release;f.root.CoachDiBookingServer.call=async(name,data)=>{f.calls.push({name,data});await new Promise(resolve=>{release=resolve});return{ok:true}};input.value='ส่งครั้งเดียว';const first=f.root.c70SendAdminChat(),second=f.root.c70SendAdminChat();assert.equal(await second,null);assert.equal(f.calls.length,1);release();await first;assert.equal(input.value,'');f.root.CoachDiBookingServer.call=async()=>{throw Object.assign(Error('failure'),{details:{code:'INVALID_SUPPORT_MESSAGE'}})};input.value='ข้อความที่ต้องแก้';await f.root.c70SendAdminChat();assert.equal(input.value,'ข้อความที่ต้องแก้');assert.match(f.alerts.at(-1),/4,000/);assert.match(f.items.get('cdSupportSendStatus').textContent,/ส่งไม่สำเร็จ/);assert.equal(f.buttons.get('c70ChatInput').disabled,false)});
