'use strict';
const{test}=require('node:test');const assert=require('node:assert/strict');const service=require('../functions-mobile/support-chat-service.cjs');
const clone=value=>value==null?value:structuredClone(value);const parts=path=>String(path||'').split('/').filter(Boolean);
function read(root,path){let node=root;for(const part of parts(path)){if(node==null)return null;node=node[part]}return node==null?null:node}
function write(root,path,value){const keys=parts(path);if(!keys.length){for(const key of Object.keys(root))delete root[key];Object.assign(root,clone(value)||{});return}let node=root;for(const key of keys.slice(0,-1))node=node[key]||(node[key]={});const last=keys.at(-1);if(value===null)delete node[last];else node[last]=clone(value)}
class Snapshot{constructor(value){this.value=clone(value)}val(){return clone(this.value)}}
class Ref{constructor(db,path){this.db=db;this.path=path}async get(){return new Snapshot(read(this.db.data,this.path))}async transaction(callback){const current=clone(read(this.db.data,this.path)),next=callback(current);if(next===undefined)return{committed:false,snapshot:new Snapshot(current)};write(this.db.data,this.path,next);return{committed:true,snapshot:new Snapshot(next)}}async update(updates){if(this.db.failRootUpdateOnce&&!this.path){this.db.failRootUpdateOnce=false;throw Error('simulated network loss')}for(const[path,value]of Object.entries(updates))write(this.db.data,this.path?`${this.path}/${path}`:path,value)}}
class FakeDb{constructor(data){this.data=clone(data);this.failRootUpdateOnce=false}ref(path=''){return new Ref(this,path)}}
const now=Date.parse('2026-10-01T12:00:00+07:00');
function seed(){return{users:{admin_12345678:{role:'admin',displayName:'Admin One'},admin_87654321:{role:'admin',displayName:'Admin Two'},athlete_12345678:{role:'athlete',displayName:'Athlete Test'},coach_12345678:{role:'coach',displayName:'Coach Test'},outsider_12345678:{role:'venue',displayName:'Venue Test'}}}}
const request=(actorUid='athlete_12345678',requestId='request_12345678',text=' ขอความช่วยเหลือ\r\nเรื่องการจอง ',threadUid='')=>({actorUid,input:{requestId,text,threadUid},now});

test('athlete support message creates one thread message, Admin inbox item and generic push per Admin',async()=>{const db=new FakeDb(seed()),result=await service.execute(db,request());assert.equal(result.ok,true);assert.equal(result.threadUid,'athlete_12345678');assert.equal(result.adminPushCount,2);const message=read(db.data,`supportChats/athlete_12345678/messages/${result.messageId}`);assert.deepEqual(message,{senderId:'athlete_12345678',senderRole:'athlete',text:'ขอความช่วยเหลือ\nเรื่องการจอง',createdAt:now});const notice=read(db.data,`adminSupportNotifications/${result.adminNotificationId}`);assert.equal(notice.message,'ขอความช่วยเหลือ\nเรื่องการจอง');for(const uid of ['admin_12345678','admin_87654321']){const pushes=read(db.data,`notifications/${uid}`);assert.equal(Object.keys(pushes).length,1);assert.equal(Object.values(pushes)[0].type,'support_request');assert.doesNotMatch(Object.values(pushes)[0].message,/เรื่องการจอง/)}});
test('Admin reply is limited to a real Athlete or Coach and creates one recipient notification',async()=>{const db=new FakeDb(seed()),result=await service.execute(db,request('admin_12345678','request_admin123','ตรวจสอบให้แล้วค่ะ','coach_12345678'));assert.equal(result.threadUid,'coach_12345678');assert.equal(result.adminPushCount,0);assert.equal(read(db.data,`supportChats/coach_12345678/messages/${result.messageId}/senderRole`),'admin');assert.equal(read(db.data,`notifications/coach_12345678/${result.notificationId}/type`),'support_message');assert.equal(read(db.data,'adminSupportNotifications'),null)});
test('same request replays without duplicates and preserves read state',async()=>{const db=new FakeDb(seed()),first=await service.execute(db,request());write(db.data,`adminSupportNotifications/${first.adminNotificationId}/read`,true);const again=await service.execute(db,request());assert.equal(again.replay,true);assert.equal(Object.keys(read(db.data,'supportChats/athlete_12345678/messages')).length,1);assert.equal(Object.keys(read(db.data,'notifications/admin_12345678')).length,1);assert.equal(read(db.data,`adminSupportNotifications/${first.adminNotificationId}/read`),true)});
test('retry repairs the command result after a lost response without duplicate side effects',async()=>{const db=new FakeDb(seed());db.failRootUpdateOnce=true;await assert.rejects(()=>service.execute(db,request()),/network loss/);const result=await service.execute(db,request());assert.equal(result.replay,true);assert.equal(Object.keys(read(db.data,'supportChats/athlete_12345678/messages')).length,1);assert.equal(Object.keys(read(db.data,'adminSupportNotifications')).length,1);assert.equal(read(db.data,'supportChatCommandResults/athlete_12345678/request_12345678/status'),'completed')});
test('changed request, unsupported role and invalid Admin target are rejected',async()=>{const db=new FakeDb(seed());await service.execute(db,request());await assert.rejects(()=>service.execute(db,request('athlete_12345678','request_12345678','เปลี่ยนข้อความ')),error=>error.code==='REQUEST_CONFLICT');await assert.rejects(()=>service.execute(db,request('outsider_12345678','request_outside1','ข้อความ')),error=>error.code==='NOT_SUPPORT_PARTICIPANT');await assert.rejects(()=>service.execute(db,request('admin_12345678','request_missing1','ข้อความ','missing_user')),error=>error.code==='SUPPORT_USER_NOT_FOUND')});
test('empty, oversized and malformed requests are rejected before chat writes',async()=>{for(const req of [request('athlete_12345678','short','hello'),request('athlete_12345678','request_empty123','   '),request('athlete_12345678','request_long123','x'.repeat(service.MAX_TEXT+1))]){const db=new FakeDb(seed());await assert.rejects(()=>service.execute(db,req),error=>error.code==='INVALID_SUPPORT_MESSAGE');assert.equal(read(db.data,'supportChats'),null)}});
